export interface Monster {
  id: number;
  name: string;
  image: string;
  filter: string; // CSS filter for creating variations
  isLegendary?: boolean;
}

export const MONSTER_DATA: Record<number, Monster> = {
  // --- Normal Monsters (1-20) ---
  1: { id: 1, name: '綠豆包', image: 'monsters/mon_01.png', filter: '' },
  2: { id: 2, name: '小火狐', image: 'monsters/mon_02.png', filter: '' },
  3: { id: 3, name: '水滴怪', image: 'monsters/mon_03.png', filter: '' },
  4: { id: 4, name: '岩石龜', image: 'monsters/mon_04.png', filter: '' },
  5: { id: 5, name: '電氣蜂', image: 'monsters/mon_05.png', filter: '' },
  6: { id: 6, name: '雪冰堡', image: 'monsters/mon_06.png', filter: '' },
  7: { id: 7, name: '大地岩魔', image: 'monsters/mon_07.png', filter: '' },
  8: { id: 8, name: '雲彩飛鳥', image: 'monsters/mon_08.png', filter: '' },
  9: { id: 9, name: '夢幻粉菇', image: 'monsters/mon_09.png', filter: '' },
  10: { id: 10, name: '星光妖精', image: 'monsters/mon_12.png', filter: '' }, // Using 12 as 10
  
  // Variations using hue-rotate to bypass generating 10 more images
  11: { id: 11, name: '霸王花', image: 'monsters/mon_01.png', filter: 'hue-rotate(120deg) brightness(1.2)' },
  12: { id: 12, name: '幽冥靈狐', image: 'monsters/mon_02.png', filter: 'hue-rotate(240deg) saturate(2)' },
  13: { id: 13, name: '毒水怪', image: 'monsters/mon_03.png', filter: 'hue-rotate(90deg)' },
  14: { id: 14, name: '黑曜龜', image: 'monsters/mon_04.png', filter: 'grayscale(1) brightness(0.5)' },
  15: { id: 15, name: '血紅狂蜂', image: 'monsters/mon_05.png', filter: 'hue-rotate(300deg)' },
  16: { id: 16, name: '暗影雪魔', image: 'monsters/mon_06.png', filter: 'hue-rotate(180deg)' },
  17: { id: 17, name: '鋼鐵巨甲', image: 'monsters/mon_10.png', filter: '' }, // Base 10 not used in 1-10
  18: { id: 18, name: '雷霆金鳥', image: 'monsters/mon_08.png', filter: 'hue-rotate(60deg)' },
  19: { id: 19, name: '幽光靈傘', image: 'monsters/mon_09.png', filter: 'hue-rotate(180deg)' },
  20: { id: 20, name: '暗夜妖精', image: 'monsters/mon_12.png', filter: 'hue-rotate(200deg)' },
  
  // --- Legendary Boss Monsters (21-23) ---
  21: { id: 21, name: '雷霆機關神', image: 'monsters/mon_10.png', filter: 'drop-shadow(0 0 20px yellow) hue-rotate(45deg) saturate(2)', isLegendary: true },
  22: { id: 22, name: '聖靈幽火', image: 'monsters/mon_11.png', filter: 'drop-shadow(0 0 20px cyan)', isLegendary: true },
  23: { id: 23, name: '黃金究極王', image: 'monsters/mon_01.png', filter: 'hue-rotate(60deg) saturate(2) drop-shadow(0 0 40px gold)', isLegendary: true },

  // --- Grammar Boss Monsters (24-27) ---
  24: { id: 24, name: '時光幽魂', image: 'monsters/mon_25.png', filter: 'drop-shadow(0 0 15px purple)', isLegendary: true },
  25: { id: 25, name: '大地護衛', image: 'monsters/mon_24.png', filter: 'drop-shadow(0 0 15px green)', isLegendary: true },
  26: { id: 26, name: '永恆機甲', image: 'monsters/mon_23.png', filter: 'drop-shadow(0 0 15px blue)', isLegendary: true },
  27: { id: 27, name: '烈焰之舞', image: 'monsters/mon_22.png', filter: 'drop-shadow(0 0 15px red)', isLegendary: true },
  28: { id: 28, name: '雷電松鼠', image: 'monsters/mon_26.png', filter: '' },
  29: { id: 29, name: '岩甲地鼠', image: 'monsters/mon_27.png', filter: '' },
  30: { id: 30, name: '格鬥鋼拳', image: 'monsters/mon_28.png', filter: 'drop-shadow(0 0 15px red)', isLegendary: true },
  31: { id: 31, name: '爆炎雙頭龍', image: 'monsters/mon_13.png', filter: '' },
  32: { id: 32, name: '劇毒蠍子', image: 'monsters/mon_14.png', filter: '' },
  33: { id: 33, name: '幻影蝙蝠', image: 'monsters/mon_15.png', filter: '' },
  34: { id: 34, name: '冰晶海妖', image: 'monsters/mon_16.png', filter: '' },
  35: { id: 35, name: '狂暴野豬', image: 'monsters/mon_17.png', filter: '' },
  36: { id: 36, name: '綠林長老', image: 'monsters/mon_18.png', filter: '' },
  37: { id: 37, name: '熔岩巨猿', image: 'monsters/mon_19.png', filter: '' },
  38: { id: 38, name: '深海巨怪', image: 'monsters/mon_20.png', filter: '' },
  39: { id: 39, name: '聖光獨角獸', image: 'monsters/mon_21.png', filter: 'drop-shadow(0 0 20px gold)', isLegendary: true },
  40: { id: 40, name: '冰藍雙頭龍', image: 'monsters/mon_13.png', filter: 'hue-rotate(180deg)' },
  41: { id: 41, name: '劇毒紅蠍', image: 'monsters/mon_14.png', filter: 'hue-rotate(120deg) saturate(1.5)' },
  42: { id: 42, name: '黃金蝙蝠', image: 'monsters/mon_15.png', filter: 'hue-rotate(45deg)' },
  43: { id: 43, name: '深淵海妖', image: 'monsters/mon_16.png', filter: 'hue-rotate(90deg) brightness(0.8)' },
  44: { id: 44, name: '魔化野豬', image: 'monsters/mon_17.png', filter: 'hue-rotate(270deg)' },
  45: { id: 45, name: '枯木長老', image: 'monsters/mon_18.png', filter: 'grayscale(0.8) brightness(0.9)' },
  46: { id: 46, name: '冰霜巨猿', image: 'monsters/mon_19.png', filter: 'hue-rotate(180deg)' },
  47: { id: 47, name: '變種海怪', image: 'monsters/mon_20.png', filter: 'hue-rotate(300deg)' },
  48: { id: 48, name: '墮落獨角獸', image: 'monsters/mon_21.png', filter: 'hue-rotate(180deg) invert(0.8) drop-shadow(0 0 15px purple)', isLegendary: true },
  49: { id: 49, name: '虛空護衛', image: 'monsters/mon_24.png', filter: 'hue-rotate(200deg) brightness(0.7) drop-shadow(0 0 15px magenta)', isLegendary: true },
  50: { id: 50, name: '疾風松鼠', image: 'monsters/mon_26.png', filter: 'hue-rotate(90deg)' },
  51: { id: 51, name: '藍晶石怪', image: 'monsters/mon_01.png', filter: 'hue-rotate(240deg) saturate(200%)' },
  52: { id: 52, name: '紫曜岩魔', image: 'monsters/mon_02.png', filter: 'hue-rotate(280deg) brightness(1.2)' },
  53: { id: 53, name: '翡翠毒蛙', image: 'monsters/mon_03.png', filter: 'hue-rotate(120deg) contrast(150%)' },
  54: { id: 54, name: '赤焰獅子', image: 'monsters/mon_04.png', filter: 'hue-rotate(30deg) saturate(150%)' },
  55: { id: 55, name: '冰霜雪怪', image: 'monsters/mon_05.png', filter: 'hue-rotate(200deg) brightness(1.5)' },
  56: { id: 56, name: '暗影蝙蝠', image: 'monsters/mon_06.png', filter: 'grayscale(80%) brightness(0.6)' },
  57: { id: 57, name: '黃金飛龍', image: 'monsters/mon_07.png', filter: 'hue-rotate(60deg) saturate(300%) drop-shadow(0 0 10px gold)', isLegendary: true },
  58: { id: 58, name: '深海巨蛇', image: 'monsters/mon_08.png', filter: 'hue-rotate(220deg) contrast(200%) drop-shadow(0 0 10px blue)', isLegendary: true },
  59: { id: 59, name: '大地巨像', image: 'monsters/mon_09.png', filter: 'sepia(50%) saturate(80%) brightness(0.9)' },
  60: { id: 60, name: '烈風靈鳥', image: 'monsters/mon_10.png', filter: 'hue-rotate(180deg) saturate(250%)' },
  61: { id: 61, name: '幻光龍族', image: 'monsters/mon_09.png', filter: 'hue-rotate(68deg) saturate(117%)' },
  62: { id: 62, name: '赤紅松鼠', image: 'monsters/mon_06.png', filter: 'hue-rotate(306deg) saturate(146%)' },
  63: { id: 63, name: '鋼鐵蝙蝠', image: 'monsters/mon_17.png', filter: 'hue-rotate(117deg) saturate(113%)' },
  64: { id: 64, name: '冰霜巨龜', image: 'monsters/mon_03.png', filter: 'hue-rotate(301deg) saturate(123%)' },
  65: { id: 65, name: '暗影龍族', image: 'monsters/mon_28.png', filter: 'hue-rotate(192deg) saturate(117%)' },
  66: { id: 66, name: '深淵妖精', image: 'monsters/mon_06.png', filter: 'hue-rotate(262deg) saturate(148%)' },
  67: { id: 67, name: '鋼鐵松鼠', image: 'monsters/mon_14.png', filter: 'hue-rotate(142deg) saturate(147%)' },
  68: { id: 68, name: '赤紅護衛', image: 'monsters/mon_21.png', filter: 'hue-rotate(341deg) saturate(103%)' },
  69: { id: 69, name: '幻光海妖', image: 'monsters/mon_10.png', filter: 'hue-rotate(155deg) saturate(129%)' },
  70: { id: 70, name: '雷爆松鼠', image: 'monsters/mon_14.png', filter: 'hue-rotate(188deg) saturate(308%) drop-shadow(0 0 15px gold)', isLegendary: true },
  71: { id: 71, name: '劇毒妖精', image: 'monsters/mon_12.png', filter: 'hue-rotate(217deg) saturate(114%)' },
  72: { id: 72, name: '雷爆巨魔', image: 'monsters/mon_11.png', filter: 'hue-rotate(44deg) saturate(132%)' },
  73: { id: 73, name: '雷爆海妖', image: 'monsters/mon_14.png', filter: 'hue-rotate(206deg) saturate(114%)' },
  74: { id: 74, name: '蒼藍龍族', image: 'monsters/mon_07.png', filter: 'hue-rotate(323deg) saturate(118%)' },
  75: { id: 75, name: '幻光蝙蝠', image: 'monsters/mon_08.png', filter: 'hue-rotate(186deg) saturate(127%)' },
  76: { id: 76, name: '劇毒護衛', image: 'monsters/mon_22.png', filter: 'hue-rotate(353deg) saturate(144%)' },
  77: { id: 77, name: '劇毒松鼠', image: 'monsters/mon_15.png', filter: 'hue-rotate(206deg) saturate(131%)' },
  78: { id: 78, name: '神聖護衛', image: 'monsters/mon_25.png', filter: 'hue-rotate(124deg) saturate(136%)' },
  79: { id: 79, name: '神聖海妖', image: 'monsters/mon_16.png', filter: 'hue-rotate(77deg) saturate(107%)' },
  80: { id: 80, name: '雷爆龍族', image: 'monsters/mon_27.png', filter: 'hue-rotate(14deg) saturate(230%) drop-shadow(0 0 15px gold)', isLegendary: true },
  81: { id: 81, name: '冰霜巨魔', image: 'monsters/mon_21.png', filter: 'hue-rotate(73deg) saturate(123%)' },
  82: { id: 82, name: '冰霜妖精', image: 'monsters/mon_15.png', filter: 'hue-rotate(319deg) saturate(127%)' },
  83: { id: 83, name: '雷爆護衛', image: 'monsters/mon_05.png', filter: 'hue-rotate(96deg) saturate(147%)' },
  84: { id: 84, name: '深淵妖精', image: 'monsters/mon_14.png', filter: 'hue-rotate(310deg) saturate(131%)' },
  85: { id: 85, name: '深淵巨龜', image: 'monsters/mon_18.png', filter: 'hue-rotate(302deg) saturate(131%)' },
  86: { id: 86, name: '蒼藍護衛', image: 'monsters/mon_05.png', filter: 'hue-rotate(230deg) saturate(119%)' },
  87: { id: 87, name: '暗影蝙蝠', image: 'monsters/mon_23.png', filter: 'hue-rotate(278deg) saturate(124%)' },
  88: { id: 88, name: '蒼藍巨魔', image: 'monsters/mon_26.png', filter: 'hue-rotate(242deg) saturate(132%)' },
  89: { id: 89, name: '雷爆蝙蝠', image: 'monsters/mon_04.png', filter: 'hue-rotate(96deg) saturate(120%)' },
  90: { id: 90, name: '蒼藍蝙蝠', image: 'monsters/mon_28.png', filter: 'hue-rotate(332deg) saturate(264%) drop-shadow(0 0 15px gold)', isLegendary: true },
  91: { id: 91, name: '冰霜蝙蝠', image: 'monsters/mon_12.png', filter: 'hue-rotate(72deg) saturate(140%)' },
  92: { id: 92, name: '暗影巨龜', image: 'monsters/mon_09.png', filter: 'hue-rotate(87deg) saturate(147%)' },
  93: { id: 93, name: '雷爆巨魔', image: 'monsters/mon_18.png', filter: 'hue-rotate(328deg) saturate(128%)' },
  94: { id: 94, name: '雷爆護衛', image: 'monsters/mon_09.png', filter: 'hue-rotate(140deg) saturate(105%)' },
  95: { id: 95, name: '暗影海妖', image: 'monsters/mon_21.png', filter: 'hue-rotate(161deg) saturate(129%)' },
  96: { id: 96, name: '冰霜松鼠', image: 'monsters/mon_22.png', filter: 'hue-rotate(45deg) saturate(109%)' },
  97: { id: 97, name: '暗影護衛', image: 'monsters/mon_24.png', filter: 'hue-rotate(347deg) saturate(108%)' },
  98: { id: 98, name: '蒼藍蝙蝠', image: 'monsters/mon_01.png', filter: 'hue-rotate(49deg) saturate(141%)' },
  99: { id: 99, name: '冰霜海妖', image: 'monsters/mon_04.png', filter: 'hue-rotate(197deg) saturate(127%)' },
  100: { id: 100, name: '劇毒巨魔', image: 'monsters/mon_12.png', filter: 'hue-rotate(319deg) saturate(390%) drop-shadow(0 0 15px gold)', isLegendary: true },
  101: { id: 101, name: '伊布幻狐', image: 'monsters/mon_29.png', filter: '' },
  102: { id: 102, name: '電氣萌犬', image: 'monsters/mon_30.png', filter: '' },
  103: { id: 103, name: '葉靈魔法貓', image: 'monsters/mon_31.png', filter: '' },
  104: { id: 104, name: '水滴泡泡兔', image: 'monsters/mon_32.png', filter: '' },
  105: { id: 105, name: '烈焰絨鼠', image: 'monsters/mon_33.png', filter: '' },
  106: { id: 106, name: '愛睏小熊', image: 'monsters/mon_34.png', filter: '' },
  107: { id: 107, name: '迷你飛龍寶寶', image: 'monsters/mon_35.png', filter: '' },
  108: { id: 108, name: '超能雲貓', image: 'monsters/mon_36.png', filter: '' },
  109: { id: 109, name: '極凍企鵝', image: 'monsters/mon_37.png', filter: '' },
  110: { id: 110, name: '岩石硬殼龜', image: 'monsters/mon_38.png', filter: '' },
};
