export interface VocabWord {
  id: string;
  word: string;
  partOfSpeech: string;
  meaning: string;
  englishMeaning?: string;
}

// Level 6 — Week 19-20 (2026/6/15 ~ 6/23)
// School: 陽光森林全美語安親學校
export const vocabData: VocabWord[] = [
  { id: "knight_a1b2c", word: "knight", partOfSpeech: "n.", meaning: "騎士" },
  { id: "clown_d3e4f", word: "clown", partOfSpeech: "n.", meaning: "小丑" },
  { id: "princess_g5h6i", word: "princess", partOfSpeech: "n.", meaning: "公主、王妃" },
  { id: "glad_j7k8l", word: "glad", partOfSpeech: "adj.", meaning: "高興的" },
  { id: "juggler_m9n0o", word: "juggler", partOfSpeech: "n.", meaning: "雜耍演員" },
  { id: "king_p1q2r", word: "king", partOfSpeech: "n.", meaning: "國王" },
  { id: "prince_s3t4u", word: "prince", partOfSpeech: "n.", meaning: "王子、親王" },
  { id: "accident_v5w6x", word: "accident", partOfSpeech: "n.", meaning: "意外、事故" },
  { id: "pirate_y7z8a", word: "pirate", partOfSpeech: "n.", meaning: "海盜" },
  { id: "magician_b9c0d", word: "magician", partOfSpeech: "n.", meaning: "魔術師；魔法師" },
  { id: "carnival_e1f2g", word: "carnival", partOfSpeech: "n.", meaning: "嘉年華" },
  { id: "pair_h3i4j", word: "pair", partOfSpeech: "n.", meaning: "一雙、一對" },
  { id: "dancer_k5l6m", word: "dancer", partOfSpeech: "n.", meaning: "舞者" },
  { id: "queen_n7o8p", word: "queen", partOfSpeech: "n.", meaning: "女王；王后" },
  { id: "brilliant_q9r0s", word: "brilliant", partOfSpeech: "adj.", meaning: "有才華的；聰穎的；傑出的" },
  { id: "practice_t1u2v", word: "practice", partOfSpeech: "v.", meaning: "練習" },
  { id: "acrobat_w3x4y", word: "acrobat", partOfSpeech: "n.", meaning: "雜技演員" },
  { id: "lady_z5a6b", word: "lady", partOfSpeech: "n.", meaning: "女士" },
  { id: "laugh_c7d8e", word: "laugh", partOfSpeech: "v.", meaning: "大笑" },
  { id: "unplanned_f9g0h", word: "unplanned", partOfSpeech: "adj.", meaning: "沒有計劃的；意料之外的" },
  { id: "action_i1j2k", word: "action", partOfSpeech: "n.", meaning: "行動、行為" },
  { id: "hospital_l3m4n", word: "hospital", partOfSpeech: "n.", meaning: "醫院" },
  { id: "score_o5p6q", word: "score", partOfSpeech: "v.", meaning: "得分" },
  { id: "movietheater_r7s8t", word: "movie theater", partOfSpeech: "n.", meaning: "電影院" },
  { id: "onpurpose_u9v0w", word: "on purpose", partOfSpeech: "ph.", meaning: "故意地" },
  { id: "onavacation_x1y2z", word: "on a vacation", partOfSpeech: "ph.", meaning: "休假中、度假中" },
  { id: "empty_a3b4c", word: "empty", partOfSpeech: "adj./v.", meaning: "空的、無意義的；倒空" },
  { id: "boring_d5e6f", word: "boring", partOfSpeech: "adj.", meaning: "無聊的" },
  { id: "email_g7h8i", word: "e-mail", partOfSpeech: "n.", meaning: "電子郵件" },
  { id: "interesting_j9k0l", word: "interesting", partOfSpeech: "adj.", meaning: "有趣的" },
  { id: "camera_m1n2o", word: "camera", partOfSpeech: "n.", meaning: "照相機" },
  { id: "dangerous_p3q4r", word: "dangerous", partOfSpeech: "adj.", meaning: "危險的、有威脅的" },
  { id: "getstuck_s5t6u", word: "get stuck", partOfSpeech: "ph.", meaning: "卡住、困住" },
  { id: "nurse_v7w8x", word: "nurse", partOfSpeech: "n.", meaning: "護士、護理人員" },
  { id: "glasses_y9z0a", word: "glasses", partOfSpeech: "n.", meaning: "眼鏡" },
  { id: "hamburger_b1c2d", word: "hamburger", partOfSpeech: "n.", meaning: "漢堡；漢堡牛肉餅" },
  { id: "break_e3f4g", word: "break", partOfSpeech: "v.", meaning: "打破、破裂、毀壞、破壞" },
  { id: "purpose_h5i6j", word: "purpose", partOfSpeech: "n.", meaning: "意圖、原因、目的" },
  { id: "puton_k7l8m", word: "put on", partOfSpeech: "ph.", meaning: "把...穿戴上；塗抹、擦上" },
  { id: "lizard_n9o0p", word: "lizard", partOfSpeech: "n.", meaning: "蜥蜴" },
  { id: "laptop_q1r2s", word: "laptop", partOfSpeech: "n.", meaning: "筆記型電腦" },
  { id: "climb_t3u4v", word: "climb", partOfSpeech: "v.", meaning: "爬、攀登、爬升" },
  { id: "playagainst_w5x6y", word: "play against", partOfSpeech: "ph.", meaning: "與...比賽；對抗" },
  { id: "seat_z7a8b", word: "seat", partOfSpeech: "n.", meaning: "座位" },
  { id: "juggle_c9d0e", word: "juggle", partOfSpeech: "v.", meaning: "玩雜耍" },
  { id: "rope_f1g2h", word: "rope", partOfSpeech: "n.", meaning: "繩索" },
  { id: "against_i3j4k", word: "against", partOfSpeech: "prep.", meaning: "反對、與...相反、緊靠著" },
  { id: "hate_l5m6n", word: "hate", partOfSpeech: "v.", meaning: "討厭、厭惡" },
  { id: "costume_o7p8q", word: "costume", partOfSpeech: "n.", meaning: "服裝、戲服" },
  { id: "trapeze_r9s0t", word: "trapeze", partOfSpeech: "n.", meaning: "高空秋千" },
  { id: "circus_u1v2w", word: "circus", partOfSpeech: "n.", meaning: "馬戲團" },
  { id: "suddenly_x3y4z", word: "suddenly", partOfSpeech: "adv.", meaning: "突然地、驟然" },
  { id: "dotrick_a5b6c", word: "do trick", partOfSpeech: "ph.", meaning: "變戲法、做惡作劇" },
  { id: "trampoline_d7e8f", word: "trampoline", partOfSpeech: "n.", meaning: "彈跳床、蹦床" },
  { id: "station_g9h0i", word: "station", partOfSpeech: "n.", meaning: "車站、電台、站、局" },
  { id: "plant_j1k2l", word: "plant", partOfSpeech: "n.", meaning: "植物" },
  { id: "lorry_m3n4o", word: "lorry (Br.)", partOfSpeech: "n.", meaning: "卡車、貨車" },
  { id: "footballmatch_p5q6r", word: "football match", partOfSpeech: "n.", meaning: "足球比賽" },
  { id: "subway_s7t8u", word: "subway", partOfSpeech: "n.", meaning: "地鐵" },
  { id: "medicine_v9w0x", word: "medicine", partOfSpeech: "n.", meaning: "藥物" },
  { id: "neck_y1z2a", word: "neck", partOfSpeech: "n.", meaning: "脖子、頸部" },
  { id: "head_b3c4d", word: "head", partOfSpeech: "n.", meaning: "頭" },
  { id: "wood_e5f6g", word: "wood", partOfSpeech: "n.", meaning: "木頭、木材" },
  { id: "atcamp_h7i8j", word: "at camp", partOfSpeech: "ph.", meaning: "在露營地" },
  { id: "hip_k9l0m", word: "hip", partOfSpeech: "n.", meaning: "臀部" },
  { id: "hand_n1o2p", word: "hand", partOfSpeech: "n.", meaning: "手" },
  { id: "inthewoods_q3r4s", word: "in the woods", partOfSpeech: "ph.", meaning: "在森林裡" },
  { id: "cover_t5u6v", word: "cover", partOfSpeech: "v.", meaning: "覆蓋、遮蔽" },
  { id: "shoulder_w7x8y", word: "shoulder", partOfSpeech: "n.", meaning: "肩膀" },
  { id: "foot_z9a0b", word: "foot", partOfSpeech: "n.", meaning: "腳、足" },
  { id: "touch_c1d2e", word: "touch", partOfSpeech: "v.", meaning: "觸摸、碰" },
  { id: "exciting_f3g4h", word: "exciting", partOfSpeech: "adj.", meaning: "令人興奮的、使人激動的" },
  { id: "elbow_i5j6k", word: "elbow", partOfSpeech: "n.", meaning: "手肘" },
  { id: "oval_l7m8n", word: "oval", partOfSpeech: "n./adj.", meaning: "橢圓形；橢圓形的" },
  { id: "try_o9p0q", word: "try", partOfSpeech: "v.", meaning: "嘗試、努力" },
  { id: "thinkof_r1s2t", word: "think of", partOfSpeech: "ph.", meaning: "想到、發明、覺得、認為" },
  { id: "knee_u3v4w", word: "knee", partOfSpeech: "n.", meaning: "膝蓋" },
  { id: "overlap_x5y6z", word: "overlap", partOfSpeech: "v.", meaning: "重疊" },
  { id: "hike_a7b8c", word: "hike", partOfSpeech: "v.", meaning: "健行" },
  { id: "plan_d9e0f", word: "plan", partOfSpeech: "v.", meaning: "計劃、安排" },
  { id: "canoe_g1h2i", word: "canoe", partOfSpeech: "v.", meaning: "划獨木舟" },
  { id: "snowboard_j3k4l", word: "snowboard", partOfSpeech: "v.", meaning: "單板滑雪" },
  { id: "helmet_m5n6o", word: "helmet", partOfSpeech: "n.", meaning: "安全帽" },
  { id: "weatherreport_p7q8r", word: "weather report", partOfSpeech: "n.", meaning: "天氣預報" },
  { id: "grill_s9t0u", word: "grill", partOfSpeech: "v.", meaning: "燒烤" },
  { id: "iceskate_v1w2x", word: "ice-skate", partOfSpeech: "v.", meaning: "溜冰" },
  { id: "sunscreen_y3z4a", word: "sunscreen", partOfSpeech: "n.", meaning: "防曬乳" },
  { id: "tomorrow_b5c6d", word: "tomorrow", partOfSpeech: "n.", meaning: "明天" },
  { id: "fish_e7f8g", word: "fish", partOfSpeech: "v.", meaning: "釣魚、捕魚" },
  { id: "inlineskate_h9i0j", word: "in-line skate", partOfSpeech: "n./v.", meaning: "直排輪鞋；溜直排輪" },
  { id: "lifejacket_k1l2m", word: "life jacket", partOfSpeech: "n.", meaning: "救生衣" },
  { id: "remember_n3o4p", word: "remember", partOfSpeech: "v.", meaning: "記得、記起" },
  { id: "watchbirds_q5r6s", word: "watch birds", partOfSpeech: "ph.", meaning: "賞鳥" },
  { id: "skateboard_t7u8v", word: "skateboard", partOfSpeech: "n./v.", meaning: "滑板；溜滑板" },
  { id: "fastenseatbelt_w9x0y", word: "fasten your seatbelt", partOfSpeech: "ph.", meaning: "繫上安全帶" },
  { id: "snowy_z1a2b", word: "snowy", partOfSpeech: "adj.", meaning: "下雪的" },
  { id: "ski_c3d4e", word: "ski", partOfSpeech: "n./v.", meaning: "滑雪板；滑雪" },
  { id: "surf_f5g6h", word: "surf", partOfSpeech: "v.", meaning: "衝浪、上網" },
  { id: "stone_i7j8k", word: "stone", partOfSpeech: "n.", meaning: "石頭、石塊" },
  { id: "around_l9m0n", word: "around", partOfSpeech: "adv./prep.", meaning: "周圍、圍繞" },
  { id: "hippopotamus_o1p2q", word: "hippopotamus", partOfSpeech: "n.", meaning: "河馬" },
  { id: "seal_r3s4t", word: "seal", partOfSpeech: "n.", meaning: "海豹" },
  { id: "octopus_u5v6w", word: "octopus", partOfSpeech: "n.", meaning: "章魚" },
  { id: "foolish_x7y8z", word: "foolish", partOfSpeech: "adj.", meaning: "愚蠢的、傻的" },
  { id: "gorilla_a9b0c", word: "gorilla", partOfSpeech: "n.", meaning: "大猩猩" },
  { id: "dolphin_d1e2f", word: "dolphin", partOfSpeech: "n.", meaning: "海豚" },
  { id: "length_g3h4i", word: "length", partOfSpeech: "n.", meaning: "長度" },
  { id: "fence_j5k6l", word: "fence", partOfSpeech: "n.", meaning: "柵欄、籬笆" },
  { id: "panda_m7n8o", word: "panda", partOfSpeech: "n.", meaning: "貓熊" },
  { id: "squid_p9q0r", word: "squid", partOfSpeech: "n.", meaning: "魷魚" },
  { id: "weight_s1t2u", word: "weight", partOfSpeech: "n.", meaning: "重量、體重" },
  { id: "taste_v3w4x", word: "taste", partOfSpeech: "v.", meaning: "品嚐" },
  { id: "caterpillar_y5z6a", word: "caterpillar", partOfSpeech: "n.", meaning: "毛毛蟲" },
  { id: "beetle_b7c8d", word: "beetle", partOfSpeech: "n.", meaning: "甲蟲" },
  { id: "blond_e9f0g", word: "blond", partOfSpeech: "adj.", meaning: "（毛髮）金黃色的" },
  { id: "seem_h1i2j", word: "seem", partOfSpeech: "v.", meaning: "似乎、看起來好像" },
  { id: "eel_k3l4m", word: "eel", partOfSpeech: "n.", meaning: "鰻魚" },
  { id: "crab_n5o6p", word: "crab", partOfSpeech: "n.", meaning: "螃蟹" },
  { id: "beard_q7r8s", word: "beard", partOfSpeech: "n.", meaning: "（下巴上的）鬍鬚" },
  { id: "stayhome_t9u0v", word: "stay home", partOfSpeech: "ph.", meaning: "待在家" },
  { id: "butterfly_w1x2y", word: "butterfly", partOfSpeech: "n.", meaning: "蝴蝶" },
  { id: "bee_z3a4b", word: "bee", partOfSpeech: "n.", meaning: "蜜蜂" },
  { id: "whale_c5d6e", word: "whale", partOfSpeech: "n.", meaning: "鯨魚" },
  { id: "shark_f7g8h", word: "shark", partOfSpeech: "n.", meaning: "鯊魚" },
  { id: "shoulderlength_i9j0k", word: "shoulder-length", partOfSpeech: "adj.", meaning: "齊肩的、及肩的" },
  { id: "earrings_l1m2n", word: "earrings", partOfSpeech: "n.", meaning: "耳環" },
  { id: "ocean_o3p4q", word: "ocean", partOfSpeech: "n.", meaning: "海洋" },
  { id: "famous_r5s6t", word: "famous", partOfSpeech: "adj.", meaning: "有名的、著名的" },
  { id: "straight_u7v8w", word: "straight", partOfSpeech: "adj.", meaning: "直的" },
  { id: "sunglasses_x9y0z", word: "sunglasses", partOfSpeech: "n.", meaning: "太陽眼鏡" },
  { id: "invite_a1b2c3", word: "invite", partOfSpeech: "v.", meaning: "邀請" },
  { id: "afraid_d4e5f6", word: "afraid", partOfSpeech: "adj.", meaning: "害怕的、擔憂的" },
  { id: "curly_g7h8i9", word: "curly", partOfSpeech: "adj.", meaning: "捲曲的" },
  { id: "stick_j0k1l2", word: "stick", partOfSpeech: "n.", meaning: "枝條、木棍" },
  { id: "first_m3n4o5", word: "first", partOfSpeech: "det.", meaning: "第一、首先" },
  { id: "island_p6q7r8", word: "island", partOfSpeech: "n.", meaning: "島嶼" },
  { id: "wavy_s9t0u1", word: "wavy", partOfSpeech: "adj.", meaning: "波浪狀的" },
  { id: "grass_v2w3x4", word: "grass", partOfSpeech: "n.", meaning: "草" },
  { id: "problem_y5z6a7", word: "problem", partOfSpeech: "n.", meaning: "問題、困難" },
  { id: "beableto_b8c9d0", word: "be able to", partOfSpeech: "ph.", meaning: "能夠、有...能力" },
  { id: "necklace_e1f2g3", word: "necklace", partOfSpeech: "n.", meaning: "項鍊" },
  { id: "sand_h4i5j6", word: "sand", partOfSpeech: "n.", meaning: "沙子" },
  { id: "land_k7l8m9", word: "land", partOfSpeech: "v.", meaning: "著陸、降落" },
  { id: "sportsstar_n0o1p2", word: "sports star", partOfSpeech: "n.", meaning: "運動明星" },
  { id: "shoulderlengthhair_q3r4s5", word: "shoulder-length hair", partOfSpeech: "n.", meaning: "及肩長髮" },
  { id: "shorthair_t6u7v8", word: "short hair", partOfSpeech: "n.", meaning: "短髮" },
  { id: "longhair_w9x0y1", word: "long hair", partOfSpeech: "n.", meaning: "長髮" },
  { id: "straighthair_z2a3b4", word: "straight hair", partOfSpeech: "n.", meaning: "直髮" },
  { id: "curlyhair_c5d6e7", word: "curly hair", partOfSpeech: "n.", meaning: "捲髮" },
  { id: "wavyhair_f8g9h0", word: "wavy hair", partOfSpeech: "n.", meaning: "波浪狀捲髮" },
  { id: "watch_i1j2k3", word: "watch", partOfSpeech: "n.", meaning: "手錶" },
  { id: "gloves_l4m5n6", word: "gloves", partOfSpeech: "n.", meaning: "手套" },
  { id: "belt_o7p8q9", word: "belt", partOfSpeech: "n.", meaning: "腰帶" },
  { id: "baseball_r0s1t2", word: "baseball", partOfSpeech: "n.", meaning: "棒球" },
  { id: "basketball_u3v4w5", word: "basketball", partOfSpeech: "n.", meaning: "籃球" },
  { id: "volleyball_x6y7z8", word: "volleyball", partOfSpeech: "n.", meaning: "排球" },
  { id: "golf_a9b0c1", word: "golf", partOfSpeech: "n.", meaning: "高爾夫球" },
  { id: "helpmyparents_d2e3f4", word: "help my parents", partOfSpeech: "ph.", meaning: "幫忙我的父母" },
  { id: "metal_g5h6i7", word: "metal", partOfSpeech: "n.", meaning: "金屬" },
  { id: "surprised_j8k9l0", word: "surprised", partOfSpeech: "adj.", meaning: "驚訝的、意外的" },
  { id: "tabletennis_m1n2o3", word: "table tennis / tennis", partOfSpeech: "n.", meaning: "桌球 / 網球" },
  { id: "visitmyfriend_p4q5r6", word: "visit my friend", partOfSpeech: "ph.", meaning: "拜訪我的朋友" },
  { id: "study_s7t8u9", word: "study", partOfSpeech: "v.", meaning: "學習、研究" },
  { id: "smart_v0w1x2", word: "smart", partOfSpeech: "adj.", meaning: "聰明的（US）；時髦的（UK）" },
  { id: "practicepiano_y3z4a5", word: "practice the piano", partOfSpeech: "ph.", meaning: "練習鋼琴" },
  { id: "workonproject_b6c7d8", word: "work on a project", partOfSpeech: "ph.", meaning: "進行一個專案" },
  { id: "cage_e9f0g1", word: "cage", partOfSpeech: "n.", meaning: "籠子" },
  { id: "useful_h2i3j4", word: "useful", partOfSpeech: "adj.", meaning: "有用的、有效的" },
  { id: "usecomputer_k5l6m7", word: "use the computer", partOfSpeech: "ph.", meaning: "使用電腦" },
  { id: "clay_n8o9p0", word: "clay", partOfSpeech: "n.", meaning: "黏土" },
  { id: "wall_q1r2s3", word: "wall", partOfSpeech: "n.", meaning: "牆壁" },
  { id: "delicious_t4u5v6", word: "delicious", partOfSpeech: "adj.", meaning: "美味的" },
  { id: "talkonphone_w7x8y9", word: "talk on the phone", partOfSpeech: "ph.", meaning: "講電話" },
  { id: "glass_z0a1b2", word: "glass", partOfSpeech: "n.", meaning: "玻璃製品、杯子" },
  { id: "pull_c3d4e5", word: "pull", partOfSpeech: "v.", meaning: "拉、拖、抽出" },
  { id: "toward_f6g7h8", word: "toward", partOfSpeech: "prep.", meaning: "朝向、接近" },
  { id: "careful_i9j0k1", word: "careful", partOfSpeech: "adj.", meaning: "仔細的、小心的、認真的" },
  { id: "goat_l2m3n4", word: "goat", partOfSpeech: "n.", meaning: "山羊" },
  { id: "riverbridge_o5p6q7", word: "river / bridge", partOfSpeech: "n.", meaning: "河流 / 橋樑" },
  { id: "wear_r8s9t0", word: "wear", partOfSpeech: "v.", meaning: "穿、戴" },
  { id: "angry_u1v2w3", word: "angry", partOfSpeech: "adj.", meaning: "生氣的、憤怒的" },
  { id: "fly_x4y5z6", word: "fly", partOfSpeech: "v.", meaning: "飛行" },
  { id: "through_a7b8c9", word: "through", partOfSpeech: "prep.", meaning: "穿過、通過" },
  { id: "leaf_d0e1f2", word: "leaf", partOfSpeech: "n.", meaning: "葉子" },
  { id: "laughat_g3h4i5", word: "laugh at", partOfSpeech: "ph.", meaning: "嘲笑" },
  { id: "practiceving_j6k7l8", word: "practice V-ing / N.", partOfSpeech: "ph.", meaning: "練習..." },
  { id: "lookforwardto_m9n0o1", word: "look forward to V-ing / N.", partOfSpeech: "ph.", meaning: "期待、盼望..." },
  { id: "ridesubway_p2q3r4", word: "ride the subway to...", partOfSpeech: "ph.", meaning: "搭地鐵去..." },
  { id: "beaboutto_s5t6u7", word: "be about to V.", partOfSpeech: "ph.", meaning: "快要、即將..." },
  { id: "goout_v8w9x0", word: "go out", partOfSpeech: "ph.", meaning: "熄滅、外出" },
  { id: "waterplants_y1z2a3", word: "water the plants", partOfSpeech: "ph.", meaning: "給植物澆水" },
  { id: "takemedicine_b4c5d6", word: "take (some) medicine", partOfSpeech: "ph.", meaning: "服藥" },
  { id: "pickup_e7f8g9", word: "pick up", partOfSpeech: "ph.", meaning: "接送、撿起、順道購買" },
  { id: "haveanidea_h0i1j2", word: "have an idea to V.", partOfSpeech: "ph.", meaning: "想出一個辦法、主意" },
  { id: "gocamping_k3l4m5", word: "go camping", partOfSpeech: "ph.", meaning: "去露營" },
  { id: "putout_n6o7p8", word: "put out", partOfSpeech: "ph.", meaning: "撲滅、熄滅；出版、生產" },
  { id: "befoolishof_q9r0s1", word: "be foolish of", partOfSpeech: "ph.", meaning: "做...是很傻的" },
  { id: "takecareeof_t2u3v4", word: "take (good) care of", partOfSpeech: "ph.", meaning: "（好好）照顧" },
  { id: "behappywith_w5x6y7", word: "be happy with", partOfSpeech: "ph.", meaning: "對...感到滿意、高興" },
  { id: "invitesb_z8a9b0", word: "invite sb. to V.", partOfSpeech: "ph.", meaning: "邀請某人做..." },
  { id: "runinto_c1d2e3", word: "run into", partOfSpeech: "ph.", meaning: "偶然遇見、遭遇困難、碰撞" },
  { id: "besurprisedto_f4g5h6", word: "be surprised to V.", partOfSpeech: "ph.", meaning: "對（做某事）感到驚訝" },
  { id: "findout_i7j8k9", word: "find out", partOfSpeech: "ph.", meaning: "發現、得知、查明" },
  { id: "getridof_l0m1n2", word: "get rid of", partOfSpeech: "ph.", meaning: "擺脫、除去、處理" },
  { id: "s1", word: "torch", partOfSpeech: "n.", meaning: "手電筒" },
  { id: "s2", word: "comb", partOfSpeech: "n.", meaning: "梳子" },
  { id: "s3", word: "sleeping bag", partOfSpeech: "n.", meaning: "睡袋" },
  { id: "s4", word: "teddy", partOfSpeech: "n.", meaning: "玩具熊" },
  { id: "s5", word: "pillow", partOfSpeech: "n.", meaning: "枕頭" },
  { id: "s6", word: "contest", partOfSpeech: "n.", meaning: "比賽" },
  { id: "s7", word: "piece", partOfSpeech: "n.", meaning: "片/塊" },
  { id: "s8", word: "serve", partOfSpeech: "v.", meaning: "服務；提供" },
  { id: "s9", word: "winner", partOfSpeech: "n.", meaning: "贏家；獲勝者" },
  { id: "s10", word: "chart", partOfSpeech: "n.", meaning: "圖表" },
  { id: "s11", word: "pyjamas(Br.)/pajamas(US)", partOfSpeech: "n.", meaning: "睡衣褲" },
  { id: "s12", word: "blanket", partOfSpeech: "n.", meaning: "毯子" },
  { id: "s13", word: "sunglasses", partOfSpeech: "n.", meaning: "墨鏡" },
  { id: "s14", word: "mat", partOfSpeech: "n.", meaning: "地墊" },
  { id: "s15", word: "towel", partOfSpeech: "n.", meaning: "毛巾" },
  { id: "s16", word: "toothbrush", partOfSpeech: "n.", meaning: "牙刷" },
  { id: "s17", word: "campsite", partOfSpeech: "n.", meaning: "露營地" },
  { id: "s18", word: "dinosaur", partOfSpeech: "n.", meaning: "恐龍" },
  { id: "s19", word: "surfboard", partOfSpeech: "n.", meaning: "衝浪板" },
  { id: "s20", word: "postcard", partOfSpeech: "n.", meaning: "明信片" },
  { id: "s21", word: "mall", partOfSpeech: "n.", meaning: "購物中心" },
  { id: "s22", word: "noise", partOfSpeech: "n.", meaning: "噪音" },
  { id: "s23", word: "spotted", partOfSpeech: "adj.", meaning: "有斑點的" },
  { id: "s24", word: "owl", partOfSpeech: "n.", meaning: "貓頭鷹" },
  { id: "s25", word: "enormous", partOfSpeech: "adj.", meaning: "巨大的" },
  { id: "s26", word: "hurt", partOfSpeech: "v.", meaning: "使受傷" },
  { id: "s27", word: "stand", partOfSpeech: "v.", meaning: "站立" },
  { id: "s28", word: "surf", partOfSpeech: "v.", meaning: "衝浪；上網" },
  { id: "s29", word: "turn", partOfSpeech: "v.", meaning: "轉向" },
  { id: "s30", word: "weather", partOfSpeech: "n.", meaning: "天氣" },
  { id: "s31", word: "figure", partOfSpeech: "n.", meaning: "模型/外型" },
  { id: "s32", word: "fast", partOfSpeech: "adj.", meaning: "快的" },
  { id: "s33", word: "slow", partOfSpeech: "adj.", meaning: "慢的" },
  { id: "s34", word: "loud", partOfSpeech: "adj.", meaning: "大聲的" },
  { id: "s35", word: "quiet", partOfSpeech: "adj.", meaning: "安靜的" },
  { id: "s36", word: "snowy", partOfSpeech: "adj.", meaning: "下雪的" },
  { id: "s37", word: "sandy", partOfSpeech: "adj.", meaning: "含沙的" },
  { id: "s38", word: "snowboard", partOfSpeech: "v.", meaning: "單板滑雪" },
  { id: "s39", word: "skate", partOfSpeech: "v.", meaning: "溜冰" },
  { id: "s40", word: "strong", partOfSpeech: "adj.", meaning: "強壯的" },
  { id: "s41", word: "difficult", partOfSpeech: "adj.", meaning: "困難的" },
  { id: "s42", word: "different", partOfSpeech: "adj.", meaning: "不同的" },
  { id: "s43", word: "cousin", partOfSpeech: "n.", meaning: "堂(表)兄弟姊妹" },
  { id: "s44", word: "everyone", partOfSpeech: "pron.", meaning: "每個人" },
  { id: "s45", word: "brilliant", partOfSpeech: "adj.", meaning: "聰穎的；出色的" },
  { id: "s46", word: "bear", partOfSpeech: "n.", meaning: "熊" },
  { id: "s47", word: "monkey", partOfSpeech: "n.", meaning: "猴子" },
  { id: "s48", word: "dark", partOfSpeech: "adj.", meaning: "黑暗的" },
  { id: "s49", word: "scared", partOfSpeech: "adj.", meaning: "驚恐的" },
  { id: "s50", word: "surfing", partOfSpeech: "n.", meaning: "衝浪運動" },
  { id: "s51", word: "horse", partOfSpeech: "n.", meaning: "馬" },
  { id: "s52", word: "snake", partOfSpeech: "n.", meaning: "蛇" },
  { id: "s53", word: "lion", partOfSpeech: "n.", meaning: "獅子" },
  { id: "s54", word: "high / low", partOfSpeech: "adj.", meaning: "高的/低的" },
  { id: "s55", word: "art", partOfSpeech: "n.", meaning: "藝術" },
  { id: "s56", word: "road", partOfSpeech: "n.", meaning: "路" },
  { id: "s57", word: "same", partOfSpeech: "adj.", meaning: "一樣的" },
  { id: "s58", word: "ride", partOfSpeech: "v.", meaning: "騎車" },
  { id: "s59", word: "club", partOfSpeech: "n.", meaning: "社團" },
  { id: "s60", word: "science", partOfSpeech: "n.", meaning: "科學" },
  { id: "s61", word: "popular", partOfSpeech: "adj.", meaning: "受歡迎的" },
  { id: "s62", word: "library", partOfSpeech: "n.", meaning: "圖書館" },
  { id: "s63", word: "exercise", partOfSpeech: "v.", meaning: "練習；運動" },
  { id: "s64", word: "famous", partOfSpeech: "adj.", meaning: "有名的" },
  { id: "s65", word: "weekend", partOfSpeech: "n.", meaning: "週末" },
  { id: "s66", word: "mouse", partOfSpeech: "n.", meaning: "老鼠" },
  { id: "s67", word: "elephant", partOfSpeech: "n.", meaning: "大象" },
  { id: "s68", word: "parrot", partOfSpeech: "n.", meaning: "鸚鵡" },
  { id: "s69", word: "hen", partOfSpeech: "n.", meaning: "母雞" },
  { id: "s70", word: "relax", partOfSpeech: "v.", meaning: "放鬆" },
  { id: "s71", word: "rock", partOfSpeech: "n.", meaning: "岩石" },
  { id: "s72", word: "bell", partOfSpeech: "n.", meaning: "鐘" },
  { id: "s73", word: "fewest", partOfSpeech: "adj.", meaning: "最少的" },
  { id: "s74", word: "mountain bike", partOfSpeech: "v.", meaning: "騎登山越野車" },
  { id: "s75", word: "sport", partOfSpeech: "n.", meaning: "體育；運動" },
  { id: "s76", word: "food court", partOfSpeech: "n.", meaning: "美食廣場" },
  { id: "s77", word: "floor", partOfSpeech: "n.", meaning: "地板" },
  { id: "s78", word: "relaxing", partOfSpeech: "adj.", meaning: "令人放鬆的" },
  { id: "s79", word: "tortoise", partOfSpeech: "n.", meaning: "陸龜" },
  { id: "s80", word: "butterfly", partOfSpeech: "n.", meaning: "蝴蝶" },
  { id: "s81", word: "rest", partOfSpeech: "n.", meaning: "休息" },
  { id: "s82", word: "canary", partOfSpeech: "n.", meaning: "金絲雀" },
  { id: "s83", word: "lizard", partOfSpeech: "n.", meaning: "蜥蜴" },
  { id: "s84", word: "stick insects", partOfSpeech: "n.", meaning: "竹節蟲" },
  { id: "s85", word: "snail", partOfSpeech: "n.", meaning: "蝸牛" },
  { id: "s86", word: "guinea pig", partOfSpeech: "n.", meaning: "天竺鼠" },
  { id: "s87", word: "hide", partOfSpeech: "v.", meaning: "藏起來" },
  { id: "s88", word: "storm", partOfSpeech: "n.", meaning: "暴風雨" },
  { id: "s89", word: "stormy", partOfSpeech: "adj.", meaning: "暴風雨的" },
  { id: "s90", word: "cloudy", partOfSpeech: "adj.", meaning: "陰天的；多雲的" },
  { id: "s91", word: "rabbit", partOfSpeech: "n.", meaning: "兔子" },
  { id: "s92", word: "reptile center", partOfSpeech: "n.", meaning: "爬行動物中心" },
  { id: "s93", word: "rescue", partOfSpeech: "n.", meaning: "救援" },
  { id: "s94", word: "owner", partOfSpeech: "n.", meaning: "主人" },
  { id: "s95", word: "python", partOfSpeech: "n.", meaning: "巨蟒" },
  { id: "s96", word: "crocodile", partOfSpeech: "n.", meaning: "鱷魚" },
  { id: "s97", word: "giant", partOfSpeech: "adj.", meaning: "巨大的" },
  { id: "s98", word: "shame", partOfSpeech: "n.", meaning: "可惜；羞恥" },
  { id: "s99", word: "chameleon", partOfSpeech: "n.", meaning: "變色龍" },
  { id: "s100", word: "stripy", partOfSpeech: "adj.", meaning: "條紋的" },
  { id: "s101", word: "excited", partOfSpeech: "adj.", meaning: "興奮的" },
  { id: "s102", word: "energy", partOfSpeech: "n.", meaning: "活力；能量" },
  { id: "s103", word: "hear", partOfSpeech: "v.", meaning: "聽到" },
  { id: "s104", word: "thunder", partOfSpeech: "n.", meaning: "雷" },
  { id: "s105", word: "lightning", partOfSpeech: "n.", meaning: "閃電" },
  { id: "s106", word: "warm", partOfSpeech: "adj.", meaning: "溫暖的" },
  { id: "s107", word: "bicycle", partOfSpeech: "n.", meaning: "腳踏車" },
  { id: "s108", word: "sound", partOfSpeech: "v.", meaning: "聽起來" },
  { id: "s109", word: "fish", partOfSpeech: "n.", meaning: "魚" },
  { id: "s110", word: "change", partOfSpeech: "v.", meaning: "交換；改變" },
  { id: "s111", word: "Habitat", partOfSpeech: "n.", meaning: "棲息地" },
  { id: "s112", word: "fact file", partOfSpeech: "n.", meaning: "事實檔案" },
  { id: "s113", word: "iguana", partOfSpeech: "n.", meaning: "鬣蜥" },
  { id: "s114", word: "tongue", partOfSpeech: "n.", meaning: "舌頭" },
  { id: "s115", word: "insect", partOfSpeech: "n.", meaning: "昆蟲" },
  { id: "s116", word: "go on vacation", partOfSpeech: "phr.", meaning: "去度假" },
  { id: "s117", word: "temperature", partOfSpeech: "n.", meaning: "溫度" },
  { id: "s118", word: "ladybird/ladybug", partOfSpeech: "n.", meaning: "瓢蟲" },
  { id: "s119", word: "grasshopper", partOfSpeech: "n.", meaning: "蚱蜢" },
  { id: "s120", word: "dragonfly", partOfSpeech: "n.", meaning: "蜻蜓" },
  { id: "s121", word: "body parts", partOfSpeech: "n.", meaning: "身體部位" },
  { id: "s122", word: "have fun", partOfSpeech: "phr.", meaning: "玩得開心" },
  { id: "s123", word: "neck", partOfSpeech: "n.", meaning: "脖子" },
  { id: "s124", word: "necklace", partOfSpeech: "n.", meaning: "項鍊" },
  { id: "s125", word: "present", partOfSpeech: "n.", meaning: "禮物" },
  { id: "s126", word: "mean", partOfSpeech: "adj.", meaning: "小氣的;刻薄的" },
  { id: "s127", word: "live", partOfSpeech: "v.", meaning: "生活" },
  { id: "s128", word: "windy", partOfSpeech: "adj.", meaning: "颳(刮)風的" },
  { id: "s129", word: "vacation", partOfSpeech: "n.", meaning: "假期" },
  { id: "s130", word: "beach", partOfSpeech: "n.", meaning: "海邊;海灘" },
  { id: "s131", word: "address", partOfSpeech: "n.", meaning: "地址" },
  { id: "s132", word: "hotel", partOfSpeech: "n.", meaning: "飯店" },
  { id: "s133", word: "go surfing / fishing", partOfSpeech: "phr.", meaning: "去衝浪 ; 去釣魚" },
  { id: "s134", word: "tempo", partOfSpeech: "n.", meaning: "拍子; 節奏" },
  { id: "s135", word: "bathhouse", partOfSpeech: "n.", meaning: "澡堂; 公共浴室" },
  { id: "s136", word: "get excited", partOfSpeech: "ph.", meaning: "感到興奮" },
  { id: "s137", word: "hear sth. on the news", partOfSpeech: "ph.", meaning: "在新聞上聽到..." },
  { id: "s138", word: "read sth. in the newspaper", partOfSpeech: "ph.", meaning: "在報紙上看到..." },
  { id: "s139", word: "queen bee", partOfSpeech: "n.", meaning: "蜂后" },
  { id: "s140", word: "spider", partOfSpeech: "n.", meaning: "蜘蛛" },
  { id: "s141", word: "sting", partOfSpeech: "v.", meaning: "叮咬" },
  { id: "s142", word: "be made of", partOfSpeech: "ph.", meaning: "用...做成" },
  { id: "s143", word: "spend the weekend", partOfSpeech: "ph.", meaning: "度過周末" },
  { id: "s144", word: "have a picnic", partOfSpeech: "ph.", meaning: "去野餐" },
  { id: "s145", word: "restaurant", partOfSpeech: "n.", meaning: "餐廳" },
  { id: "s146", word: "boat", partOfSpeech: "n.", meaning: "小船" },
  { id: "s147", word: "camping", partOfSpeech: "n.", meaning: "露營" },
  { id: "s148", word: "matter", partOfSpeech: "n.", meaning: "事情" },
  { id: "s149", word: "pitch", partOfSpeech: "n.", meaning: "音調" },
  { id: "s150", word: "tempo", partOfSpeech: "n.", meaning: "拍子; 節奏" },
  { id: "s151", word: "bathhouse", partOfSpeech: "n.", meaning: "澡堂; 公共浴室" },
  { id: "s152", word: "get excited", partOfSpeech: "ph.", meaning: "感到興奮" },
  { id: "s153", word: "hear sth. on the news", partOfSpeech: "ph.", meaning: "在新聞上聽到..." },
  { id: "s154", word: "read sth. in the newspaper", partOfSpeech: "ph.", meaning: "在報紙上看到..." },
  { id: "s155", word: "sleep", partOfSpeech: "v.", meaning: "睡覺" },
  { id: "s156", word: "wish", partOfSpeech: "v.", meaning: "希望" },
  { id: "s157", word: "become", partOfSpeech: "v.", meaning: "變成" },
  { id: "s158", word: "outside", partOfSpeech: "adv.", meaning: "在外面" },
  { id: "s159", word: "anymore", partOfSpeech: "adv.", meaning: "再也不" },
  { id: "s160", word: "go on vacation", partOfSpeech: "phr.", meaning: "去度假" },
  { id: "s161", word: "have fun", partOfSpeech: "phr.", meaning: "玩得很開心" },
  { id: "s162", word: "go surfing/fishing", partOfSpeech: "phr.", meaning: "去衝浪; 去釣魚" },
  { id: "s163", word: "ant", partOfSpeech: "n.", meaning: "螞蟻" },
  { id: "s164", word: "minute", partOfSpeech: "n.", meaning: "分鐘*" },
  { id: "s165", word: "pizza", partOfSpeech: "n.", meaning: "披薩*" },
  { id: "s166", word: "chicken", partOfSpeech: "n.", meaning: "雞;雞肉*" },
  { id: "s167", word: "win(won)", partOfSpeech: "v.", meaning: "贏;獲勝" },
  { id: "s168", word: "museum", partOfSpeech: "n.", meaning: "博物館" },
  { id: "s169", word: "fantastic", partOfSpeech: "adj.", meaning: "極好的" },
  { id: "s170", word: "dynamics", partOfSpeech: "n.", meaning: "動力學; (音樂)力度" },
  { id: "s171", word: "computer", partOfSpeech: "n.", meaning: "電腦" },
  { id: "s172", word: "read(read)", partOfSpeech: "v.", meaning: "閱讀" },
  { id: "s173", word: "watch movies", partOfSpeech: "ph.", meaning: "看電影" },
  { id: "s174", word: "fly", partOfSpeech: "n.", meaning: "蒼蠅" },
  { id: "s175", word: "bee", partOfSpeech: "n.", meaning: "蜜蜂" },
  { id: "s176", word: "get first(second) place", partOfSpeech: "ph.", meaning: "獲得第一(第二)" },
  { id: "s177", word: "be (get/feel) tired", partOfSpeech: "ph.", meaning: "覺得累了" },
  { id: "s178", word: "the same number of ...", partOfSpeech: "ph.", meaning: "數量相同的" },
  { id: "s179", word: "go skiing", partOfSpeech: "ph.", meaning: "去滑雪" },
  { id: "s180", word: "think of ...", partOfSpeech: "ph.", meaning: "認為、覺得;想出" },
  { id: "s181", word: "talk about ...", partOfSpeech: "ph.", meaning: "討論" },
  { id: "s182", word: "one's favorite thing to do is ...", partOfSpeech: "ph.", meaning: "(誰)最喜歡做..." },
  { id: "s183", word: "help sb. with sth.", partOfSpeech: "ph.", meaning: "幫助(誰)做了..." },
  { id: "s184", word: "be made of", partOfSpeech: "ph.", meaning: "用...做成" },
  { id: "s185", word: "spend the weekend", partOfSpeech: "ph.", meaning: "度過週末" },
  { id: "s186", word: "boat/sea/sky", partOfSpeech: "n.", meaning: "小船/海/天空" },
  { id: "s187", word: "Broccoli", partOfSpeech: "n.", meaning: "花椰菜" },
  { id: "s188", word: "Spinach", partOfSpeech: "n.", meaning: "菠菜" },
  { id: "s189", word: "Strawberry", partOfSpeech: "n.", meaning: "草莓" },
  { id: "s190", word: "flour", partOfSpeech: "n.", meaning: "麵粉" },
  { id: "s191", word: "butter", partOfSpeech: "n.", meaning: "奶油" },
  { id: "s192", word: "Cocoa", partOfSpeech: "n.", meaning: "可可粉" },
  { id: "s193", word: "Asparagus", partOfSpeech: "n.", meaning: "蘆筍" },
  { id: "s194", word: "Coconut", partOfSpeech: "n.", meaning: "椰子" },
  { id: "s195", word: "egg", partOfSpeech: "n.", meaning: "蛋" },
  { id: "s196", word: "cheese", partOfSpeech: "n.", meaning: "起司、乳酪" },
  { id: "s197", word: "think about", partOfSpeech: "ph.", meaning: "思考;考慮" },
  { id: "s198", word: "biscuit", partOfSpeech: "n.", meaning: "餅乾" },
  { id: "s199", word: "Sugar", partOfSpeech: "n.", meaning: "糖" },
  { id: "s200", word: "Supermarket", partOfSpeech: "n.", meaning: "超級市場" },
  { id: "s201", word: "present", partOfSpeech: "n.", meaning: "禮物" },
  { id: "s202", word: "surprise", partOfSpeech: "n.", meaning: "驚喜、驚訝" },
  { id: "s203", word: "make friends with", partOfSpeech: "ph.", meaning: "交朋友" },
  { id: "s204", word: "cry", partOfSpeech: "v.", meaning: "哭" },
  { id: "s205", word: "door", partOfSpeech: "n.", meaning: "門" },
  { id: "s206", word: "together", partOfSpeech: "adv.", meaning: "一起" },
  { id: "s207", word: "knock", partOfSpeech: "v.", meaning: "敲;擊" },
  { id: "s208", word: "family", partOfSpeech: "n.", meaning: "家庭" },
  { id: "s209", word: "run away from", partOfSpeech: "ph.", meaning: "逃離; 躲避" },
  { id: "s210", word: "young", partOfSpeech: "adj.", meaning: "年輕的" },
  { id: "s211", word: "worry", partOfSpeech: "v.", meaning: "擔心;發愁" },
  { id: "s212", word: "size", partOfSpeech: "n.", meaning: "尺寸;大小" },
  { id: "s213", word: "team", partOfSpeech: "n.", meaning: "團隊;隊" },
  { id: "s214", word: "score", partOfSpeech: "v.", meaning: "得分" },
  { id: "s215", word: "Funny", partOfSpeech: "adj.", meaning: "有趣的;好笑的" },
  { id: "s216", word: "Look out", partOfSpeech: "ph.", meaning: "小心;當心" },
  { id: "s217", word: "mess", partOfSpeech: "n.", meaning: "雜亂;髒亂" },
  { id: "s218", word: "delicious", partOfSpeech: "adj.", meaning: "美味的" },
  { id: "s219", word: "recipe", partOfSpeech: "n.", meaning: "食譜" },
  { id: "s220", word: "score...in the game", partOfSpeech: "ph.", meaning: "在比賽中得...分" },
  { id: "s221", word: "Ingredient(s)", partOfSpeech: "n.", meaning: "材料、成分" },
  { id: "s222", word: "Slice", partOfSpeech: "n.", meaning: "薄片" },
  { id: "s223", word: "mayonnaise", partOfSpeech: "n.", meaning: "美乃滋" },
  { id: "s224", word: "Decorate", partOfSpeech: "v.", meaning: "裝飾" },
  { id: "s225", word: "caramel", partOfSpeech: "n.", meaning: "焦糖" },
  { id: "s226", word: "worry about", partOfSpeech: "ph.", meaning: "擔心" },
  { id: "s227", word: "vanilla", partOfSpeech: "n.", meaning: "香草" },
  { id: "s228", word: "Sauce", partOfSpeech: "n.", meaning: "醬汁" },
  { id: "s229", word: "future", partOfSpeech: "n.", meaning: "未來" },
  { id: "s230", word: "hospital", partOfSpeech: "n.", meaning: "醫院" },
  { id: "s231", word: "Job", partOfSpeech: "n.", meaning: "工作" },
  { id: "s232", word: "Be good at", partOfSpeech: "ph.", meaning: "對...擅長" },
  { id: "s233", word: "country", partOfSpeech: "n.", meaning: "國家" },
  { id: "s234", word: "star", partOfSpeech: "n.", meaning: "明星" },
  { id: "s235", word: "medal", partOfSpeech: "n.", meaning: "獎牌" },
  { id: "s236", word: "interesting", partOfSpeech: "adj.", meaning: "引起興趣的" },
  { id: "s237", word: "famous", partOfSpeech: "adj.", meaning: "有名的" },
  { id: "s238", word: "flower", partOfSpeech: "n.", meaning: "花" },
  { id: "s239", word: "fruit", partOfSpeech: "n.", meaning: "水果" },
  { id: "s240", word: "leaf", partOfSpeech: "n.", meaning: "葉子" },
  { id: "s241", word: "stem", partOfSpeech: "n.", meaning: "莖" },
  { id: "s242", word: "root", partOfSpeech: "n.", meaning: "根" },
  { id: "s243", word: "make somebody feel better", partOfSpeech: "ph.", meaning: "讓某人感覺好一點" },
  { id: "s244", word: "seed", partOfSpeech: "n.", meaning: "種子" },
  { id: "s245", word: "tomato", partOfSpeech: "n.", meaning: "番茄" },
  { id: "s246", word: "cocoa bean(s)", partOfSpeech: "n.", meaning: "可可豆" },
  { id: "s247", word: "pod", partOfSpeech: "n.", meaning: "豆莢" },
  { id: "s248", word: "carrot", partOfSpeech: "n.", meaning: "胡蘿蔔" },
  { id: "s249", word: "grow up", partOfSpeech: "ph.", meaning: "長大、成長" },
  { id: "s250", word: "lettuce", partOfSpeech: "n.", meaning: "萵苣" },
  { id: "s251", word: "care", partOfSpeech: "v.", meaning: "關心；在乎" },
  { id: "s252", word: "rice", partOfSpeech: "n.", meaning: "米" },
  { id: "s253", word: "be made of", partOfSpeech: "ph.", meaning: "由...製成" },
  { id: "s254", word: "use", partOfSpeech: "v.", meaning: "使用" },
  { id: "s255", word: "take care of", partOfSpeech: "ph.", meaning: "照顧；處理" },
  { id: "s256", word: "vet", partOfSpeech: "n.", meaning: "獸醫" },
  { id: "s257", word: "farmer", partOfSpeech: "n.", meaning: "農夫" },
  { id: "s258", word: "scientist", partOfSpeech: "n.", meaning: "科學家" },
  { id: "s259", word: "dentist", partOfSpeech: "n.", meaning: "牙醫" },
  { id: "s260", word: "easy", partOfSpeech: "adj.", meaning: "容易的" },
  { id: "s261", word: "cookie", partOfSpeech: "n.", meaning: "曲奇、餅乾" },
  { id: "s262", word: "singer", partOfSpeech: "n.", meaning: "歌手" },
  { id: "s263", word: "grandfather", partOfSpeech: "n.", meaning: "祖父" },
  { id: "s264", word: "sound", partOfSpeech: "n.", meaning: "聲音" },
  { id: "s265", word: "give birth", partOfSpeech: "ph.", meaning: "生孩子" },
  { id: "s266", word: "be different from", partOfSpeech: "ph.", meaning: "不同於" },
  { id: "s267", word: "talk", partOfSpeech: "v.", meaning: "講話；談論" },
  { id: "s268", word: "noisy", partOfSpeech: "adj.", meaning: "喧鬧的" },
  { id: "s269", word: "dangerous", partOfSpeech: "adj.", meaning: "危險的" },
  { id: "s270", word: "whale", partOfSpeech: "n.", meaning: "鯨魚" },
  { id: "s271", word: "dolphin", partOfSpeech: "n.", meaning: "海豚" },
  { id: "s272", word: "turtle", partOfSpeech: "n.", meaning: "海龜" },
  { id: "s273", word: "travel", partOfSpeech: "v.", meaning: "旅行" },
  { id: "s274", word: "alone", partOfSpeech: "adj.adv.", meaning: "獨自的(地)、單獨的(地)" },
  { id: "s275", word: "each other", partOfSpeech: "pron.", meaning: "彼此；互相" },
  { id: "s276", word: "take care of", partOfSpeech: "ph.", meaning: "照顧；處理" },
  { id: "s277", word: "scare away", partOfSpeech: "ph.", meaning: "把...嚇跑" },
  { id: "s278", word: "adventure", partOfSpeech: "n.", meaning: "冒險；奇遇" },
  { id: "s279", word: "explore", partOfSpeech: "v.", meaning: "探索" },
  { id: "s280", word: "continent", partOfSpeech: "n.", meaning: "洲、大陸" },
  { id: "s281", word: "teach", partOfSpeech: "v.", meaning: "教" },
  { id: "s282", word: "naughty", partOfSpeech: "adj.", meaning: "淘氣的；調皮的" },
  { id: "s283", word: "be interesting to", partOfSpeech: "ph.", meaning: "某事令人覺得有趣" },
  { id: "s285", word: "swimming pool", partOfSpeech: "n.", meaning: "游泳池" },
  { id: "s286", word: "restaurant", partOfSpeech: "n.", meaning: "餐廳" },
  { id: "s287", word: "library", partOfSpeech: "n.", meaning: "圖書館" },
  { id: "s288", word: "supermarket", partOfSpeech: "n.", meaning: "超級市場" },
  { id: "s289", word: "cheer on", partOfSpeech: "ph.", meaning: "為...加油；打氣" },
  { id: "s290", word: "shopping centre (Br) / shopping center (US)", partOfSpeech: "n.", meaning: "購物中心" },
  { id: "s291", word: "car park (Br) / parking lot (US)", partOfSpeech: "n.", meaning: "停車場" },
  { id: "s292", word: "post office", partOfSpeech: "n.", meaning: "郵局" },
  { id: "s293", word: "station", partOfSpeech: "n.", meaning: "車站" },
  { id: "s294", word: "lose (lose - lost - lost)", partOfSpeech: "v.", meaning: "輸掉；丟失" },
  { id: "s295", word: "shout at", partOfSpeech: "ph.", meaning: "對...大聲喊叫" },
  { id: "s296", word: "stretch", partOfSpeech: "v.", meaning: "伸展、延伸" },
  { id: "s297", word: "pitcher", partOfSpeech: "n.", meaning: "投手" },
  { id: "s298", word: "bat", partOfSpeech: "v. / n.", meaning: "打擊(v.) / 球棒、蝙蝠(n.)" },
  { id: "s299", word: "catch", partOfSpeech: "v.", meaning: "接住、抓住" },
  { id: "s300", word: "throw", partOfSpeech: "v.", meaning: "丟、拋擲" },
  { id: "s301", word: "go to the dentist", partOfSpeech: "ph.", meaning: "看牙醫" },
  { id: "s302", word: "score", partOfSpeech: "v.", meaning: "得分" },
  { id: "s303", word: "tie", partOfSpeech: "v.", meaning: "平手、繫" },
  { id: "s304", word: "baseball", partOfSpeech: "n.", meaning: "棒球" },
  { id: "s305", word: "season", partOfSpeech: "n.", meaning: "季節" },
  { id: "s306", word: "stand", partOfSpeech: "v.", meaning: "站立" },
  { id: "s307", word: "stay up (late)", partOfSpeech: "ph.", meaning: "熬夜" },
  { id: "s308", word: "visitor", partOfSpeech: "n.", meaning: "訪客、遊客" },
  { id: "s309", word: "swing", partOfSpeech: "v. / n.", meaning: "擺動(v.); 鞦韆(n.)" },
  { id: "s310", word: "enormous", partOfSpeech: "adj.", meaning: "巨大的" },
  { id: "s311", word: "airport", partOfSpeech: "n.", meaning: "機場" },
  { id: "s312", word: "slide", partOfSpeech: "n.", meaning: "溜滑梯" },
  { id: "s313", word: "It's time to...", partOfSpeech: "ph.", meaning: "是...的時候了" },
  { id: "s314", word: "important", partOfSpeech: "adj.", meaning: "重要的" },
  { id: "s315", word: "actor", partOfSpeech: "n.", meaning: "演員" },
  { id: "s316", word: "after school", partOfSpeech: "ph.", meaning: "放學後" },
  { id: "s318", word: "hungry", partOfSpeech: "adj.", meaning: "飢餓的" },
  { id: "s319", word: "head for + a place", partOfSpeech: "ph.", meaning: "朝...走去" },
  { id: "s320", word: "breakfast", partOfSpeech: "n.", meaning: "早餐" },
  { id: "s321", word: "cover", partOfSpeech: "v.", meaning: "蓋住；遮蓋" },
  { id: "s322", word: "receive", partOfSpeech: "v.", meaning: "收到" },
  { id: "s323", word: "shout", partOfSpeech: "v.", meaning: "呼喊；吼叫" },
  { id: "s324", word: "hand", partOfSpeech: "v.", meaning: "將...交給" },
  { id: "s325", word: "as busy as a bee", partOfSpeech: "ph.", meaning: "忙個不停" },
  { id: "s326", word: "path", partOfSpeech: "n.", meaning: "小道" },
  { id: "s327", word: "bridge", partOfSpeech: "n.", meaning: "橋" },
  { id: "s328", word: "river", partOfSpeech: "n.", meaning: "河" },
  { id: "s329", word: "area", partOfSpeech: "n.", meaning: "區域；範圍" },
  { id: "s330", word: "wood", partOfSpeech: "n.", meaning: "木頭；樹林" },
  { id: "s331", word: "as sick as a dog", partOfSpeech: "ph.", meaning: "非常虛弱；病得很嚴重" },
  { id: "s332", word: "adventure", partOfSpeech: "n.", meaning: "冒險；奇遇" },
  { id: "s333", word: "symbol", partOfSpeech: "n.", meaning: "符號；標誌；象徵" },
  { id: "s334", word: "cross", partOfSpeech: "v.", meaning: "越過；跨越" },
  { id: "s335", word: "island", partOfSpeech: "n.", meaning: "島；島嶼" },
  { id: "s336", word: "return", partOfSpeech: "v.", meaning: "返回；歸還" },
  { id: "s337", word: "as hungry as a bear", partOfSpeech: "ph.", meaning: "非常餓" },
  { id: "s338", word: "countryside", partOfSpeech: "n.", meaning: "農村；鄉下" },
  { id: "s339", word: "hard / soft", partOfSpeech: "adj.", meaning: "困難的(1)；堅硬的(2) / 柔軟的" },
  { id: "s340", word: "salt", partOfSpeech: "n.", meaning: "鹽" },
  { id: "s341", word: "delicious", partOfSpeech: "adj.", meaning: "美味的" },
  { id: "s342", word: "pour", partOfSpeech: "v.", meaning: "倒、注入" },
  { id: "s343", word: "eat out", partOfSpeech: "ph.", meaning: "外出用餐" },
  { id: "s344", word: "shake", partOfSpeech: "v.", meaning: "搖動；發抖" },
  { id: "s345", word: "dessert", partOfSpeech: "n.", meaning: "甜點" },
  { id: "s346", word: "sweet", partOfSpeech: "adj.", meaning: "甜的；溫和的" },
  { id: "s347", word: "fresh", partOfSpeech: "adj.", meaning: "新鮮的；清新的" },
  { id: "s348", word: "thick", partOfSpeech: "adj.", meaning: "厚的；濃的" },
  { id: "s349", word: "act like...", partOfSpeech: "ph.", meaning: "表現得像..." },
  { id: "s350", word: "school", partOfSpeech: "n.", meaning: "學校" },
  { id: "s351", word: "park", partOfSpeech: "n.", meaning: "公園" },
  { id: "s352", word: "computer", partOfSpeech: "n.", meaning: "電腦" },
  { id: "s353", word: "team", partOfSpeech: "n.", meaning: "隊伍" },
  { id: "s354", word: "picnic", partOfSpeech: "n.", meaning: "野餐" },
  { id: "s355", word: "beach", partOfSpeech: "n.", meaning: "海灘；沙灘" },
  { id: "s356", word: "shop", partOfSpeech: "n.", meaning: "商店" },
  { id: "s357", word: "present", partOfSpeech: "n.", meaning: "禮物" },
  { id: "s358", word: "balloon", partOfSpeech: "n.", meaning: "氣球" },
  { id: "s359", word: "surprise", partOfSpeech: "n.", meaning: "驚喜" },
  { id: "s360", word: "restaurant", partOfSpeech: "n.", meaning: "餐廳" },
  { id: "s361", word: "bedroom", partOfSpeech: "n.", meaning: "臥室" },
  { id: "s362", word: "kitchen", partOfSpeech: "n.", meaning: "廚房" },
  { id: "s363", word: "sugar", partOfSpeech: "n.", meaning: "糖" },
  { id: "s364", word: "fruit", partOfSpeech: "n.", meaning: "水果；果實" },
  { id: "s365", word: "different", partOfSpeech: "adj.", meaning: "不一樣的" },
  { id: "s366", word: "straight", partOfSpeech: "adv.", meaning: "筆直地；坦率地；直接" },
  { id: "s367", word: "show", partOfSpeech: "v.", meaning: "顯示；說明" },
  { id: "s368", word: "(play) badminton", partOfSpeech: "n.", meaning: "羽毛球" },
  { id: "s369", word: "(do) gymnastics", partOfSpeech: "n.", meaning: "體操" },
  { id: "s370", word: "(play) hockey", partOfSpeech: "n.", meaning: "曲棍球" },
  { id: "s371", word: "(play) basketball", partOfSpeech: "n.", meaning: "籃球" },
  { id: "s372", word: "football", partOfSpeech: "n.", meaning: "美式橄欖球(US)；足球(Br)" },
  { id: "s373", word: "turn off", partOfSpeech: "ph.", meaning: "關掉、停止" },
  { id: "s374", word: "(play) tennis", partOfSpeech: "n.", meaning: "網球" },
  { id: "s375", word: "(do) judo", partOfSpeech: "n.", meaning: "柔道" },
  { id: "s376", word: "(play) chess", partOfSpeech: "n.", meaning: "西洋棋" },
  { id: "s377", word: "(play) table tennis", partOfSpeech: "n.", meaning: "桌球" },
  { id: "s378", word: "(play) volleyball", partOfSpeech: "n.", meaning: "排球" },
  { id: "s379", word: "be worried about", partOfSpeech: "ph.", meaning: "對...感到擔憂、憂慮" },
  { id: "s380", word: "polite", partOfSpeech: "adj.", meaning: "有禮貌的" },
  { id: "s381", word: "lady", partOfSpeech: "n.", meaning: "女士" },
  { id: "s382", word: "gentleman", partOfSpeech: "n.", meaning: "紳士、先生" },
  { id: "s383", word: "act", partOfSpeech: "v.", meaning: "行為、表現" },
  { id: "s384", word: "quietly", partOfSpeech: "adv.", meaning: "安靜地" },
  { id: "s385", word: "smile at sb.", partOfSpeech: "ph.", meaning: "對某人微笑" },
  { id: "s386", word: "waiter", partOfSpeech: "n.", meaning: "男服務生" },
  { id: "s387", word: "kind", partOfSpeech: "adj.", meaning: "親切的；和善的" },
  { id: "s388", word: "excuse", partOfSpeech: "v.", meaning: "原諒、寬恕" },
  { id: "s389", word: "hedge", partOfSpeech: "n.", meaning: "樹籬" },
  { id: "s390", word: "adult", partOfSpeech: "n.", meaning: "成人" },
  { id: "s391", word: "talk about", partOfSpeech: "ph.", meaning: "討論、談論" },
  { id: "s392", word: "prefer", partOfSpeech: "v.", meaning: "更(較)喜歡" },
  { id: "s393", word: "ladder", partOfSpeech: "n.", meaning: "梯子" },
  { id: "s394", word: "hole", partOfSpeech: "n.", meaning: "洞、孔" },
  { id: "s395", word: "through", partOfSpeech: "prep.", meaning: "穿越、通過；從頭至尾" },
  { id: "s396", word: "ticket", partOfSpeech: "n.", meaning: "票、券" },
  { id: "s397", word: "be crazy about", partOfSpeech: "ph.", meaning: "對...著迷、對...很狂熱" },
  { id: "s398", word: "special", partOfSpeech: "adj.", meaning: "特別的；專門的" },
  { id: "s399", word: "offer", partOfSpeech: "n.", meaning: "(短期的)折扣、提議" },
  { id: "s400", word: "figure", partOfSpeech: "n.", meaning: "數字；外形；畫像、塑像" },
  { id: "s401", word: "climbing wall", partOfSpeech: "n.", meaning: "攀岩牆" },
  { id: "s402", word: "route", partOfSpeech: "n.", meaning: "路線" },
  { id: "s403", word: "keep away from", partOfSpeech: "ph.", meaning: "遠離、避開" },
  { id: "s404", word: "rock climbing", partOfSpeech: "n.", meaning: "攀岩運動" },
  { id: "s405", word: "alone", partOfSpeech: "adv.", meaning: "單獨地、獨自地" },
  { id: "s406", word: "corner", partOfSpeech: "n.", meaning: "角落、轉角" },
  { id: "s407", word: "textbook", partOfSpeech: "n.", meaning: "教科書" },
  { id: "s408", word: "empty", partOfSpeech: "adj.", meaning: "空的" },
  { id: "s409", word: "as well", partOfSpeech: "ph.", meaning: "也；還有" },
  { id: "s410", word: "smile", partOfSpeech: "v.", meaning: "微笑" },
  { id: "s411", word: "arrive", partOfSpeech: "v.", meaning: "到達、抵達" },
  { id: "s412", word: "subject", partOfSpeech: "n.", meaning: "主題；科目" },
  { id: "s413", word: "already", partOfSpeech: "adv.", meaning: "已經、早已" },
  { id: "s414", word: "find", partOfSpeech: "n.", meaning: "尋找；發現" },
  { id: "s415", word: "be different from", partOfSpeech: "ph.", meaning: "不同於；和...不一樣" },
  { id: "s416", word: "boat trip(s)", partOfSpeech: "n.", meaning: "乘船旅行" },
  { id: "s417", word: "take photos of", partOfSpeech: "ph.", meaning: "拍攝...的照片" },
  { id: "s418", word: "feed", partOfSpeech: "v.", meaning: "餵、養；提供食物" },
  { id: "s419", word: "lamb", partOfSpeech: "n.", meaning: "小羊、羊肉" },
  { id: "s420", word: "notice", partOfSpeech: "n.", meaning: "通知、告示" },
  { id: "s421", word: "watch movies", partOfSpeech: "ph.", meaning: "看電影" },
  { id: "s422", word: "flag", partOfSpeech: "n.", meaning: "旗、幟" },
  { id: "s423", word: "scarf", partOfSpeech: "n.", meaning: "圍巾" },
  { id: "s424", word: "wig", partOfSpeech: "n.", meaning: "假髮" },
  { id: "s425", word: "drum", partOfSpeech: "n.", meaning: "鼓" },
  { id: "s426", word: "half", partOfSpeech: "adj./n.", meaning: "一半的 / 一半" },
  { id: "s427", word: "have a lot of fun + V-ing / N.", partOfSpeech: "ph.", meaning: "玩得很開心" },
  { id: "s428", word: "fan", partOfSpeech: "n.", meaning: "粉絲；電扇、扇子" },
  { id: "s429", word: "quarter", partOfSpeech: "n.", meaning: "四分之一" },
  { id: "s430", word: "T-shirt / hat", partOfSpeech: "n.", meaning: "T恤衫 / 帽子" },
  { id: "s431", word: "climb", partOfSpeech: "v.", meaning: "爬、攀登" },
  { id: "s432", word: "change", partOfSpeech: "v.", meaning: "交換；改變" },
  { id: "s433", word: "take pictures", partOfSpeech: "ph.", meaning: "拍照" },
  { id: "s434", word: "interesting", partOfSpeech: "adj.", meaning: "有趣的" },
  { id: "s435", word: "fly", partOfSpeech: "n.", meaning: "蒼蠅" },
  { id: "s436", word: "hide", partOfSpeech: "v.", meaning: "躲藏；遮掩" },
  { id: "s437", word: "boring", partOfSpeech: "adj.", meaning: "無聊的" },
  { id: "s438", word: "lizard", partOfSpeech: "n.", meaning: "蜥蜴" },
  { id: "s439", word: "listen to...", partOfSpeech: "ph.", meaning: "聽(音樂、收音機、某人說話等)" },
  { id: "s440", word: "get up", partOfSpeech: "ph.", meaning: "起床、起立" },
  { id: "s441", word: "have a shower (Br)", partOfSpeech: "ph.", meaning: "淋浴／洗澡" },
  { id: "s442", word: "have breakfast / lunch / dinner", partOfSpeech: "ph.", meaning: "吃早／午／晚餐" },
  { id: "s443", word: "go to work", partOfSpeech: "ph.", meaning: "上班" },
  { id: "s444", word: "leave work", partOfSpeech: "ph.", meaning: "下班" },
  { id: "s445", word: "a number of", partOfSpeech: "ph.", meaning: "一些、許多" },
  { id: "s446", word: "leave school", partOfSpeech: "ph.", meaning: "放學；畢業" },
  { id: "s447", word: "go to school", partOfSpeech: "ph.", meaning: "上學" },
  { id: "s448", word: "go to bed", partOfSpeech: "ph.", meaning: "睡覺" },
  { id: "s449", word: "machine", partOfSpeech: "n.", meaning: "機器" },
  { id: "s450", word: "at work", partOfSpeech: "ph.", meaning: "工作中" },
  { id: "s451", word: "cheer on", partOfSpeech: "ph.", meaning: "為...加油；給...打氣" },
  { id: "s452", word: "traffic jam", partOfSpeech: "n.", meaning: "塞車" },
  { id: "s453", word: "build", partOfSpeech: "v.", meaning: "建造；建立" },
  { id: "s454", word: "call", partOfSpeech: "v.", meaning: "給...取名；打電話；呼喊；把...看作" },
  { id: "s455", word: "phone", partOfSpeech: "n./v.", meaning: "(n.) 電話；(v.) 致電" },
  { id: "s456", word: "past", partOfSpeech: "adj./n.", meaning: "(adj.) 過去的；(n.) 過去" },
  { id: "s457", word: "shout at", partOfSpeech: "ph.", meaning: "對...大聲喊叫" },
  { id: "s458", word: "Internet", partOfSpeech: "n.", meaning: "網際網路" },
  { id: "s459", word: "message", partOfSpeech: "n.", meaning: "訊息、消息" },
  { id: "s460", word: "closely", partOfSpeech: "adv.", meaning: "密切地；仔細地" },
  { id: "s461", word: "camera", partOfSpeech: "n.", meaning: "照相機" },
  { id: "s462", word: "travel", partOfSpeech: "v.", meaning: "旅行、旅遊" },
  { id: "s463", word: "go to the dentist", partOfSpeech: "ph.", meaning: "看牙醫" },
  { id: "s464", word: "shop", partOfSpeech: "v.", meaning: "買、購買" },
  { id: "s465", word: "few", partOfSpeech: "adj.", meaning: "很少的、一點點" },
  { id: "s466", word: "tell", partOfSpeech: "v.", meaning: "講、述、告訴" },
  { id: "s467", word: "sport(s)", partOfSpeech: "n.", meaning: "體育、運動" },
  { id: "s468", word: "hobby", partOfSpeech: "n.", meaning: "愛好、嗜好" },
  { id: "s469", word: "stay up (late)", partOfSpeech: "ph.", meaning: "熬夜" },
  { id: "s470", word: "photo", partOfSpeech: "n.", meaning: "照片、相片" },
  { id: "s471", word: "popular", partOfSpeech: "adj.", meaning: "受歡迎的、大眾的" },
  { id: "s472", word: "information", partOfSpeech: "n.", meaning: "資料、消息" },
  { id: "s473", word: "chart", partOfSpeech: "n.", meaning: "圖表" },
  { id: "s474", word: "collect", partOfSpeech: "v.", meaning: "收藏、聚集" },
  { id: "s475", word: "It's time to...", partOfSpeech: "ph.", meaning: "是...的時候了" },
  { id: "s476", word: "set up", partOfSpeech: "ph.", meaning: "建立；安排；安裝；準備" },
  { id: "s477", word: "plug", partOfSpeech: "v./n.", meaning: "(v.) 宣傳；堵、塞、插入；(n.) 插頭" },
  { id: "s478", word: "switch", partOfSpeech: "v./n.", meaning: "(v.) 打開/關閉；轉換；(n.) 開關" },
  { id: "s479", word: "happen", partOfSpeech: "v.", meaning: "發生" },
  { id: "s480", word: "everyone", partOfSpeech: "pron.", meaning: "每個人" },
  { id: "s481", word: "head for + a place", partOfSpeech: "ph.", meaning: "朝...走去" },
  { id: "s482", word: "movie theater", partOfSpeech: "n.", meaning: "電影院" },
  { id: "s483", word: "concert", partOfSpeech: "n.", meaning: "音樂會" },
  { id: "s484", word: "playground", partOfSpeech: "n.", meaning: "操場；遊戲場" },
  { id: "s485", word: "wonderful", partOfSpeech: "adj.", meaning: "令人驚嘆的；絕妙的；極好的" },
  { id: "s486", word: "gym", partOfSpeech: "n.", meaning: "體育館；健身房" },
  { id: "s487", word: "leaf / leaves", partOfSpeech: "n.", meaning: "葉片；樹葉" },
  { id: "s488", word: "draw", partOfSpeech: "v.", meaning: "繪畫" },
  { id: "s489", word: "picture", partOfSpeech: "n.", meaning: "圖畫、照片" },
  { id: "s490", word: "music", partOfSpeech: "n.", meaning: "音樂" },
  { id: "s491", word: "listen", partOfSpeech: "v.", meaning: "聽" },
  { id: "s492", word: "fantastic", partOfSpeech: "adj.", meaning: "極好的；幻想的；難以置信的" },
  { id: "s493", word: "different", partOfSpeech: "adj.", meaning: "不一樣的；另類的" },
  { id: "s494", word: "adult", partOfSpeech: "n.", meaning: "成人" },
  { id: "s495", word: "difficult", partOfSpeech: "adj.", meaning: "困難的；艱難地" },
  { id: "s496", word: "touch", partOfSpeech: "v.", meaning: "碰、觸、摸" },
  { id: "s497", word: "wet", partOfSpeech: "adj.", meaning: "濕的；潮濕的" },
  { id: "s498", word: "dim", partOfSpeech: "adj.", meaning: "暗淡的、昏暗的" },
  { id: "s499", word: "bright", partOfSpeech: "adj.", meaning: "光明的、明亮的；鮮艷的" },
  { id: "s500", word: "hundreds of", partOfSpeech: "ph.", meaning: "許多的、成百上千" },
  { id: "s501", word: "solar power", partOfSpeech: "n.", meaning: "太陽能" },
  { id: "s502", word: "energy", partOfSpeech: "n.", meaning: "精力；能量" },
  { id: "s503", word: "amazing", partOfSpeech: "adj.", meaning: "驚人的；令人驚喜的" },
  { id: "s504", word: "advert(s)", partOfSpeech: "n.", meaning: "廣告、宣傳" },
  { id: "s505", word: "as busy as a bee", partOfSpeech: "ph.", meaning: "忙得不停" },
  { id: "s506", word: "mint", partOfSpeech: "n.", meaning: "薄荷" },
  { id: "s507", word: "kit", partOfSpeech: "n.", meaning: "工具箱、成套工具" },
  { id: "s508", word: "bulb", partOfSpeech: "n.", meaning: "燈泡" },
  { id: "s509", word: "battery", partOfSpeech: "n.", meaning: "電池" },
  { id: "s510", word: "wire", partOfSpeech: "n.", meaning: "電線；金屬絲" },
  { id: "s511", word: "as sick as a dog", partOfSpeech: "ph.", meaning: "非常虛弱；病得很重" },
  { id: "s512", word: "motor", partOfSpeech: "n.", meaning: "發動機；馬達" },
  { id: "s513", word: "circuit", partOfSpeech: "n.", meaning: "電路、回路" },
  { id: "s514", word: "electricity", partOfSpeech: "n.", meaning: "電、電能" },
  { id: "s515", word: "dangerous", partOfSpeech: "adj.", meaning: "危險的、有威脅的" },
  { id: "s516", word: "on or off", partOfSpeech: "adj.", meaning: "開啟的或是關閉的" },
  { id: "s517", word: "as hungry as a bear", partOfSpeech: "ph.", meaning: "非常餓" },
  { id: "s518", word: "princess", partOfSpeech: "n.", meaning: "公主、王妃" },
  { id: "s519", word: "prince", partOfSpeech: "n.", meaning: "王子、親王" },
  { id: "s520", word: "carnival", partOfSpeech: "n.", meaning: "嘉年華" },
  { id: "s521", word: "brilliant", partOfSpeech: "adj.", meaning: "有才華的、聰穎的、傑出的" },
  { id: "s522", word: "laugh", partOfSpeech: "v.", meaning: "大笑" },
  { id: "s523", word: "look forward to V-ing / N.", partOfSpeech: "ph.", meaning: "期待、盼望" },
  { id: "s524", word: "glad", partOfSpeech: "adj.", meaning: "高興的" },
  { id: "s525", word: "accident", partOfSpeech: "n.", meaning: "意外、事故" },
  { id: "s526", word: "pair", partOfSpeech: "n.", meaning: "一雙、一對" },
  { id: "s527", word: "practice", partOfSpeech: "v.", meaning: "練習" },
  { id: "s528", word: "unplanned", partOfSpeech: "adj.", meaning: "沒計畫的、意料之外的" },
  { id: "s529", word: "ride the subway to...", partOfSpeech: "ph.", meaning: "搭地鐵去..." },
  { id: "s530", word: "knight", partOfSpeech: "n.", meaning: "騎士" },
  { id: "s531", word: "juggler", partOfSpeech: "n.", meaning: "雜耍演員" },
  { id: "s532", word: "pirate", partOfSpeech: "n.", meaning: "海盜" },
  { id: "s533", word: "dancer", partOfSpeech: "n.", meaning: "舞者" },
  { id: "s534", word: "acrobat", partOfSpeech: "n.", meaning: "雜技演員" },
  { id: "s535", word: "laugh at", partOfSpeech: "ph.", meaning: "笑；取笑" },
  { id: "s536", word: "clown", partOfSpeech: "n.", meaning: "小丑" },
  { id: "s537", word: "king", partOfSpeech: "n.", meaning: "國王" },
  { id: "s538", word: "magician", partOfSpeech: "n.", meaning: "魔術師；魔法師" },
  { id: "s539", word: "queen", partOfSpeech: "n.", meaning: "女王；王后" },
  { id: "s540", word: "lady", partOfSpeech: "n.", meaning: "女士" },
  { id: "s541", word: "practice V-ing / N.", partOfSpeech: "ph.", meaning: "練習" },
  { id: "s542", word: "action", partOfSpeech: "n.", meaning: "行動、行為" },
  { id: "s543", word: "on purpose", partOfSpeech: "ph.", meaning: "故意地" },
  { id: "s544", word: "e-mail", partOfSpeech: "n.", meaning: "電子郵件" },
  { id: "s545", word: "get stuck", partOfSpeech: "ph.", meaning: "卡住、困住" },
  { id: "s546", word: "break", partOfSpeech: "v.", meaning: "打破、破裂、毀壞、破壞" },
  { id: "s547", word: "be about to V.", partOfSpeech: "ph.", meaning: "快要、即將要" },
  { id: "s548", word: "hospital", partOfSpeech: "n.", meaning: "醫院" },
  { id: "s549", word: "score", partOfSpeech: "v.", meaning: "得分" },
  { id: "s550", word: "movie theater", partOfSpeech: "n.", meaning: "電影院" },
  { id: "s551", word: "on a vacation", partOfSpeech: "ph.", meaning: "休假中、度假中" },
  { id: "s552", word: "station", partOfSpeech: "n.", meaning: "車站" },
  { id: "s553", word: "boring", partOfSpeech: "adj.", meaning: "無聊的" },
  { id: "s554", word: "interesting", partOfSpeech: "adj.", meaning: "有趣的" },
  { id: "s555", word: "empty", partOfSpeech: "adj.", meaning: "空的；無意義的" },
  { id: "s556", word: "exciting", partOfSpeech: "adj.", meaning: "令人興奮的、使人激動的" },
  { id: "s557", word: "nurse", partOfSpeech: "n.", meaning: "護士、護理人員" },
  { id: "s558", word: "camera", partOfSpeech: "n.", meaning: "照相機" },
  { id: "s559", word: "dangerous", partOfSpeech: "adj.", meaning: "危險的、有威脅的" },
  { id: "s560", word: "laptop", partOfSpeech: "n.", meaning: "筆記型電腦" },
  { id: "s561", word: "juggle", partOfSpeech: "v.", meaning: "玩雜耍" },
  { id: "s562", word: "costume", partOfSpeech: "n.", meaning: "服裝、戲服" },
  { id: "s563", word: "do trick", partOfSpeech: "ph.", meaning: "變戲法、做把戲" },
  { id: "s564", word: "lorry (Br.)", partOfSpeech: "n.", meaning: "卡車、貨車" },
  { id: "s565", word: "go out", partOfSpeech: "ph.", meaning: "熄滅；外出去玩" },
  { id: "s566", word: "climb", partOfSpeech: "v.", meaning: "爬、攀登；爬升" },
  { id: "s567", word: "rope", partOfSpeech: "n.", meaning: "繩索" },
  { id: "s568", word: "trapeze", partOfSpeech: "n.", meaning: "高空鞦韆" },
  { id: "s569", word: "trampoline", partOfSpeech: "n.", meaning: "彈跳墊、蹦床" },
  { id: "s570", word: "football match", partOfSpeech: "n.", meaning: "足球比賽" },
  { id: "s571", word: "water the plants", partOfSpeech: "ph.", meaning: "給植物澆水" },
  { id: "s572", word: "play against", partOfSpeech: "ph.", meaning: "與...比賽；對抗" },
  { id: "s573", word: "against", partOfSpeech: "prep.", meaning: "反對、與...相反；緊靠著" },
  { id: "s574", word: "circus", partOfSpeech: "n.", meaning: "馬戲團" },
  { id: "s575", word: "station", partOfSpeech: "n.", meaning: "車站；電台；站、局" },
  { id: "s576", word: "subway", partOfSpeech: "n.", meaning: "地鐵" },
  { id: "s577", word: "take (some) medicine", partOfSpeech: "ph.", meaning: "服藥" },
  { id: "s578", word: "seat", partOfSpeech: "n.", meaning: "座位" },
  { id: "s579", word: "hate", partOfSpeech: "v.", meaning: "討厭、厭惡" },
  { id: "s580", word: "suddenly", partOfSpeech: "adv.", meaning: "突然、驟然" },
  { id: "s581", word: "plant", partOfSpeech: "n.", meaning: "植物" },
  { id: "s582", word: "medicine", partOfSpeech: "n.", meaning: "藥物" },
  { id: "s583", word: "pick up", partOfSpeech: "ph.", meaning: "接送；撿起；順道購買" },
  { id: "s584", word: "neck", partOfSpeech: "n.", meaning: "脖子、頸" },
  { id: "s585", word: "hip", partOfSpeech: "n.", meaning: "臀部" },
  { id: "s586", word: "shoulder", partOfSpeech: "n.", meaning: "肩膀" },
  { id: "s587", word: "elbow", partOfSpeech: "n.", meaning: "手肘" },
  { id: "s588", word: "knee", partOfSpeech: "n.", meaning: "膝蓋" },
  { id: "s589", word: "have an idea to V.", partOfSpeech: "ph.", meaning: "想出一個辦法；有一個主意" },
  { id: "s590", word: "head", partOfSpeech: "n.", meaning: "頭部" },
  { id: "s591", word: "hand", partOfSpeech: "n.", meaning: "手" },
  { id: "s592", word: "foot", partOfSpeech: "n.", meaning: "腳、足" },
  { id: "s593", word: "oval", partOfSpeech: "n. adj.", meaning: "橢圓形、橢圓形的" },
  { id: "s594", word: "overlap", partOfSpeech: "v.", meaning: "重疊" },
  { id: "s595", word: "go camping", partOfSpeech: "ph.", meaning: "去露營" },
  { id: "s614", word: "wood", partOfSpeech: "n.", meaning: "木頭、木材" },
  { id: "s615", word: "in the woods", partOfSpeech: "ph.", meaning: "在森林裡面" },
  { id: "s616", word: "touch", partOfSpeech: "v.", meaning: "觸摸、碰" },
  { id: "s617", word: "try", partOfSpeech: "v.", meaning: "嘗試、努力" },
  { id: "s618", word: "hike", partOfSpeech: "v.", meaning: "健行" },
  { id: "s619", word: "put out", partOfSpeech: "ph.", meaning: "撲滅、熄滅(1)；給...添麻煩(2)；出版、生產(3)；拿出(4)" },
  { id: "s620", word: "at camp", partOfSpeech: "ph.", meaning: "在露營地" },
  { id: "s621", word: "cover", partOfSpeech: "v.", meaning: "覆蓋、遮蔽" },
  { id: "s622", word: "exciting", partOfSpeech: "adj.", meaning: "令人興奮的" },
  { id: "s623", word: "think of", partOfSpeech: "ph.", meaning: "想出、發明；覺得、認為" },
  { id: "s624", word: "plan", partOfSpeech: "v.", meaning: "計劃、安排" },
  { id: "s625", word: "be foolish of", partOfSpeech: "ph.", meaning: "做...是愚蠢的" },
  { id: "s626", word: "canoe", partOfSpeech: "v.", meaning: "划獨木舟" },
  { id: "s627", word: "grill", partOfSpeech: "v.", meaning: "燒烤" },
  { id: "s628", word: "fish", partOfSpeech: "v.", meaning: "釣魚、捕魚(魚)；翻找、搜尋" },
  { id: "s629", word: "watch birds", partOfSpeech: "ph.", meaning: "賞鳥" },
  { id: "s630", word: "ski", partOfSpeech: "n., v.", meaning: "(n.) 滑雪板 (v.) 滑雪" },
  { id: "s631", word: "take (good) care of", partOfSpeech: "ph.", meaning: "好好照顧" },
  { id: "s632", word: "snowboard", partOfSpeech: "v.", meaning: "單板滑雪" },
  { id: "s633", word: "ice-skate", partOfSpeech: "v.", meaning: "溜冰" },
  { id: "s634", word: "in-line skate", partOfSpeech: "n., v.", meaning: "(n.) 直排輪鞋 (v.) 溜直排輪" },
  { id: "s635", word: "skateboard", partOfSpeech: "n., v.", meaning: "(n.) 滑板 (v.) 滑滑板" },
  { id: "s636", word: "surf", partOfSpeech: "v.", meaning: "衝浪；上網" },
  { id: "s637", word: "be happy with", partOfSpeech: "ph.", meaning: "對...感到滿意、高興" },
  { id: "s638", word: "helmet", partOfSpeech: "n.", meaning: "安全帽" },
  { id: "s639", word: "sunscreen", partOfSpeech: "n.", meaning: "防曬乳" },
  { id: "s640", word: "life jacket", partOfSpeech: "n.", meaning: "救生衣" },
  { id: "s641", word: "fasten your seatbelt", partOfSpeech: "ph.", meaning: "繫上安全帶" },
  { id: "s642", word: "stone", partOfSpeech: "n.", meaning: "石頭、石塊" },
  { id: "s643", word: "invite sb. to V.", partOfSpeech: "ph.", meaning: "邀請某人做..." },
  { id: "s644", word: "weather report", partOfSpeech: "n.", meaning: "天氣預報" },
  { id: "s645", word: "tomorrow", partOfSpeech: "n.", meaning: "明天" },
  { id: "s646", word: "remember", partOfSpeech: "v.", meaning: "記得、想起" },
  { id: "s647", word: "snowy", partOfSpeech: "adj.", meaning: "下雪的" },
  { id: "s648", word: "around", partOfSpeech: "adv., prep.", meaning: "周圍；圍繞；在...附近" },
  { id: "s649", word: "run into", partOfSpeech: "ph.", meaning: "偶然遇見(1)；遭遇(困難)(2)；碰撞(3)" },
  { id: "s650", word: "hippopotamus", partOfSpeech: "n.", meaning: "河馬" },
  { id: "s651", word: "gorilla", partOfSpeech: "n.", meaning: "大猩猩" },
  { id: "s652", word: "panda", partOfSpeech: "n.", meaning: "貓熊" },
  { id: "s653", word: "caterpillar", partOfSpeech: "n.", meaning: "毛毛蟲" },
  { id: "s654", word: "eel", partOfSpeech: "n.", meaning: "鰻魚" },
  { id: "s655", word: "be about to V.", partOfSpeech: "ph.", meaning: "快要、即將、將會" },
  { id: "s656", word: "seal", partOfSpeech: "n.", meaning: "海豹" },
  { id: "s657", word: "dolphin", partOfSpeech: "n.", meaning: "海豚" },
  { id: "s658", word: "squid", partOfSpeech: "n.", meaning: "魷魚" },
  { id: "s659", word: "beetle", partOfSpeech: "n.", meaning: "甲蟲" },
  { id: "s660", word: "crab", partOfSpeech: "n.", meaning: "螃蟹" },
  { id: "s661", word: "be surprised to V.", partOfSpeech: "ph.", meaning: "對(做某事)感到驚訝" },
  { id: "s662", word: "octopus", partOfSpeech: "n.", meaning: "章魚" },
  { id: "s663", word: "length", partOfSpeech: "n.", meaning: "長度" },
  { id: "s664", word: "weight", partOfSpeech: "n.", meaning: "重量、體重" },
  { id: "s665", word: "blond", partOfSpeech: "adj.", meaning: "(毛髮)金黃色的" },
  { id: "s666", word: "beard", partOfSpeech: "n.", meaning: "(下巴上的)鬍鬚" },
  { id: "s667", word: "find out", partOfSpeech: "ph.", meaning: "發現、得知、找出、查明" },
  { id: "s668", word: "foolish", partOfSpeech: "adj.", meaning: "愚蠢的、傻的" },
  { id: "s669", word: "fence", partOfSpeech: "n.", meaning: "柵欄、籬笆" },
  { id: "s670", word: "taste", partOfSpeech: "v.", meaning: "品嚐" },
  { id: "s671", word: "seem", partOfSpeech: "v.", meaning: "似乎、看起來像" },
  { id: "s672", word: "stay home", partOfSpeech: "ph.", meaning: "待在家" },
  { id: "s673", word: "get rid of", partOfSpeech: "ph.", meaning: "擺脫、除去、處理、丟棄" },
  { id: "s674", word: "ocean", partOfSpeech: "n.", meaning: "海洋" },
  { id: "s675", word: "invite", partOfSpeech: "v.", meaning: "邀請、請；徵求" },
  { id: "s676", word: "first", partOfSpeech: "det.", meaning: "第一、首先、最初、首要" },
  { id: "s677", word: "problem", partOfSpeech: "n.", meaning: "問題、困難" },
  { id: "s678", word: "land", partOfSpeech: "v.", meaning: "著陸、降落" },
  { id: "s679", word: "look forward to V-ing / N.", partOfSpeech: "ph.", meaning: "期待、盼望" },
  { id: "s680", word: "famous", partOfSpeech: "adj.", meaning: "有名氣的、著名的" },
  { id: "s681", word: "afraid", partOfSpeech: "adj.", meaning: "害怕的；擔憂的" },
  { id: "s682", word: "island", partOfSpeech: "n.", meaning: "島嶼" },
  { id: "s683", word: "be able to", partOfSpeech: "ph.", meaning: "能夠、有...能力" },
  { id: "s684", word: "sports star", partOfSpeech: "n.", meaning: "運動明星" },
  { id: "s685", word: "ride the subway to...", partOfSpeech: "ph.", meaning: "搭地鐵去..." },
  { id: "s686", word: "shoulder-length", partOfSpeech: "adj.", meaning: "齊肩的、披肩的" },
  { id: "s687", word: "straight", partOfSpeech: "adj.", meaning: "直的" },
  { id: "s688", word: "curly", partOfSpeech: "adj.", meaning: "捲曲的" },
  { id: "s689", word: "wavy", partOfSpeech: "adj.", meaning: "波浪狀的" },
  { id: "s690", word: "necklace", partOfSpeech: "n.", meaning: "項鍊" },
  { id: "s691", word: "laugh at", partOfSpeech: "ph.", meaning: "笑、取笑" },
  { id: "s692", word: "earrings", partOfSpeech: "n.", meaning: "耳環" },
  { id: "s693", word: "sunglasses", partOfSpeech: "n.", meaning: "太陽眼鏡、墨鏡" },
  { id: "s694", word: "stick", partOfSpeech: "n.", meaning: "枝條；木棍" },
  { id: "s695", word: "grass", partOfSpeech: "n.", meaning: "草" },
  { id: "s696", word: "sand", partOfSpeech: "n.", meaning: "沙子" },
  { id: "s697", word: "practice V-ing / N.", partOfSpeech: "ph.", meaning: "練習" },
  { id: "s698", word: "golf", partOfSpeech: "n.", meaning: "高爾夫球" },
  { id: "s699", word: "table tennis", partOfSpeech: "n.", meaning: "桌球" },
  { id: "s700", word: "practice the piano", partOfSpeech: "ph.", meaning: "練習鋼琴" },
  { id: "s701", word: "use the computer", partOfSpeech: "ph.", meaning: "使用電腦" },
  { id: "s702", word: "talk on the phone", partOfSpeech: "ph.", meaning: "講電話" },
  { id: "s703", word: "be about to V.", partOfSpeech: "ph.", meaning: "快要、即將、將會" },
  { id: "s704", word: "help my parents", partOfSpeech: "ph.", meaning: "幫忙我的父母" },
  { id: "s705", word: "visit my friend", partOfSpeech: "ph.", meaning: "拜訪我的朋友" },
  { id: "s706", word: "work on a project", partOfSpeech: "ph.", meaning: "進行一個專案" },
  { id: "s707", word: "clay", partOfSpeech: "n.", meaning: "黏土" },
  { id: "s708", word: "glass", partOfSpeech: "n.", meaning: "玻璃(製品、杯子)" },
  { id: "s709", word: "go out", partOfSpeech: "ph.", meaning: "外出、出去玩" },
  { id: "s710", word: "metal", partOfSpeech: "n.", meaning: "金屬；合金" },
  { id: "s711", word: "study", partOfSpeech: "v.", meaning: "學習、研讀" },
  { id: "s712", word: "cage", partOfSpeech: "n.", meaning: "籠子" },
  { id: "s713", word: "wall", partOfSpeech: "n.", meaning: "牆、壁" },
  { id: "s714", word: "pull", partOfSpeech: "v.", meaning: "拉、拖、抽出" },
  { id: "s715", word: "water the plants", partOfSpeech: "ph.", meaning: "給植物澆水" },
  { id: "s716", word: "surprised", partOfSpeech: "adj.", meaning: "驚訝的、意料之外的" },
  { id: "s717", word: "smart", partOfSpeech: "adj.", meaning: "聰明的" },
  { id: "s718", word: "useful", partOfSpeech: "adj.", meaning: "有用的、有效的" },
  { id: "s719", word: "delicious", partOfSpeech: "adj.", meaning: "美味的" },
  { id: "s720", word: "toward", partOfSpeech: "prep.", meaning: "朝向；接近" },
  { id: "s721", word: "take (some) medicine", partOfSpeech: "ph.", meaning: "服藥" },
  { id: "s722", word: "noodles", partOfSpeech: "n.", meaning: "麵條" },
  { id: "s723", word: "curry", partOfSpeech: "n.", meaning: "咖哩" },
  { id: "s724", word: "sushi", partOfSpeech: "n.", meaning: "壽司" },
  { id: "s725", word: "lemonade", partOfSpeech: "n.", meaning: "檸檬水" },
  { id: "s726", word: "grape juice", partOfSpeech: "n.", meaning: "葡萄汁" },
  { id: "s727", word: "dress up", partOfSpeech: "ph.", meaning: "盛裝打扮" },
  { id: "s728", word: "go bowling", partOfSpeech: "ph.", meaning: "打保齡球" },
  { id: "s729", word: "take a picture", partOfSpeech: "ph.", meaning: "拍照片" },
  { id: "s730", word: "parade", partOfSpeech: "n.", meaning: "遊行" },
  { id: "s731", word: "haircut", partOfSpeech: "n.", meaning: "理髮；髮型" },
  { id: "s732", word: "buy clothes", partOfSpeech: "ph.", meaning: "買衣服" },
  { id: "s733", word: "check out", partOfSpeech: "ph.", meaning: "查看、檢查(1)；結帳(2)；辦理退房手續(3)" },
  { id: "s734", word: "ancient", partOfSpeech: "adj.", meaning: "古代的；古老的" },
  { id: "s735", word: "activity", partOfSpeech: "n.", meaning: "活動；行動" },
  { id: "s736", word: "answer", partOfSpeech: "n., v.", meaning: "(n.) 回答；作答；答案 (v.) 回答；作答；應門；接電話" },
  { id: "s737", word: "borrow", partOfSpeech: "v.", meaning: "借" },
  { id: "s738", word: "odd", partOfSpeech: "adj.", meaning: "奇怪的、異常的" },
  { id: "s739", word: "stand", partOfSpeech: "n.", meaning: "攤位、展臺" },
  { id: "s740", word: "helpful", partOfSpeech: "adj.", meaning: "有幫助的" },
  { id: "s741", word: "feather", partOfSpeech: "n.", meaning: "羽毛" },
  { id: "s742", word: "tail", partOfSpeech: "n.", meaning: "尾巴" },
  { id: "s743", word: "claw", partOfSpeech: "n.", meaning: "爪；螯" },
  { id: "s744", word: "wing", partOfSpeech: "n.", meaning: "翅膀；機翼" },
  { id: "s745", word: "thirsty", partOfSpeech: "adj.", meaning: "口渴的" },
  { id: "s746", word: "collect", partOfSpeech: "v.", meaning: "收藏、收集；聚集；集中" },
  { id: "s747", word: "Halloween", partOfSpeech: "n.", meaning: "萬聖節前夕" },
  { id: "s748", word: "holiday", partOfSpeech: "n.", meaning: "假期、假日；節日" },
  { id: "s749", word: "costume", partOfSpeech: "n.", meaning: "服裝" },
  { id: "s750", word: "stick to sth.", partOfSpeech: "ph.", meaning: "堅持；遵守、信守" },
  { id: "s751", word: "fight", partOfSpeech: "v., n.", meaning: "(v.) 打鬥、打架；努力擊敗(爭取) (n.) 爭吵；打架；鬥爭" },
  { id: "s752", word: "appearance", partOfSpeech: "n.", meaning: "外表、外觀；露面" },
  { id: "s753", word: "accessory", partOfSpeech: "n.", meaning: "附件、配件；裝飾品" },
  { id: "s754", word: "sing songs", partOfSpeech: "ph.", meaning: "唱歌" },
  { id: "s755", word: "make movies", partOfSpeech: "ph.", meaning: "拍電影" },
  { id: "s756", word: "write stories", partOfSpeech: "ph.", meaning: "寫故事" },
  { id: "s757", word: "paint pictures", partOfSpeech: "ph.", meaning: "畫畫" },
  { id: "s758", word: "design", partOfSpeech: "v.", meaning: "設計" },
  { id: "s759", word: "clothes", partOfSpeech: "n.", meaning: "衣服、衣物" },
  { id: "s760", word: "model", partOfSpeech: "n.", meaning: "模型；模樣" },
  { id: "s761", word: "free", partOfSpeech: "adj.", meaning: "自由的" },
  { id: "s762", word: "bake cookies", partOfSpeech: "ph.", meaning: "烤餅乾" },
  { id: "s763", word: "carry", partOfSpeech: "v.", meaning: "背；扛；搬；攜帶" },
  { id: "s764", word: "jewelry", partOfSpeech: "n.", meaning: "珠寶、首飾" },
  { id: "s765", word: "make", partOfSpeech: "v.", meaning: "做；製造；製作；拍攝" },
  { id: "s766", word: "knit", partOfSpeech: "v.", meaning: "編織" },
  { id: "s767", word: "neighbor", partOfSpeech: "n.", meaning: "鄰居" },
  { id: "s768", word: "garbage", partOfSpeech: "n.", meaning: "垃圾" },
  { id: "s769", word: "sweep", partOfSpeech: "v.", meaning: "清掃" },
  { id: "s770", word: "painting", partOfSpeech: "n.", meaning: "繪畫、油畫" },
  { id: "s771", word: "photograph", partOfSpeech: "n.", meaning: "照片、相片" },
  { id: "s772", word: "mosaic", partOfSpeech: "n.", meaning: "馬賽克；鑲嵌圖案" },
  { id: "s773", word: "sculpture", partOfSpeech: "n.", meaning: "雕塑、雕刻" },
  { id: "s774", word: "dress up", partOfSpeech: "ph.", meaning: "盛裝打扮" },
  { id: "s775", word: "check out", partOfSpeech: "ph.", meaning: "查看、檢查；結帳；辦理退房手續" },
  { id: "s776", word: "It's time to...", partOfSpeech: "ph.", meaning: "是時候...了" },
  { id: "s777", word: "actor", partOfSpeech: "n.", meaning: "男演員" },
  { id: "s778", word: "artist", partOfSpeech: "n.", meaning: "藝術家" },
  { id: "s779", word: "musician", partOfSpeech: "n.", meaning: "音樂家" },
  { id: "s780", word: "game designer", partOfSpeech: "n.", meaning: "遊戲設計師" },
  { id: "s781", word: "journalist", partOfSpeech: "n.", meaning: "新聞記者" },
  { id: "s782", word: "scientist", partOfSpeech: "n.", meaning: "科學家" },
  { id: "s783", word: "grow", partOfSpeech: "v.", meaning: "增多；增長；成長；長大" },
  { id: "s784", word: "career", partOfSpeech: "n.", meaning: "職業；事業；生涯" },
  { id: "s785", word: "go to space", partOfSpeech: "ph.", meaning: "去太空" },
  { id: "s786", word: "fly a helicopter", partOfSpeech: "ph.", meaning: "駕駛直升機" },
  { id: "s787", word: "work with animals", partOfSpeech: "ph.", meaning: "從事與動物相關的工作" },
  { id: "s788", word: "drive a race car", partOfSpeech: "ph.", meaning: "駕駛賽車" },
  { id: "s789", word: "explore", partOfSpeech: "v.", meaning: "探測；探索" },
  { id: "s790", word: "jungle", partOfSpeech: "n.", meaning: "熱帶叢林" },
  { id: "s791", word: "travel the world", partOfSpeech: "ph.", meaning: "環遊世界" },
  { id: "s792", word: "space shuttle", partOfSpeech: "n.", meaning: "太空梭" },
  { id: "s793", word: "space station", partOfSpeech: "n.", meaning: "太空站" },
  { id: "s794", word: "space suit", partOfSpeech: "n.", meaning: "太空衣" },
  { id: "s795", word: "Earth", partOfSpeech: "n.", meaning: "地球" },
  { id: "s796", word: "astronaut", partOfSpeech: "n.", meaning: "太空人" },
  { id: "s797", word: "cook dinner for", partOfSpeech: "ph.", meaning: "為...準備晚餐" },
  { id: "s798", word: "take out the trash (garbage)", partOfSpeech: "ph.", meaning: "倒垃圾" },
  { id: "s799", word: "sweaty", partOfSpeech: "adj.", meaning: "滿身是汗的" },
  { id: "s800", word: "dry", partOfSpeech: "v./adj.", meaning: "弄乾/乾燥的" },
  { id: "s801", word: "wet", partOfSpeech: "adj.", meaning: "潮濕的" },
  { id: "s802", word: "work", partOfSpeech: "v.", meaning: "有效/成功" },
  { id: "s803", word: "mad", partOfSpeech: "adj.", meaning: "生氣的" },
  { id: "s804", word: "get ready", partOfSpeech: "ph.", meaning: "準備好" },
  { id: "s805", word: "yell", partOfSpeech: "v.", meaning: "吼叫" },
  { id: "s806", word: "summary", partOfSpeech: "n.", meaning: "摘要" },
  { id: "s807", word: "knock", partOfSpeech: "v.", meaning: "敲/打" },
  { id: "s808", word: "wake up", partOfSpeech: "ph.", meaning: "醒來" },
  { id: "s809", word: "sequencing", partOfSpeech: "n.", meaning: "照順序排；排序" },
  { id: "s810", word: "poor", partOfSpeech: "adj.", meaning: "貧窮的" },
  { id: "s811", word: "wealthy", partOfSpeech: "adj.", meaning: "富裕的" },
  { id: "s812", word: "fancy", partOfSpeech: "n.", meaning: "愛好/想像" },
  { id: "s813", word: "these", partOfSpeech: "pron.", meaning: "這些" },
  { id: "s814", word: "credit card", partOfSpeech: "n.", meaning: "信用卡" },
  { id: "s815", word: "pay for", partOfSpeech: "ph.", meaning: "支付…費用" },
  { id: "s816", word: "cause", partOfSpeech: "n.", meaning: "原因" },
  { id: "s817", word: "effect", partOfSpeech: "n.", meaning: "結果" },
  { id: "s818", word: "feel great", partOfSpeech: "ph.", meaning: "覺得很好" },
  { id: "s819", word: "bring", partOfSpeech: "v.", meaning: "帶來" },
  { id: "s820", word: "carry", partOfSpeech: "v.", meaning: "攜帶" },
  { id: "s821", word: "careful", partOfSpeech: "adj.", meaning: "小心的" },
  { id: "s822", word: "different", partOfSpeech: "adj.", meaning: "不同的" },
  { id: "s823", word: "circus", partOfSpeech: "n.", meaning: "馬戲團" },
  { id: "s824", word: "balcony", partOfSpeech: "n.", meaning: "陽臺" },
  { id: "s825", word: "bottle", partOfSpeech: "n.", meaning: "瓶子" },
  { id: "s826", word: "climb", partOfSpeech: "v.", meaning: "爬" },
  { id: "s827", word: "exciting", partOfSpeech: "adj.", meaning: "令人興奮的" },
  { id: "s828", word: "difficult", partOfSpeech: "adj.", meaning: "困難的" },
  { id: "s829", word: "be good at", partOfSpeech: "ph.", meaning: "擅長" },
  { id: "s830", word: "build", partOfSpeech: "v.", meaning: "建造" },
  { id: "s831", word: "forest", partOfSpeech: "n.", meaning: "森林" },
  { id: "s832", word: "cloud", partOfSpeech: "n.", meaning: "雲" },
  { id: "s833", word: "always", partOfSpeech: "adv.", meaning: "總是" },
  { id: "s834", word: "cinema", partOfSpeech: "n.", meaning: "電影院" },
  { id: "s835", word: "dentist", partOfSpeech: "n.", meaning: "牙醫" },
  { id: "s836", word: "because", partOfSpeech: "conj.", meaning: "因為" },
  { id: "s837", word: "market", partOfSpeech: "n.", meaning: "市場" },
  { id: "s838", word: "island", partOfSpeech: "n.", meaning: "島" },
  { id: "s839", word: "curve", partOfSpeech: "n.", meaning: "曲線" },
  { id: "s840", word: "valuable", partOfSpeech: "adj.", meaning: "有價值的" },
  { id: "s841", word: "building", partOfSpeech: "n.", meaning: "建築物" },
  { id: "s842", word: "splash", partOfSpeech: "v.", meaning: "濺起" },
  { id: "s843", word: "surprised", partOfSpeech: "adj.", meaning: "驚訝的" },
  { id: "s844", word: "headache", partOfSpeech: "n.", meaning: "頭痛" },
  { id: "s845", word: "shoulder", partOfSpeech: "n.", meaning: "肩膀" },
  { id: "s846", word: "dolphin", partOfSpeech: "n.", meaning: "海豚" },
  { id: "s847", word: "skip", partOfSpeech: "v.", meaning: "跳繩" },
  { id: "s848", word: "curly", partOfSpeech: "adj.", meaning: "捲曲的" },
  { id: "s849", word: "clown", partOfSpeech: "n.", meaning: "小丑" },
  { id: "s850", word: "ticket", partOfSpeech: "n.", meaning: "票券" },
  { id: "s851", word: "snail", partOfSpeech: "n.", meaning: "蝸牛" },
  { id: "s852", word: "shell", partOfSpeech: "n.", meaning: "殼；外殼" },
  { id: "s853", word: "toothbrush", partOfSpeech: "n.", meaning: "牙刷" },
  { id: "s854", word: "sweater", partOfSpeech: "n.", meaning: "毛衣" },
  { id: "s855", word: "uniform", partOfSpeech: "n.", meaning: "制服" },
  { id: "s856", word: "river", partOfSpeech: "n.", meaning: "河流" },
  { id: "s857", word: "blanket", partOfSpeech: "n.", meaning: "毯子" },
  { id: "s858", word: "balloon", partOfSpeech: "n.", meaning: "氣球" },
  { id: "s859", word: "fish/ go fishing", partOfSpeech: "v.", meaning: "釣魚" },
  { id: "s860", word: "waterski / go waterskiing", partOfSpeech: "v.", meaning: "滑水" },
  { id: "s861", word: "sail/ go sailing", partOfSpeech: "v.", meaning: "航行" },
  { id: "s862", word: "row", partOfSpeech: "v.", meaning: "划船" },
  { id: "s863", word: "rollerblade/ go rollerblading", partOfSpeech: "v.", meaning: "直排輪" },
  { id: "s864", word: "a couple of", partOfSpeech: "ph.", meaning: "成對的…；兩三個…" },
  { id: "s865", word: "minute", partOfSpeech: "n.", meaning: "分鐘" },
  { id: "s866", word: "celebrate", partOfSpeech: "v.", meaning: "慶祝" },
  { id: "s867", word: "knock", partOfSpeech: "v.", meaning: "敲" },
  { id: "s868", word: "invite", partOfSpeech: "v.", meaning: "邀請" },
  { id: "s869", word: "surprise", partOfSpeech: "n.", meaning: "驚喜；驚嚇" },
  { id: "s870", word: "a long time ago", partOfSpeech: "ph.", meaning: "很久以前" },
  { id: "s871", word: "hide and seek", partOfSpeech: "n.", meaning: "捉迷藏" },
  { id: "s872", word: "write an email", partOfSpeech: "v.", meaning: "寫信" },
  { id: "s873", word: "have a rest", partOfSpeech: "v.", meaning: "休息一下" },
  { id: "s874", word: "play tennis", partOfSpeech: "v.", meaning: "打網球" },
  { id: "s875", word: "swim/ go swimming", partOfSpeech: "v.", meaning: "游泳" },
  { id: "s876", word: "a lot of", partOfSpeech: "ph.", meaning: "很多…" },
  { id: "s877", word: "climb/ go climbing", partOfSpeech: "v.", meaning: "攀爬" },
  { id: "s878", word: "football", partOfSpeech: "n.", meaning: "足球" },
  { id: "s879", word: "basketball", partOfSpeech: "n.", meaning: "籃球" },
  { id: "s880", word: "skateboard/ go skateboarding", partOfSpeech: "v.", meaning: "滑板" },
  { id: "s881", word: "several", partOfSpeech: "adj.", meaning: "幾個；數個；一些" },
  { id: "s882", word: "a pair of", partOfSpeech: "ph.", meaning: "一雙…；一副…" },
  { id: "s883", word: "carry", partOfSpeech: "v.", meaning: "攜帶" },
  { id: "s884", word: "snow", partOfSpeech: "n. / v.", meaning: "雪；下雪" },
  { id: "s885", word: "vapour / vapor", partOfSpeech: "n.", meaning: "蒸氣" },
  { id: "s886", word: "sunny", partOfSpeech: "adj.", meaning: "晴朗的" },
  { id: "s887", word: "cloudy", partOfSpeech: "adj.", meaning: "多雲的" },
  { id: "s888", word: "agree with", partOfSpeech: "ph.", meaning: "同意；贊同" },
  { id: "s889", word: "windy", partOfSpeech: "adj.", meaning: "起風的；風大的" },
  { id: "s890", word: "rainy", partOfSpeech: "adj.", meaning: "下雨的；多雨的" },
  { id: "s891", word: "snowy", partOfSpeech: "adj.", meaning: "下雪的；積雪的" },
  { id: "s892", word: "foggy", partOfSpeech: "adj.", meaning: "起霧的" },
  { id: "s893", word: "stormy", partOfSpeech: "adj.", meaning: "暴風雨的" },
  { id: "s894", word: "all over the world", partOfSpeech: "ph.", meaning: "全世界" },
  { id: "s895", word: "degree", partOfSpeech: "n.", meaning: "度；度數" },
  { id: "s896", word: "temperature", partOfSpeech: "n.", meaning: "溫度；體溫" },
  { id: "s897", word: "alarm clock", partOfSpeech: "n.", meaning: "鬧鐘" },
  { id: "s898", word: "chore", partOfSpeech: "n.", meaning: "家務；雜務" },
  { id: "s899", word: "schedule", partOfSpeech: "n.", meaning: "行程；時間表" },
  { id: "s900", word: "all of a sudden", partOfSpeech: "ph.", meaning: "突然間" },
  { id: "s901", word: "rarely", partOfSpeech: "adv.", meaning: "很少；不常見；難得" },
  { id: "s902", word: "practice", partOfSpeech: "n. / v.", meaning: "練習" },
  { id: "s903", word: "astronaut", partOfSpeech: "n.", meaning: "太空人" },
  { id: "s904", word: "artist", partOfSpeech: "n.", meaning: "藝術家；畫家" },
  { id: "s905", word: "scientist", partOfSpeech: "n.", meaning: "科學家" },
  { id: "s906", word: "all the time", partOfSpeech: "ph.", meaning: "總是；一直" },
  { id: "s907", word: "policeman", partOfSpeech: "n.", meaning: "警察" },
  { id: "s908", word: "pilot", partOfSpeech: "n.", meaning: "飛行員；機師" },
  { id: "s909", word: "actor / actress", partOfSpeech: "n.", meaning: "男演員／女演員" },
  { id: "s910", word: "pirate", partOfSpeech: "n.", meaning: "海盜" },
  { id: "s911", word: "footballer", partOfSpeech: "n.", meaning: "足球員" },
  { id: "s912", word: "all the way", partOfSpeech: "ph.", meaning: "一路上；一直；完全" },
  { id: "s913", word: "firefighter", partOfSpeech: "n.", meaning: "消防員" },
  { id: "s914", word: "meanwhile", partOfSpeech: "adv.", meaning: "同時；在此期間" },
  { id: "s915", word: "go for a walk", partOfSpeech: "ph.", meaning: "去散步" },
  { id: "s916", word: "comics", partOfSpeech: "n.", meaning: "漫畫（書）" },
  { id: "s917", word: "art gallery", partOfSpeech: "n.", meaning: "美術館；畫廊" },
  { id: "s918", word: "and so on", partOfSpeech: "ph.", meaning: "等等；諸如此類" },
  { id: "s919", word: "interview", partOfSpeech: "n.", meaning: "訪問；面試" },
  { id: "s920", word: "cartoonist", partOfSpeech: "n.", meaning: "漫畫家" },
  { id: "s921", word: "difficult", partOfSpeech: "adj.", meaning: "困難的" },
  { id: "s922", word: "programme (US=program)", partOfSpeech: "n.", meaning: "節目；計畫／程式" },
  { id: "s923", word: "relax", partOfSpeech: "v.", meaning: "放鬆" },
  { id: "s924", word: "arrive at / in", partOfSpeech: "ph.", meaning: "抵達..." },
  { id: "s925", word: "go cycling", partOfSpeech: "ph.", meaning: "去騎單車" },
  { id: "s926", word: "draw cartoons", partOfSpeech: "v.", meaning: "畫漫畫" },
  { id: "s927", word: "raise", partOfSpeech: "v.", meaning: "募款；募集" },
  { id: "s928", word: "destroy", partOfSpeech: "v.", meaning: "毀壞；破壞" },
  { id: "s929", word: "collect", partOfSpeech: "v.", meaning: "收集；收藏" },
  { id: "s930", word: "as a result", partOfSpeech: "ph.", meaning: "結果" },
  { id: "s931", word: "adventure camp", partOfSpeech: "n.", meaning: "探險營" },
  { id: "s932", word: "climbing wall", partOfSpeech: "n.", meaning: "攀岩牆" },
  { id: "s933", word: "fantastic", partOfSpeech: "adj.", meaning: "極好的；非常棒的" },
  { id: "s934", word: "scary", partOfSpeech: "adj.", meaning: "可怕的；嚇人的" },
  { id: "s935", word: "brilliant", partOfSpeech: "adj.", meaning: "聰明的；傑出的" },
  { id: "s936", word: "after all", partOfSpeech: "ph.", meaning: "畢竟" },
  { id: "s937", word: "comfortable", partOfSpeech: "adj.", meaning: "舒服的" },
  { id: "s938", word: "countryside", partOfSpeech: "n.", meaning: "鄉下；農村" },
  { id: "s939", word: "court", partOfSpeech: "n.", meaning: "球場" },
  { id: "s940", word: "football pitch", partOfSpeech: "n.", meaning: "足球場" },
  { id: "s941", word: "do sports", partOfSpeech: "v.", meaning: "從事運動" },
  { id: "s942", word: "above all (else)", partOfSpeech: "ph.", meaning: "最重要的是" },
  { id: "s943", word: "activity", partOfSpeech: "n.", meaning: "活動" },
  { id: "s944", word: "volleyball", partOfSpeech: "n.", meaning: "排球" },
  { id: "s945", word: "enough", partOfSpeech: "adj.", meaning: "足夠的" },
  { id: "s946", word: "shelf", partOfSpeech: "n.", meaning: "層架；書架" },
  { id: "s947", word: "dentist", partOfSpeech: "n.", meaning: "牙醫" },
  { id: "s948", word: "again and again", partOfSpeech: "ph.", meaning: "反覆地；再三" },
  { id: "s949", word: "trip", partOfSpeech: "n.", meaning: "旅行；遠足" },
  { id: "s950", word: "forget", partOfSpeech: "v.", meaning: "忘記" },
  { id: "s951", word: "buy", partOfSpeech: "v.", meaning: "買" },
  { id: "s952", word: "raindrop", partOfSpeech: "n.", meaning: "雨滴" },
  { id: "s953", word: "shine", partOfSpeech: "v.", meaning: "發光；照耀" },
  { id: "s954", word: "according to", partOfSpeech: "ph.", meaning: "根據；按照" },
  { id: "s955", word: "grid", partOfSpeech: "n.", meaning: "網格" },
  { id: "s956", word: "tower", partOfSpeech: "n.", meaning: "塔；高樓" },
  { id: "s957", word: "building", partOfSpeech: "n.", meaning: "建築物" },
  { id: "s958", word: "palace", partOfSpeech: "n.", meaning: "宮殿；皇宮" },
  { id: "s959", word: "whole", partOfSpeech: "adj.", meaning: "完整的；全部的" },
  { id: "s960", word: "as well as", partOfSpeech: "ph.", meaning: "以及；還有" },
  { id: "s961", word: "top", partOfSpeech: "n.", meaning: "頂點；頂端" },
  { id: "s962", word: "step", partOfSpeech: "n.", meaning: "階梯" },
  { id: "s963", word: "blank", partOfSpeech: "n.", meaning: "空格；空白處" },
  { id: "s964", word: "photo", partOfSpeech: "n.", meaning: "照片；相片" },
  { id: "s965", word: "help out", partOfSpeech: "ph.", meaning: "幫忙；協助" },
  { id: "s966", word: "ask for", partOfSpeech: "ph.", meaning: "請求；要求" },
  { id: "s967", word: "country", partOfSpeech: "n.", meaning: "國家" },
  { id: "s968", word: "build", partOfSpeech: "v.", meaning: "建造；修建" },
  { id: "s969", word: "medicine", partOfSpeech: "n.", meaning: "藥物；藥品" },
  { id: "s970", word: "perform", partOfSpeech: "v.", meaning: "表演；演出" },
  { id: "s971", word: "guess", partOfSpeech: "v.", meaning: "猜測；猜想" },
  { id: "s972", word: "at a time", partOfSpeech: "ph.", meaning: "一次；每次" },
  { id: "s973", word: "trick", partOfSpeech: "n.", meaning: "特技；惡作劇" },
  { id: "s974", word: "audience", partOfSpeech: "n.", meaning: "觀眾" },
  { id: "s975", word: "on stage", partOfSpeech: "adv.", meaning: "在舞台上" },
  { id: "s976", word: "evaporation", partOfSpeech: "n.", meaning: "蒸發" },
  { id: "s977", word: "continue", partOfSpeech: "v.", meaning: "繼續；持續" },
  { id: "s978", word: "at any time", partOfSpeech: "ph.", meaning: "隨時" },
  { id: "s979", word: "Turkey", partOfSpeech: "n.", meaning: "土耳其" },
  { id: "s980", word: "Poland", partOfSpeech: "n.", meaning: "波蘭" },
  { id: "s981", word: "England", partOfSpeech: "n.", meaning: "英格蘭" },
  { id: "s982", word: "France", partOfSpeech: "n.", meaning: "法國" },
  { id: "s983", word: "Italy", partOfSpeech: "n.", meaning: "義大利" },
  { id: "s984", word: "above all", partOfSpeech: "ph.", meaning: "最重要的是" },
  { id: "s985", word: "continue", partOfSpeech: "v.", meaning: "持續；繼續" },
  { id: "s986", word: "planet", partOfSpeech: "n.", meaning: "行星" },
  { id: "s987", word: "high", partOfSpeech: "adj.", meaning: "高的" },
  { id: "s988", word: "research", partOfSpeech: "n.", meaning: "研究；調查" },
  { id: "s989", word: "living things", partOfSpeech: "n.", meaning: "生物" },
  { id: "s990", word: "after all", partOfSpeech: "ph.", meaning: "畢竟；到底" },
  { id: "s991", word: "mountain", partOfSpeech: "n.", meaning: "(高)山" },
  { id: "s992", word: "machine", partOfSpeech: "n.", meaning: "機器；機械" },
  { id: "s993", word: "teacher", partOfSpeech: "n.", meaning: "老師" },
  { id: "s994", word: "dancer", partOfSpeech: "n.", meaning: "舞者；舞蹈家" },
  { id: "s995", word: "doctor", partOfSpeech: "n.", meaning: "醫生；博士" },
  { id: "s996", word: "according to", partOfSpeech: "ph.", meaning: "根據；按照" },
  { id: "s997", word: "Celsius", partOfSpeech: "n.", meaning: "攝氏" },
  { id: "s998", word: "Fahrenheit", partOfSpeech: "n.", meaning: "華氏" },
  { id: "s999", word: "water cycle", partOfSpeech: "n.", meaning: "水循環" },
  { id: "s1000", word: "was built in", partOfSpeech: "ph.", meaning: "建於" },
  { id: "s1001", word: "condensation", partOfSpeech: "n.", meaning: "凝結" },
  { id: "s1002", word: "agree with", partOfSpeech: "ph.", meaning: "同意；贊同" },
  { id: "s1003", word: "at the camp", partOfSpeech: "adv.", meaning: "在營地；在露營地" },
  { id: "s1004", word: "do research", partOfSpeech: "v.", meaning: "做研究（調查）" },
  { id: "s1005", word: "play volleyball", partOfSpeech: "v.", meaning: "打排球" },
  { id: "s1006", word: "play football", partOfSpeech: "v.", meaning: "踢足球" },
  { id: "s1007", word: "play basketball", partOfSpeech: "v.", meaning: "打籃球" },
  { id: "s1008", word: "play hide and seek", partOfSpeech: "v.", meaning: "玩捉迷藏" },
];
