export interface VocabWord {
  id: string;
  word: string;
  partOfSpeech: string;
  meaning: string;
  englishMeaning?: string;
}

// Level 6 — Week 19-20 (2026/6/15 ~ 6/23)
// School: 陽光森林全美語安親學校
export const vocabData: VocabWord[] = [
  { id: "knight_a1b2c", word: "knight", partOfSpeech: "n.", meaning: "騎士" },
  { id: "clown_d3e4f", word: "clown", partOfSpeech: "n.", meaning: "小丑" },
  { id: "princess_g5h6i", word: "princess", partOfSpeech: "n.", meaning: "公主、王妃" },
  { id: "glad_j7k8l", word: "glad", partOfSpeech: "adj.", meaning: "高興的" },
  { id: "juggler_m9n0o", word: "juggler", partOfSpeech: "n.", meaning: "雜耍演員" },
  { id: "king_p1q2r", word: "king", partOfSpeech: "n.", meaning: "國王" },
  { id: "prince_s3t4u", word: "prince", partOfSpeech: "n.", meaning: "王子、親王" },
  { id: "accident_v5w6x", word: "accident", partOfSpeech: "n.", meaning: "意外、事故" },
  { id: "pirate_y7z8a", word: "pirate", partOfSpeech: "n.", meaning: "海盜" },
  { id: "magician_b9c0d", word: "magician", partOfSpeech: "n.", meaning: "魔術師；魔法師" },
  { id: "carnival_e1f2g", word: "carnival", partOfSpeech: "n.", meaning: "嘉年華" },
  { id: "pair_h3i4j", word: "pair", partOfSpeech: "n.", meaning: "一雙、一對" },
  { id: "dancer_k5l6m", word: "dancer", partOfSpeech: "n.", meaning: "舞者" },
  { id: "queen_n7o8p", word: "queen", partOfSpeech: "n.", meaning: "女王；王后" },
  { id: "brilliant_q9r0s", word: "brilliant", partOfSpeech: "adj.", meaning: "有才華的；聰穎的；傑出的" },
  { id: "practice_t1u2v", word: "practice", partOfSpeech: "v.", meaning: "練習" },
  { id: "acrobat_w3x4y", word: "acrobat", partOfSpeech: "n.", meaning: "雜技演員" },
  { id: "lady_z5a6b", word: "lady", partOfSpeech: "n.", meaning: "女士" },
  { id: "laugh_c7d8e", word: "laugh", partOfSpeech: "v.", meaning: "大笑" },
  { id: "unplanned_f9g0h", word: "unplanned", partOfSpeech: "adj.", meaning: "沒有計劃的；意料之外的" },
  { id: "action_i1j2k", word: "action", partOfSpeech: "n.", meaning: "行動、行為" },
  { id: "hospital_l3m4n", word: "hospital", partOfSpeech: "n.", meaning: "醫院" },
  { id: "score_o5p6q", word: "score", partOfSpeech: "v.", meaning: "得分" },
  { id: "movietheater_r7s8t", word: "movie theater", partOfSpeech: "n.", meaning: "電影院" },
  { id: "onpurpose_u9v0w", word: "on purpose", partOfSpeech: "ph.", meaning: "故意地" },
  { id: "onavacation_x1y2z", word: "on a vacation", partOfSpeech: "ph.", meaning: "休假中、度假中" },
  { id: "empty_a3b4c", word: "empty", partOfSpeech: "adj./v.", meaning: "空的、無意義的；倒空" },
  { id: "boring_d5e6f", word: "boring", partOfSpeech: "adj.", meaning: "無聊的" },
  { id: "email_g7h8i", word: "e-mail", partOfSpeech: "n.", meaning: "電子郵件" },
  { id: "interesting_j9k0l", word: "interesting", partOfSpeech: "adj.", meaning: "有趣的" },
  { id: "camera_m1n2o", word: "camera", partOfSpeech: "n.", meaning: "照相機" },
  { id: "dangerous_p3q4r", word: "dangerous", partOfSpeech: "adj.", meaning: "危險的、有威脅的" },
  { id: "getstuck_s5t6u", word: "get stuck", partOfSpeech: "ph.", meaning: "卡住、困住" },
  { id: "nurse_v7w8x", word: "nurse", partOfSpeech: "n.", meaning: "護士、護理人員" },
  { id: "glasses_y9z0a", word: "glasses", partOfSpeech: "n.", meaning: "眼鏡" },
  { id: "hamburger_b1c2d", word: "hamburger", partOfSpeech: "n.", meaning: "漢堡；漢堡牛肉餅" },
  { id: "break_e3f4g", word: "break", partOfSpeech: "v.", meaning: "打破、破裂、毀壞、破壞" },
  { id: "purpose_h5i6j", word: "purpose", partOfSpeech: "n.", meaning: "意圖、原因、目的" },
  { id: "puton_k7l8m", word: "put on", partOfSpeech: "ph.", meaning: "把...穿戴上；塗抹、擦上" },
  { id: "lizard_n9o0p", word: "lizard", partOfSpeech: "n.", meaning: "蜥蜴" },
  { id: "laptop_q1r2s", word: "laptop", partOfSpeech: "n.", meaning: "筆記型電腦" },
  { id: "climb_t3u4v", word: "climb", partOfSpeech: "v.", meaning: "爬、攀登、爬升" },
  { id: "playagainst_w5x6y", word: "play against", partOfSpeech: "ph.", meaning: "與...比賽；對抗" },
  { id: "seat_z7a8b", word: "seat", partOfSpeech: "n.", meaning: "座位" },
  { id: "juggle_c9d0e", word: "juggle", partOfSpeech: "v.", meaning: "玩雜耍" },
  { id: "rope_f1g2h", word: "rope", partOfSpeech: "n.", meaning: "繩索" },
  { id: "against_i3j4k", word: "against", partOfSpeech: "prep.", meaning: "反對、與...相反、緊靠著" },
  { id: "hate_l5m6n", word: "hate", partOfSpeech: "v.", meaning: "討厭、厭惡" },
  { id: "costume_o7p8q", word: "costume", partOfSpeech: "n.", meaning: "服裝、戲服" },
  { id: "trapeze_r9s0t", word: "trapeze", partOfSpeech: "n.", meaning: "高空秋千" },
  { id: "circus_u1v2w", word: "circus", partOfSpeech: "n.", meaning: "馬戲團" },
  { id: "suddenly_x3y4z", word: "suddenly", partOfSpeech: "adv.", meaning: "突然地、驟然" },
  { id: "dotrick_a5b6c", word: "do trick", partOfSpeech: "ph.", meaning: "變戲法、做惡作劇" },
  { id: "trampoline_d7e8f", word: "trampoline", partOfSpeech: "n.", meaning: "彈跳床、蹦床" },
  { id: "station_g9h0i", word: "station", partOfSpeech: "n.", meaning: "車站、電台、站、局" },
  { id: "plant_j1k2l", word: "plant", partOfSpeech: "n.", meaning: "植物" },
  { id: "lorry_m3n4o", word: "lorry (Br.)", partOfSpeech: "n.", meaning: "卡車、貨車" },
  { id: "footballmatch_p5q6r", word: "football match", partOfSpeech: "n.", meaning: "足球比賽" },
  { id: "subway_s7t8u", word: "subway", partOfSpeech: "n.", meaning: "地鐵" },
  { id: "medicine_v9w0x", word: "medicine", partOfSpeech: "n.", meaning: "藥物" },
  { id: "neck_y1z2a", word: "neck", partOfSpeech: "n.", meaning: "脖子、頸部" },
  { id: "head_b3c4d", word: "head", partOfSpeech: "n.", meaning: "頭" },
  { id: "wood_e5f6g", word: "wood", partOfSpeech: "n.", meaning: "木頭、木材" },
  { id: "atcamp_h7i8j", word: "at camp", partOfSpeech: "ph.", meaning: "在露營地" },
  { id: "hip_k9l0m", word: "hip", partOfSpeech: "n.", meaning: "臀部" },
  { id: "hand_n1o2p", word: "hand", partOfSpeech: "n.", meaning: "手" },
  { id: "inthewoods_q3r4s", word: "in the woods", partOfSpeech: "ph.", meaning: "在森林裡" },
  { id: "cover_t5u6v", word: "cover", partOfSpeech: "v.", meaning: "覆蓋、遮蔽" },
  { id: "shoulder_w7x8y", word: "shoulder", partOfSpeech: "n.", meaning: "肩膀" },
  { id: "foot_z9a0b", word: "foot", partOfSpeech: "n.", meaning: "腳、足" },
  { id: "touch_c1d2e", word: "touch", partOfSpeech: "v.", meaning: "觸摸、碰" },
  { id: "exciting_f3g4h", word: "exciting", partOfSpeech: "adj.", meaning: "令人興奮的、使人激動的" },
  { id: "elbow_i5j6k", word: "elbow", partOfSpeech: "n.", meaning: "手肘" },
  { id: "oval_l7m8n", word: "oval", partOfSpeech: "n./adj.", meaning: "橢圓形；橢圓形的" },
  { id: "try_o9p0q", word: "try", partOfSpeech: "v.", meaning: "嘗試、努力" },
  { id: "thinkof_r1s2t", word: "think of", partOfSpeech: "ph.", meaning: "想到、發明、覺得、認為" },
  { id: "knee_u3v4w", word: "knee", partOfSpeech: "n.", meaning: "膝蓋" },
  { id: "overlap_x5y6z", word: "overlap", partOfSpeech: "v.", meaning: "重疊" },
  { id: "hike_a7b8c", word: "hike", partOfSpeech: "v.", meaning: "健行" },
  { id: "plan_d9e0f", word: "plan", partOfSpeech: "v.", meaning: "計劃、安排" },
  { id: "canoe_g1h2i", word: "canoe", partOfSpeech: "v.", meaning: "划獨木舟" },
  { id: "snowboard_j3k4l", word: "snowboard", partOfSpeech: "v.", meaning: "單板滑雪" },
  { id: "helmet_m5n6o", word: "helmet", partOfSpeech: "n.", meaning: "安全帽" },
  { id: "weatherreport_p7q8r", word: "weather report", partOfSpeech: "n.", meaning: "天氣預報" },
  { id: "grill_s9t0u", word: "grill", partOfSpeech: "v.", meaning: "燒烤" },
  { id: "iceskate_v1w2x", word: "ice-skate", partOfSpeech: "v.", meaning: "溜冰" },
  { id: "sunscreen_y3z4a", word: "sunscreen", partOfSpeech: "n.", meaning: "防曬乳" },
  { id: "tomorrow_b5c6d", word: "tomorrow", partOfSpeech: "n.", meaning: "明天" },
  { id: "fish_e7f8g", word: "fish", partOfSpeech: "v.", meaning: "釣魚、捕魚" },
  { id: "inlineskate_h9i0j", word: "in-line skate", partOfSpeech: "n./v.", meaning: "直排輪鞋；溜直排輪" },
  { id: "lifejacket_k1l2m", word: "life jacket", partOfSpeech: "n.", meaning: "救生衣" },
  { id: "remember_n3o4p", word: "remember", partOfSpeech: "v.", meaning: "記得、記起" },
  { id: "watchbirds_q5r6s", word: "watch birds", partOfSpeech: "ph.", meaning: "賞鳥" },
  { id: "skateboard_t7u8v", word: "skateboard", partOfSpeech: "n./v.", meaning: "滑板；溜滑板" },
  { id: "fastenseatbelt_w9x0y", word: "fasten your seatbelt", partOfSpeech: "ph.", meaning: "繫上安全帶" },
  { id: "snowy_z1a2b", word: "snowy", partOfSpeech: "adj.", meaning: "下雪的" },
  { id: "ski_c3d4e", word: "ski", partOfSpeech: "n./v.", meaning: "滑雪板；滑雪" },
  { id: "surf_f5g6h", word: "surf", partOfSpeech: "v.", meaning: "衝浪、上網" },
  { id: "stone_i7j8k", word: "stone", partOfSpeech: "n.", meaning: "石頭、石塊" },
  { id: "around_l9m0n", word: "around", partOfSpeech: "adv./prep.", meaning: "周圍、圍繞" },
  { id: "hippopotamus_o1p2q", word: "hippopotamus", partOfSpeech: "n.", meaning: "河馬" },
  { id: "seal_r3s4t", word: "seal", partOfSpeech: "n.", meaning: "海豹" },
  { id: "octopus_u5v6w", word: "octopus", partOfSpeech: "n.", meaning: "章魚" },
  { id: "foolish_x7y8z", word: "foolish", partOfSpeech: "adj.", meaning: "愚蠢的、傻的" },
  { id: "gorilla_a9b0c", word: "gorilla", partOfSpeech: "n.", meaning: "大猩猩" },
  { id: "dolphin_d1e2f", word: "dolphin", partOfSpeech: "n.", meaning: "海豚" },
  { id: "length_g3h4i", word: "length", partOfSpeech: "n.", meaning: "長度" },
  { id: "fence_j5k6l", word: "fence", partOfSpeech: "n.", meaning: "柵欄、籬笆" },
  { id: "panda_m7n8o", word: "panda", partOfSpeech: "n.", meaning: "貓熊" },
  { id: "squid_p9q0r", word: "squid", partOfSpeech: "n.", meaning: "魷魚" },
  { id: "weight_s1t2u", word: "weight", partOfSpeech: "n.", meaning: "重量、體重" },
  { id: "taste_v3w4x", word: "taste", partOfSpeech: "v.", meaning: "品嚐" },
  { id: "caterpillar_y5z6a", word: "caterpillar", partOfSpeech: "n.", meaning: "毛毛蟲" },
  { id: "beetle_b7c8d", word: "beetle", partOfSpeech: "n.", meaning: "甲蟲" },
  { id: "blond_e9f0g", word: "blond", partOfSpeech: "adj.", meaning: "（毛髮）金黃色的" },
  { id: "seem_h1i2j", word: "seem", partOfSpeech: "v.", meaning: "似乎、看起來好像" },
  { id: "eel_k3l4m", word: "eel", partOfSpeech: "n.", meaning: "鰻魚" },
  { id: "crab_n5o6p", word: "crab", partOfSpeech: "n.", meaning: "螃蟹" },
  { id: "beard_q7r8s", word: "beard", partOfSpeech: "n.", meaning: "（下巴上的）鬍鬚" },
  { id: "stayhome_t9u0v", word: "stay home", partOfSpeech: "ph.", meaning: "待在家" },
  { id: "butterfly_w1x2y", word: "butterfly", partOfSpeech: "n.", meaning: "蝴蝶" },
  { id: "bee_z3a4b", word: "bee", partOfSpeech: "n.", meaning: "蜜蜂" },
  { id: "whale_c5d6e", word: "whale", partOfSpeech: "n.", meaning: "鯨魚" },
  { id: "shark_f7g8h", word: "shark", partOfSpeech: "n.", meaning: "鯊魚" },
  { id: "shoulderlength_i9j0k", word: "shoulder-length", partOfSpeech: "adj.", meaning: "齊肩的、及肩的" },
  { id: "earrings_l1m2n", word: "earrings", partOfSpeech: "n.", meaning: "耳環" },
  { id: "ocean_o3p4q", word: "ocean", partOfSpeech: "n.", meaning: "海洋" },
  { id: "famous_r5s6t", word: "famous", partOfSpeech: "adj.", meaning: "有名的、著名的" },
  { id: "straight_u7v8w", word: "straight", partOfSpeech: "adj.", meaning: "直的" },
  { id: "sunglasses_x9y0z", word: "sunglasses", partOfSpeech: "n.", meaning: "太陽眼鏡" },
  { id: "invite_a1b2c3", word: "invite", partOfSpeech: "v.", meaning: "邀請" },
  { id: "afraid_d4e5f6", word: "afraid", partOfSpeech: "adj.", meaning: "害怕的、擔憂的" },
  { id: "curly_g7h8i9", word: "curly", partOfSpeech: "adj.", meaning: "捲曲的" },
  { id: "stick_j0k1l2", word: "stick", partOfSpeech: "n.", meaning: "枝條、木棍" },
  { id: "first_m3n4o5", word: "first", partOfSpeech: "det.", meaning: "第一、首先" },
  { id: "island_p6q7r8", word: "island", partOfSpeech: "n.", meaning: "島嶼" },
  { id: "wavy_s9t0u1", word: "wavy", partOfSpeech: "adj.", meaning: "波浪狀的" },
  { id: "grass_v2w3x4", word: "grass", partOfSpeech: "n.", meaning: "草" },
  { id: "problem_y5z6a7", word: "problem", partOfSpeech: "n.", meaning: "問題、困難" },
  { id: "beableto_b8c9d0", word: "be able to", partOfSpeech: "ph.", meaning: "能夠、有...能力" },
  { id: "necklace_e1f2g3", word: "necklace", partOfSpeech: "n.", meaning: "項鍊" },
  { id: "sand_h4i5j6", word: "sand", partOfSpeech: "n.", meaning: "沙子" },
  { id: "land_k7l8m9", word: "land", partOfSpeech: "v.", meaning: "著陸、降落" },
  { id: "sportsstar_n0o1p2", word: "sports star", partOfSpeech: "n.", meaning: "運動明星" },
  { id: "shoulderlengthhair_q3r4s5", word: "shoulder-length hair", partOfSpeech: "n.", meaning: "及肩長髮" },
  { id: "shorthair_t6u7v8", word: "short hair", partOfSpeech: "n.", meaning: "短髮" },
  { id: "longhair_w9x0y1", word: "long hair", partOfSpeech: "n.", meaning: "長髮" },
  { id: "straighthair_z2a3b4", word: "straight hair", partOfSpeech: "n.", meaning: "直髮" },
  { id: "curlyhair_c5d6e7", word: "curly hair", partOfSpeech: "n.", meaning: "捲髮" },
  { id: "wavyhair_f8g9h0", word: "wavy hair", partOfSpeech: "n.", meaning: "波浪狀捲髮" },
  { id: "watch_i1j2k3", word: "watch", partOfSpeech: "n.", meaning: "手錶" },
  { id: "gloves_l4m5n6", word: "gloves", partOfSpeech: "n.", meaning: "手套" },
  { id: "belt_o7p8q9", word: "belt", partOfSpeech: "n.", meaning: "腰帶" },
  { id: "baseball_r0s1t2", word: "baseball", partOfSpeech: "n.", meaning: "棒球" },
  { id: "basketball_u3v4w5", word: "basketball", partOfSpeech: "n.", meaning: "籃球" },
  { id: "volleyball_x6y7z8", word: "volleyball", partOfSpeech: "n.", meaning: "排球" },
  { id: "golf_a9b0c1", word: "golf", partOfSpeech: "n.", meaning: "高爾夫球" },
  { id: "helpmyparents_d2e3f4", word: "help my parents", partOfSpeech: "ph.", meaning: "幫忙我的父母" },
  { id: "metal_g5h6i7", word: "metal", partOfSpeech: "n.", meaning: "金屬" },
  { id: "surprised_j8k9l0", word: "surprised", partOfSpeech: "adj.", meaning: "驚訝的、意外的" },
  { id: "tabletennis_m1n2o3", word: "table tennis / tennis", partOfSpeech: "n.", meaning: "桌球 / 網球" },
  { id: "visitmyfriend_p4q5r6", word: "visit my friend", partOfSpeech: "ph.", meaning: "拜訪我的朋友" },
  { id: "study_s7t8u9", word: "study", partOfSpeech: "v.", meaning: "學習、研究" },
  { id: "smart_v0w1x2", word: "smart", partOfSpeech: "adj.", meaning: "聰明的（US）；時髦的（UK）" },
  { id: "practicepiano_y3z4a5", word: "practice the piano", partOfSpeech: "ph.", meaning: "練習鋼琴" },
  { id: "workonproject_b6c7d8", word: "work on a project", partOfSpeech: "ph.", meaning: "進行一個專案" },
  { id: "cage_e9f0g1", word: "cage", partOfSpeech: "n.", meaning: "籠子" },
  { id: "useful_h2i3j4", word: "useful", partOfSpeech: "adj.", meaning: "有用的、有效的" },
  { id: "usecomputer_k5l6m7", word: "use the computer", partOfSpeech: "ph.", meaning: "使用電腦" },
  { id: "clay_n8o9p0", word: "clay", partOfSpeech: "n.", meaning: "黏土" },
  { id: "wall_q1r2s3", word: "wall", partOfSpeech: "n.", meaning: "牆壁" },
  { id: "delicious_t4u5v6", word: "delicious", partOfSpeech: "adj.", meaning: "美味的" },
  { id: "talkonphone_w7x8y9", word: "talk on the phone", partOfSpeech: "ph.", meaning: "講電話" },
  { id: "glass_z0a1b2", word: "glass", partOfSpeech: "n.", meaning: "玻璃製品、杯子" },
  { id: "pull_c3d4e5", word: "pull", partOfSpeech: "v.", meaning: "拉、拖、抽出" },
  { id: "toward_f6g7h8", word: "toward", partOfSpeech: "prep.", meaning: "朝向、接近" },
  { id: "careful_i9j0k1", word: "careful", partOfSpeech: "adj.", meaning: "仔細的、小心的、認真的" },
  { id: "goat_l2m3n4", word: "goat", partOfSpeech: "n.", meaning: "山羊" },
  { id: "riverbridge_o5p6q7", word: "river / bridge", partOfSpeech: "n.", meaning: "河流 / 橋樑" },
  { id: "wear_r8s9t0", word: "wear", partOfSpeech: "v.", meaning: "穿、戴" },
  { id: "angry_u1v2w3", word: "angry", partOfSpeech: "adj.", meaning: "生氣的、憤怒的" },
  { id: "fly_x4y5z6", word: "fly", partOfSpeech: "v.", meaning: "飛行" },
  { id: "through_a7b8c9", word: "through", partOfSpeech: "prep.", meaning: "穿過、通過" },
  { id: "leaf_d0e1f2", word: "leaf", partOfSpeech: "n.", meaning: "葉子" },
  { id: "laughat_g3h4i5", word: "laugh at", partOfSpeech: "ph.", meaning: "嘲笑" },
  { id: "practiceving_j6k7l8", word: "practice V-ing / N.", partOfSpeech: "ph.", meaning: "練習..." },
  { id: "lookforwardto_m9n0o1", word: "look forward to V-ing / N.", partOfSpeech: "ph.", meaning: "期待、盼望..." },
  { id: "ridesubway_p2q3r4", word: "ride the subway to...", partOfSpeech: "ph.", meaning: "搭地鐵去..." },
  { id: "beaboutto_s5t6u7", word: "be about to V.", partOfSpeech: "ph.", meaning: "快要、即將..." },
  { id: "goout_v8w9x0", word: "go out", partOfSpeech: "ph.", meaning: "熄滅、外出" },
  { id: "waterplants_y1z2a3", word: "water the plants", partOfSpeech: "ph.", meaning: "給植物澆水" },
  { id: "takemedicine_b4c5d6", word: "take (some) medicine", partOfSpeech: "ph.", meaning: "服藥" },
  { id: "pickup_e7f8g9", word: "pick up", partOfSpeech: "ph.", meaning: "接送、撿起、順道購買" },
  { id: "haveanidea_h0i1j2", word: "have an idea to V.", partOfSpeech: "ph.", meaning: "想出一個辦法、主意" },
  { id: "gocamping_k3l4m5", word: "go camping", partOfSpeech: "ph.", meaning: "去露營" },
  { id: "putout_n6o7p8", word: "put out", partOfSpeech: "ph.", meaning: "撲滅、熄滅；出版、生產" },
  { id: "befoolishof_q9r0s1", word: "be foolish of", partOfSpeech: "ph.", meaning: "做...是很傻的" },
  { id: "takecareeof_t2u3v4", word: "take (good) care of", partOfSpeech: "ph.", meaning: "（好好）照顧" },
  { id: "behappywith_w5x6y7", word: "be happy with", partOfSpeech: "ph.", meaning: "對...感到滿意、高興" },
  { id: "invitesb_z8a9b0", word: "invite sb. to V.", partOfSpeech: "ph.", meaning: "邀請某人做..." },
  { id: "runinto_c1d2e3", word: "run into", partOfSpeech: "ph.", meaning: "偶然遇見、遭遇困難、碰撞" },
  { id: "besurprisedto_f4g5h6", word: "be surprised to V.", partOfSpeech: "ph.", meaning: "對（做某事）感到驚訝" },
  { id: "findout_i7j8k9", word: "find out", partOfSpeech: "ph.", meaning: "發現、得知、查明" },
  { id: "getridof_l0m1n2", word: "get rid of", partOfSpeech: "ph.", meaning: "擺脫、除去、處理" },
];
