import { Word } from '../types';

const serverData: Word[] = [
    { "id": 1, "date": "2025-10-30", "english": "torch", "chinese": "手電筒", "part_of_speech": "(n.)" },
    { "id": 2, "date": "2025-10-30", "english": "comb", "chinese": "梳子", "part_of_speech": "(n.)" },
    { "id": 3, "date": "2025-10-30", "english": "sleeping bag", "chinese": "睡袋", "part_of_speech": "(n.)" },
    { "id": 4, "date": "2025-10-30", "english": "teddy", "chinese": "玩具熊", "part_of_speech": "(n.)" },
    { "id": 5, "date": "2025-10-30", "english": "pillow", "chinese": "枕頭", "part_of_speech": "(n.)" },
    { "id": 6, "date": "2025-10-31", "english": "contest", "chinese": "比賽", "part_of_speech": "(n.)" },
    { "id": 7, "date": "2025-10-31", "english": "piece", "chinese": "片/塊", "part_of_speech": "(n.)" },
    { "id": 8, "date": "2025-10-31", "english": "serve", "chinese": "服務；提供", "part_of_speech": "(v.)" },
    { "id": 9, "date": "2025-10-31", "english": "winner", "chinese": "贏家；獲勝者", "part_of_speech": "(n.)" },
    { "id": 10, "date": "2025-10-31", "english": "chart", "chinese": "圖表", "part_of_speech": "(n.)" },
    { "id": 11, "date": "2025-11-03", "english": "pyjamas(Br.)/pajamas(US)", "chinese": "睡衣褲", "part_of_speech": "(n.)" },
    { "id": 12, "date": "2025-11-03", "english": "blanket", "chinese": "毯子", "part_of_speech": "(n.)" },
    { "id": 13, "date": "2025-11-03", "english": "sunglasses", "chinese": "墨鏡", "part_of_speech": "(n.)" },
    { "id": 14, "date": "2025-11-03", "english": "mat", "chinese": "地墊", "part_of_speech": "(n.)" },
    { "id": 15, "date": "2025-11-03", "english": "towel", "chinese": "毛巾", "part_of_speech": "(n.)" },
    { "id": 16, "date": "2025-11-05", "english": "toothbrush", "chinese": "牙刷", "part_of_speech": "(n.)" },
    { "id": 17, "date": "2025-11-05", "english": "campsite", "chinese": "露營地", "part_of_speech": "(n.)" },
    { "id": 18, "date": "2025-11-05", "english": "dinosaur", "chinese": "恐龍", "part_of_speech": "(n.)" },
    { "id": 19, "date": "2025-11-05", "english": "surfboard", "chinese": "衝浪板", "part_of_speech": "(n.)" },
    { "id": 20, "date": "2025-11-05", "english": "postcard", "chinese": "明信片", "part_of_speech": "(n.)" },
    { "id": 21, "date": "2025-11-06", "english": "mall", "chinese": "購物中心", "part_of_speech": "(n.)" },
    { "id": 22, "date": "2025-11-06", "english": "noise", "chinese": "噪音", "part_of_speech": "(n.)" },
    { "id": 23, "date": "2025-11-06", "english": "spotted", "chinese": "有斑點的", "part_of_speech": "(adj.)" },
    { "id": 24, "date": "2025-11-06", "english": "owl", "chinese": "貓頭鷹", "part_of_speech": "(n.)" },
    { "id": 25, "date": "2025-11-06", "english": "enormous", "chinese": "巨大的", "part_of_speech": "(adj.)" },
    { "id": 26, "date": "2025-11-07", "english": "hurt", "chinese": "使受傷", "part_of_speech": "(v.)" },
    { "id": 27, "date": "2025-11-07", "english": "stand", "chinese": "站立", "part_of_speech": "(v.)" },
    { "id": 28, "date": "2025-11-07", "english": "surf", "chinese": "衝浪；上網", "part_of_speech": "(v.)" },
    { "id": 29, "date": "2025-11-07", "english": "turn", "chinese": "轉向", "part_of_speech": "(v.)" },
    { "id": 30, "date": "2025-11-07", "english": "weather", "chinese": "天氣", "part_of_speech": "(n.)" },
    { "id": 31, "date": "2025-11-10", "english": "figure", "chinese": "模型/外型", "part_of_speech": "(n.)" },
    { "id": 32, "date": "2025-11-10", "english": "fast", "chinese": "快的", "part_of_speech": "(adj.)" },
    { "id": 33, "date": "2025-11-10", "english": "slow", "chinese": "慢的", "part_of_speech": "(adj.)" },
    { "id": 34, "date": "2025-11-10", "english": "loud", "chinese": "大聲的", "part_of_speech": "(adj.)" },
    { "id": 35, "date": "2025-11-10", "english": "quiet", "chinese": "安靜的", "part_of_speech": "(adj.)" },
    { "id": 36, "date": "2025-11-12", "english": "snowy", "chinese": "下雪的", "part_of_speech": "(adj.)" },
    { "id": 37, "date": "2025-11-12", "english": "sandy", "chinese": "含沙的", "part_of_speech": "(adj.)" },
    { "id": 38, "date": "2025-11-12", "english": "snowboard", "chinese": "單板滑雪", "part_of_speech": "(v.)" },
    { "id": 39, "date": "2025-11-12", "english": "skate", "chinese": "溜冰", "part_of_speech": "(v.)" },
    { "id": 40, "date": "2025-11-12", "english": "strong", "chinese": "強壯的", "part_of_speech": "(adj.)" },
    { "id": 41, "date": "2025-11-13", "english": "difficult", "chinese": "困難的", "part_of_speech": "(adj.)" },
    { "id": 42, "date": "2025-11-13", "english": "different", "chinese": "不同的", "part_of_speech": "(adj.)" },
    { "id": 43, "date": "2025-11-13", "english": "cousin", "chinese": "堂(表)兄弟姊妹", "part_of_speech": "(n.)" },
    { "id": 44, "date": "2025-11-13", "english": "everyone", "chinese": "每個人", "part_of_speech": "(pron.)" },
    { "id": 45, "date": "2025-11-13", "english": "brilliant", "chinese": "聰穎的；出色的", "part_of_speech": "(adj.)" },
    { "id": 46, "date": "2025-11-14", "english": "bear", "chinese": "熊", "part_of_speech": "(n.)" },
    { "id": 47, "date": "2025-11-14", "english": "monkey", "chinese": "猴子", "part_of_speech": "(n.)" },
    { "id": 48, "date": "2025-11-14", "english": "dark", "chinese": "黑暗的", "part_of_speech": "(adj.)" },
    { "id": 49, "date": "2025-11-14", "english": "scared", "chinese": "驚恐的", "part_of_speech": "(adj.)" },
    { "id": 50, "date": "2025-11-14", "english": "surfing", "chinese": "衝浪運動", "part_of_speech": "(n.)" },
    { "id": 51, "date": "2025-11-17", "english": "horse", "chinese": "馬", "part_of_speech": "(n.)" },
    { "id": 52, "date": "2025-11-17", "english": "snake", "chinese": "蛇", "part_of_speech": "(n.)" },
    { "id": 53, "date": "2025-11-17", "english": "lion", "chinese": "獅子", "part_of_speech": "(n.)" },
    { "id": 54, "date": "2025-11-17", "english": "high / low", "chinese": "高的/低的", "part_of_speech": "(adj.)" },
    { "id": 55, "date": "2025-11-17", "english": "art", "chinese": "藝術", "part_of_speech": "(n.)" },
    { "id": 56, "date": "2025-11-19", "english": "road", "chinese": "路", "part_of_speech": "(n.)" },
    { "id": 57, "date": "2025-11-19", "english": "same", "chinese": "一樣的", "part_of_speech": "(adj.)" },
    { "id": 58, "date": "2025-11-19", "english": "ride", "chinese": "騎車", "part_of_speech": "(v.)" },
    { "id": 59, "date": "2025-11-19", "english": "club", "chinese": "社團", "part_of_speech": "(n.)" },
    { "id": 60, "date": "2025-11-19", "english": "science", "chinese": "科學", "part_of_speech": "(n.)" },
    { "id": 61, "date": "2025-11-20", "english": "popular", "chinese": "受歡迎的", "part_of_speech": "(adj.)" },
    { "id": 62, "date": "2025-11-20", "english": "library", "chinese": "圖書館", "part_of_speech": "(n.)" },
    { "id": 63, "date": "2025-11-20", "english": "exercise", "chinese": "練習；運動", "part_of_speech": "(v.)" },
    { "id": 64, "date": "2025-11-20", "english": "famous", "chinese": "有名的", "part_of_speech": "(adj.)" },
    { "id": 65, "date": "2025-11-20", "english": "weekend", "chinese": "週末", "part_of_speech": "(n.)" },
    { "id": 66, "date": "2025-11-21", "english": "mouse", "chinese": "老鼠", "part_of_speech": "(n.)" },
    { "id": 67, "date": "2025-11-21", "english": "elephant", "chinese": "大象", "part_of_speech": "(n.)" },
    { "id": 68, "date": "2025-11-21", "english": "parrot", "chinese": "鸚鵡", "part_of_speech": "(n.)" },
    { "id": 69, "date": "2025-11-21", "english": "hen", "chinese": "母雞", "part_of_speech": "(n.)" },
    { "id": 70, "date": "2025-11-21", "english": "relax", "chinese": "放鬆", "part_of_speech": "(v.)" },
    { "id": 71, "date": "2025-11-24", "english": "rock", "chinese": "岩石", "part_of_speech": "(n.)" },
    { "id": 72, "date": "2025-11-24", "english": "bell", "chinese": "鐘", "part_of_speech": "(n.)" },
    { "id": 73, "date": "2025-11-24", "english": "fewest", "chinese": "最少的", "part_of_speech": "(adj.)" },
    { "id": 74, "date": "2025-11-24", "english": "mountain bike", "chinese": "騎登山越野車", "part_of_speech": "(v.)" },
    { "id": 75, "date": "2025-11-24", "english": "sport", "chinese": "體育；運動", "part_of_speech": "(n.)" },
    { "id": 76, "date": "2025-11-26", "english": "food court", "chinese": "美食廣場", "part_of_speech": "(n.)" },
    { "id": 77, "date": "2025-11-26", "english": "floor", "chinese": "地板", "part_of_speech": "(n.)" },
    { "id": 78, "date": "2025-11-26", "english": "relaxing", "chinese": "令人放鬆的", "part_of_speech": "(adj.)" },
    { "id": 79, "date": "2025-11-26", "english": "tortoise", "chinese": "陸龜", "part_of_speech": "(n.)" },
    { "id": 80, "date": "2025-11-26", "english": "butterfly", "chinese": "蝴蝶", "part_of_speech": "(n.)" },
    { "id": 81, "date": "2025-11-27", "english": "rest", "chinese": "休息", "part_of_speech": "(n.)" },
    { "id": 82, "date": "2025-11-27", "english": "canary", "chinese": "金絲雀", "part_of_speech": "(n.)" },
    { "id": 83, "date": "2025-11-27", "english": "lizard", "chinese": "蜥蜴", "part_of_speech": "(n.)" },
    { "id": 84, "date": "2025-11-27", "english": "stick insects", "chinese": "竹節蟲", "part_of_speech": "(n.)" },
    { "id": 85, "date": "2025-11-27", "english": "snail", "chinese": "蝸牛", "part_of_speech": "(n.)" },
    { "id": 86, "date": "2025-11-28", "english": "guinea pig", "chinese": "天竺鼠", "part_of_speech": "(n.)" },
    { "id": 87, "date": "2025-11-28", "english": "hide", "chinese": "藏起來", "part_of_speech": "(v.)" },
    { "id": 88, "date": "2025-11-28", "english": "storm", "chinese": "暴風雨", "part_of_speech": "(n.)" },
    { "id": 89, "date": "2025-11-28", "english": "stormy", "chinese": "暴風雨的", "part_of_speech": "(adj.)" },
    { "id": 90, "date": "2025-11-28", "english": "cloudy", "chinese": "陰天的；多雲的", "part_of_speech": "(adj.)" },
    { "id": 91, "date": "2025-12-01", "english": "rabbit", "chinese": "兔子", "part_of_speech": "(n.)" },
    { "id": 92, "date": "2025-12-01", "english": "reptile center", "chinese": "爬行動物中心", "part_of_speech": "(n.)" },
    { "id": 93, "date": "2025-12-01", "english": "rescue", "chinese": "救援", "part_of_speech": "(n.)" },
    { "id": 94, "date": "2025-12-01", "english": "owner", "chinese": "主人", "part_of_speech": "(n.)" },
    { "id": 95, "date": "2025-12-01", "english": "python", "chinese": "巨蟒", "part_of_speech": "(n.)" },
    { "id": 96, "date": "2025-12-03", "english": "crocodile", "chinese": "鱷魚", "part_of_speech": "(n.)" },
    { "id": 97, "date": "2025-12-03", "english": "giant", "chinese": "巨大的", "part_of_speech": "(adj.)" },
    { "id": 98, "date": "2025-12-03", "english": "shame", "chinese": "可惜；羞恥", "part_of_speech": "(n.)" },
    { "id": 99, "date": "2025-12-03", "english": "chameleon", "chinese": "變色龍", "part_of_speech": "(n.)" },
    { "id": 100, "date": "2025-12-03", "english": "stripy", "chinese": "條紋的", "part_of_speech": "(adj.)" },
    { "id": 101, "date": "2025-12-04", "english": "excited", "chinese": "興奮的", "part_of_speech": "(adj.)" },
    { "id": 102, "date": "2025-12-04", "english": "energy", "chinese": "活力；能量", "part_of_speech": "(n.)" },
    { "id": 103, "date": "2025-12-04", "english": "hear", "chinese": "聽到", "part_of_speech": "(v.)" },
    { "id": 104, "date": "2025-12-04", "english": "thunder", "chinese": "雷", "part_of_speech": "(n.)" },
    { "id": 105, "date": "2025-12-04", "english": "lightning", "chinese": "閃電", "part_of_speech": "(n.)" },
    { "id": 106, "date": "2025-12-05", "english": "warm", "chinese": "溫暖的", "part_of_speech": "(adj.)" },
    { "id": 107, "date": "2025-12-05", "english": "bicycle", "chinese": "腳踏車", "part_of_speech": "(n.)" },
    { "id": 108, "date": "2025-12-05", "english": "sound", "chinese": "聽起來", "part_of_speech": "(v.)" },
    { "id": 109, "date": "2025-12-05", "english": "fish", "chinese": "魚", "part_of_speech": "(n.)" },
    { "id": 110, "date": "2025-12-05", "english": "change", "chinese": "交換；改變", "part_of_speech": "(v.)" },
    { "id": 111, "date": "2025-12-08", "english": "Habitat", "chinese": "棲息地", "part_of_speech": "(n.)" },
    { "id": 112, "date": "2025-12-08", "english": "fact file", "chinese": "事實檔案", "part_of_speech": "(n.)" },
    { "id": 113, "date": "2025-12-08", "english": "iguana", "chinese": "鬣蜥", "part_of_speech": "(n.)" },
    { "id": 114, "date": "2025-12-08", "english": "tongue", "chinese": "舌頭", "part_of_speech": "(n.)" },
    { "id": 115, "date": "2025-12-08", "english": "insect", "chinese": "昆蟲", "part_of_speech": "(n.)" },
    { "id": 116, "date": "2025-12-08", "english": "go on vacation", "chinese": "去度假", "part_of_speech": "(phr.)" },
    { "id": 117, "date": "2025-12-10", "english": "temperature", "chinese": "溫度", "part_of_speech": "(n.)" },
    { "id": 118, "date": "2025-12-10", "english": "ladybird/ladybug", "chinese": "瓢蟲", "part_of_speech": "(n.)" },
    { "id": 119, "date": "2025-12-10", "english": "grasshopper", "chinese": "蚱蜢", "part_of_speech": "(n.)" },
    { "id": 120, "date": "2025-12-10", "english": "dragonfly", "chinese": "蜻蜓", "part_of_speech": "(n.)" },
    { "id": 121, "date": "2025-12-10", "english": "body parts", "chinese": "身體部位", "part_of_speech": "(n.)" },
    { "id": 122, "date": "2025-12-10", "english": "have fun", "chinese": "玩得開心", "part_of_speech": "(phr.)" },
    { "id": 123, "date": "2025-12-11", "english": "neck", "chinese": "脖子", "part_of_speech": "(n.)" },
    { "id": 124, "date": "2025-12-11", "english": "necklace", "chinese": "項鍊", "part_of_speech": "(n.)" },
    { "id": 125, "date": "2025-12-11", "english": "present", "chinese": "禮物", "part_of_speech": "(n.)" },
    { "id": 126, "date": "2025-12-11", "english": "mean", "chinese": "小氣的;刻薄的", "part_of_speech": "(adj.)" },
    { "id": 127, "date": "2025-12-11", "english": "live", "chinese": "生活", "part_of_speech": "(v.)" },
    { "id": 128, "date": "2025-12-12", "english": "windy", "chinese": "颳(刮)風的", "part_of_speech": "(adj.)" },
    { "id": 129, "date": "2025-12-12", "english": "vacation", "chinese": "假期", "part_of_speech": "(n.)" },
    { "id": 130, "date": "2025-12-12", "english": "beach", "chinese": "海邊;海灘", "part_of_speech": "(n.)" },
    { "id": 131, "date": "2025-12-12", "english": "address", "chinese": "地址", "part_of_speech": "(n.)" },
    { "id": 132, "date": "2025-12-12", "english": "hotel", "chinese": "飯店", "part_of_speech": "(n.)" },
    { "id": 133, "date": "2025-12-11", "english": "go surfing / fishing", "chinese": "去衝浪 ; 去釣魚", "part_of_speech": "(phr.)" },
    { "id": 134, "date": "2025-12-08", "english": "tempo", "chinese": "拍子; 節奏", "part_of_speech": "(n.)" },
    { "id": 135, "date": "2025-12-08", "english": "bathhouse", "chinese": "澡堂; 公共浴室", "part_of_speech": "(n.)" },
    { "id": 136, "date": "2025-12-08", "english": "get excited", "chinese": "感到興奮", "part_of_speech": "(ph.)" },
    { "id": 137, "date": "2025-12-08", "english": "hear sth. on the news", "chinese": "在新聞上聽到...", "part_of_speech": "(ph.)" },
    { "id": 138, "date": "2025-12-08", "english": "read sth. in the newspaper", "chinese": "在報紙上看到...", "part_of_speech": "(ph.)" },
    { "id": 139, "date": "2025-12-17", "english": "queen bee", "chinese": "蜂后", "part_of_speech": "(n.)" },
    { "id": 140, "date": "2025-12-17", "english": "spider", "chinese": "蜘蛛", "part_of_speech": "(n.)" },
    { "id": 141, "date": "2025-12-17", "english": "sting", "chinese": "叮咬", "part_of_speech": "(v.)" },
    { "id": 142, "date": "2025-12-17", "english": "be made of", "chinese": "用...做成", "part_of_speech": "(ph.)" },
    { "id": 143, "date": "2025-12-17", "english": "spend the weekend", "chinese": "度過周末", "part_of_speech": "(ph.)" },
    { "id": 144, "date": "2025-12-17", "english": "have a picnic", "chinese": "去野餐", "part_of_speech": "(ph.)" },
    { "id": 145, "date": "2025-12-17", "english": "restaurant", "chinese": "餐廳", "part_of_speech": "(n.)" },
    { "id": 146, "date": "2025-12-17", "english": "boat", "chinese": "小船", "part_of_speech": "(n.)" },
    { "id": 147, "date": "2025-12-18", "english": "camping", "chinese": "露營", "part_of_speech": "(n.)" },
    { "id": 148, "date": "2025-12-18", "english": "matter", "chinese": "事情", "part_of_speech": "(n.)" },
    { "id": 149, "date": "2025-12-18", "english": "pitch", "chinese": "音調", "part_of_speech": "(n.)" },
    { "id": 150, "date": "2025-12-18", "english": "tempo", "chinese": "拍子; 節奏", "part_of_speech": "(n.)" },
    { "id": 151, "date": "2025-12-18", "english": "bathhouse", "chinese": "澡堂; 公共浴室", "part_of_speech": "(n.)" },
    { "id": 152, "date": "2025-12-18", "english": "get excited", "chinese": "感到興奮", "part_of_speech": "(ph.)" },
    { "id": 153, "date": "2025-12-18", "english": "hear sth. on the news", "chinese": "在新聞上聽到...", "part_of_speech": "(ph.)" },
    { "id": 154, "date": "2025-12-18", "english": "read sth. in the newspaper", "chinese": "在報紙上看到...", "part_of_speech": "(ph.)" },
    { "id": 155, "date": "2025-12-19", "english": "sleep", "chinese": "睡覺", "part_of_speech": "(v.)" },
    { "id": 156, "date": "2025-12-19", "english": "wish", "chinese": "希望", "part_of_speech": "(v.)" },
    { "id": 157, "date": "2025-12-19", "english": "become", "chinese": "變成", "part_of_speech": "(v.)" },
    { "id": 158, "date": "2025-12-19", "english": "outside", "chinese": "在外面", "part_of_speech": "(adv.)" },
    { "id": 159, "date": "2025-12-19", "english": "anymore", "chinese": "再也不", "part_of_speech": "(adv.)" },
    { "id": 160, "date": "2025-12-19", "english": "go on vacation", "chinese": "去度假", "part_of_speech": "(phr.)" },
    { "id": 161, "date": "2025-12-19", "english": "have fun", "chinese": "玩得很開心", "part_of_speech": "(phr.)" },
    { "id": 162, "date": "2025-12-19", "english": "go surfing/fishing", "chinese": "去衝浪; 去釣魚", "part_of_speech": "(phr.)" },
    { "id": 163, "date": "2025-12-22", "english": "ant", "chinese": "螞蟻", "part_of_speech": "(n.)" },
    { "id": 164, "date": "2025-12-22", "english": "minute", "chinese": "分鐘*", "part_of_speech": "(n.)" },
    { "id": 165, "date": "2025-12-22", "english": "pizza", "chinese": "披薩*", "part_of_speech": "(n.)" },
    { "id": 166, "date": "2025-12-22", "english": "chicken", "chinese": "雞;雞肉*", "part_of_speech": "(n.)" },
    { "id": 167, "date": "2025-12-22", "english": "win(won)", "chinese": "贏;獲勝", "part_of_speech": "(v.)" },
    { "id": 168, "date": "2025-12-22", "english": "museum", "chinese": "博物館", "part_of_speech": "(n.)" },
    { "id": 169, "date": "2025-12-22", "english": "fantastic", "chinese": "極好的", "part_of_speech": "(adj.)" },
    { "id": 170, "date": "2025-12-22", "english": "dynamics", "chinese": "動力學; (音樂)力度", "part_of_speech": "(n.)" },
    { "id": 171, "date": "2025-12-22", "english": "computer", "chinese": "電腦", "part_of_speech": "(n.)" },
    { "id": 172, "date": "2025-12-22", "english": "read(read)", "chinese": "閱讀", "part_of_speech": "(v.)" },
    { "id": 173, "date": "2025-12-22", "english": "watch movies", "chinese": "看電影", "part_of_speech": "(ph.)" },
    { "id": 174, "date": "2025-12-22", "english": "fly", "chinese": "蒼蠅", "part_of_speech": "(n.)" },
    { "id": 175, "date": "2025-12-22", "english": "bee", "chinese": "蜜蜂", "part_of_speech": "(n.)" },
    { "id": 176, "date": "2025-12-23", "english": "get first(second) place", "chinese": "獲得第一(第二)", "part_of_speech": "(ph.)" },
    { "id": 177, "date": "2025-12-23", "english": "be (get/feel) tired", "chinese": "覺得累了", "part_of_speech": "(ph.)" },
    { "id": 178, "date": "2025-12-23", "english": "the same number of ...", "chinese": "數量相同的", "part_of_speech": "(ph.)" },
    { "id": 179, "date": "2025-12-23", "english": "go skiing", "chinese": "去滑雪", "part_of_speech": "(ph.)" },
    { "id": 180, "date": "2025-12-23", "english": "think of ...", "chinese": "認為、覺得;想出", "part_of_speech": "(ph.)" },
    { "id": 181, "date": "2025-12-23", "english": "talk about ...", "chinese": "討論", "part_of_speech": "(ph.)" },
    { "id": 182, "date": "2025-12-23", "english": "one's favorite thing to do is ...", "chinese": "(誰)最喜歡做...", "part_of_speech": "(ph.)" },
    { "id": 183, "date": "2025-12-23", "english": "help sb. with sth.", "chinese": "幫助(誰)做了...", "part_of_speech": "(ph.)" },
    { "id": 184, "date": "2025-12-23", "english": "be made of", "chinese": "用...做成", "part_of_speech": "(ph.)" },
    { "id": 185, "date": "2025-12-23", "english": "spend the weekend", "chinese": "度過週末", "part_of_speech": "(ph.)" },
    { "id": 186, "date": "2025-12-23", "english": "boat/sea/sky", "chinese": "小船/海/天空", "part_of_speech": "(n.)" },
    { "id": 187, "date": "2026-01-02", "english": "Broccoli", "chinese": "花椰菜", "part_of_speech": "(n.)" },
    { "id": 188, "date": "2026-01-02", "english": "Spinach", "chinese": "菠菜", "part_of_speech": "(n.)" },
    { "id": 189, "date": "2026-01-02", "english": "Strawberry", "chinese": "草莓", "part_of_speech": "(n.)" },
    { "id": 190, "date": "2026-01-02", "english": "flour", "chinese": "麵粉", "part_of_speech": "(n.)" },
    { "id": 191, "date": "2026-01-02", "english": "butter", "chinese": "奶油", "part_of_speech": "(n.)" },
    { "id": 192, "date": "2026-01-05", "english": "Cocoa", "chinese": "可可粉", "part_of_speech": "(n.)" },
    { "id": 193, "date": "2026-01-05", "english": "Asparagus", "chinese": "蘆筍", "part_of_speech": "(n.)" },
    { "id": 194, "date": "2026-01-05", "english": "Coconut", "chinese": "椰子", "part_of_speech": "(n.)" },
    { "id": 195, "date": "2026-01-05", "english": "egg", "chinese": "蛋", "part_of_speech": "(n.)" },
    { "id": 196, "date": "2026-01-05", "english": "cheese", "chinese": "起司、乳酪", "part_of_speech": "(n.)" },
    { "id": 197, "date": "2026-01-05", "english": "think about", "chinese": "思考;考慮", "part_of_speech": "(ph.)" },
    { "id": 198, "date": "2026-01-07", "english": "biscuit", "chinese": "餅乾", "part_of_speech": "(n.)" },
    { "id": 199, "date": "2026-01-07", "english": "Sugar", "chinese": "糖", "part_of_speech": "(n.)" },
    { "id": 200, "date": "2026-01-07", "english": "Supermarket", "chinese": "超級市場", "part_of_speech": "(n.)" },
    { "id": 201, "date": "2026-01-07", "english": "present", "chinese": "禮物", "part_of_speech": "(n.)" },
    { "id": 202, "date": "2026-01-07", "english": "surprise", "chinese": "驚喜、驚訝", "part_of_speech": "(n.)" },
    { "id": 203, "date": "2026-01-07", "english": "make friends with", "chinese": "交朋友", "part_of_speech": "(ph.)" },
    { "id": 204, "date": "2026-01-08", "english": "cry", "chinese": "哭", "part_of_speech": "(v.)" },
    { "id": 205, "date": "2026-01-08", "english": "door", "chinese": "門", "part_of_speech": "(n.)" },
    { "id": 206, "date": "2026-01-08", "english": "together", "chinese": "一起", "part_of_speech": "(adv.)" },
    { "id": 207, "date": "2026-01-08", "english": "knock", "chinese": "敲;擊", "part_of_speech": "(v.)" },
    { "id": 208, "date": "2026-01-08", "english": "family", "chinese": "家庭", "part_of_speech": "(n.)" },
    { "id": 209, "date": "2026-01-08", "english": "run away from", "chinese": "逃離; 躲避", "part_of_speech": "(ph.)" },
    { "id": 210, "date": "2026-01-09", "english": "young", "chinese": "年輕的", "part_of_speech": "(adj.)" },
    { "id": 211, "date": "2026-01-09", "english": "worry", "chinese": "擔心;發愁", "part_of_speech": "(v.)" },
    { "id": 212, "date": "2026-01-09", "english": "size", "chinese": "尺寸;大小", "part_of_speech": "(n.)" },
    { "id": 213, "date": "2026-01-09", "english": "team", "chinese": "團隊;隊", "part_of_speech": "(n.)" },
    { "id": 214, "date": "2026-01-09", "english": "score", "chinese": "得分", "part_of_speech": "(v.)" },
    { "id": 215, "date": "2026-01-12", "english": "Funny", "chinese": "有趣的;好笑的", "part_of_speech": "(adj.)" },
    { "id": 216, "date": "2026-01-12", "english": "Look out", "chinese": "小心;當心", "part_of_speech": "(ph.)" },
    { "id": 217, "date": "2026-01-12", "english": "mess", "chinese": "雜亂;髒亂", "part_of_speech": "(n.)" },
    { "id": 218, "date": "2026-01-12", "english": "delicious", "chinese": "美味的", "part_of_speech": "(adj.)" },
    { "id": 219, "date": "2026-01-12", "english": "recipe", "chinese": "食譜", "part_of_speech": "(n.)" },
    { "id": 220, "date": "2026-01-12", "english": "score...in the game", "chinese": "在比賽中得...分", "part_of_speech": "(ph.)" },
    { "id": 221, "date": "2026-01-14", "english": "Ingredient(s)", "chinese": "材料、成分", "part_of_speech": "(n.)" },
    { "id": 222, "date": "2026-01-14", "english": "Slice", "chinese": "薄片", "part_of_speech": "(n.)" },
    { "id": 223, "date": "2026-01-14", "english": "mayonnaise", "chinese": "美乃滋", "part_of_speech": "(n.)" },
    { "id": 224, "date": "2026-01-14", "english": "Decorate", "chinese": "裝飾", "part_of_speech": "(v.)" },
    { "id": 225, "date": "2026-01-14", "english": "caramel", "chinese": "焦糖", "part_of_speech": "(n.)" },
    { "id": 226, "date": "2026-01-14", "english": "worry about", "chinese": "擔心", "part_of_speech": "(ph.)" },
    { "id": 227, "date": "2026-01-15", "english": "vanilla", "chinese": "香草", "part_of_speech": "(n.)" },
    { "id": 228, "date": "2026-01-15", "english": "Sauce", "chinese": "醬汁", "part_of_speech": "(n.)" },
    { "id": 229, "date": "2026-01-15", "english": "future", "chinese": "未來", "part_of_speech": "(n.)" },
    { "id": 230, "date": "2026-01-15", "english": "hospital", "chinese": "醫院", "part_of_speech": "(n.)" },
    { "id": 231, "date": "2026-01-15", "english": "Job", "chinese": "工作", "part_of_speech": "(n.)" },
    { "id": 232, "date": "2026-01-15", "english": "Be good at", "chinese": "對...擅長", "part_of_speech": "(ph.)" },
    { "id": 233, "date": "2026-01-16", "english": "country", "chinese": "國家", "part_of_speech": "(n.)" },
    { "id": 234, "date": "2026-01-16", "english": "star", "chinese": "明星", "part_of_speech": "(n.)" },
    { "id": 235, "date": "2026-01-16", "english": "medal", "chinese": "獎牌", "part_of_speech": "(n.)" },
    { "id": 236, "date": "2026-01-16", "english": "interesting", "chinese": "引起興趣的", "part_of_speech": "(adj.)" },
    { "id": 237, "date": "2026-01-16", "english": "famous", "chinese": "有名的", "part_of_speech": "(adj.)" },
    { "id": 238, "date": "2026-01-19", "english": "flower", "chinese": "花", "part_of_speech": "(n.)" },
    { "id": 239, "date": "2026-01-19", "english": "fruit", "chinese": "水果", "part_of_speech": "(n.)" },
    { "id": 240, "date": "2026-01-19", "english": "leaf", "chinese": "葉子", "part_of_speech": "(n.)" },
    { "id": 241, "date": "2026-01-19", "english": "stem", "chinese": "莖", "part_of_speech": "(n.)" },
    { "id": 242, "date": "2026-01-19", "english": "root", "chinese": "根", "part_of_speech": "(n.)" },
    { "id": 243, "date": "2026-01-19", "english": "make somebody feel better", "chinese": "讓某人感覺好一點", "part_of_speech": "(ph.)" },
    { "id": 244, "date": "2026-01-21", "english": "seed", "chinese": "種子", "part_of_speech": "(n.)" },
    { "id": 245, "date": "2026-01-21", "english": "tomato", "chinese": "番茄", "part_of_speech": "(n.)" },
    { "id": 246, "date": "2026-01-21", "english": "cocoa bean(s)", "chinese": "可可豆", "part_of_speech": "(n.)" },
    { "id": 247, "date": "2026-01-21", "english": "pod", "chinese": "豆莢", "part_of_speech": "(n.)" },
    { "id": 248, "date": "2026-01-21", "english": "carrot", "chinese": "胡蘿蔔", "part_of_speech": "(n.)" },
    { "id": 249, "date": "2026-01-21", "english": "grow up", "chinese": "長大、成長", "part_of_speech": "(ph.)" },
    { "id": 250, "date": "2026-01-22", "english": "lettuce", "chinese": "萵苣", "part_of_speech": "(n.)" },
    { "id": 251, "date": "2026-01-22", "english": "care", "chinese": "關心；在乎", "part_of_speech": "(v.)" },
    { "id": 252, "date": "2026-01-22", "english": "rice", "chinese": "米", "part_of_speech": "(n.)" },
    { "id": 253, "date": "2026-01-22", "english": "be made of", "chinese": "由...製成", "part_of_speech": "(ph.)" },
    { "id": 254, "date": "2026-01-22", "english": "use", "chinese": "使用", "part_of_speech": "(v.)" },
    { "id": 255, "date": "2026-01-22", "english": "take care of", "chinese": "照顧；處理", "part_of_speech": "(ph.)" },
    { "id": 256, "date": "2026-01-23", "english": "vet", "chinese": "獸醫", "part_of_speech": "(n.)" },
    { "id": 257, "date": "2026-01-23", "english": "farmer", "chinese": "農夫", "part_of_speech": "(n.)" },
    { "id": 258, "date": "2026-01-23", "english": "scientist", "chinese": "科學家", "part_of_speech": "(n.)" },
    { "id": 259, "date": "2026-01-23", "english": "dentist", "chinese": "牙醫", "part_of_speech": "(n.)" },
    { "id": 260, "date": "2026-01-23", "english": "easy", "chinese": "容易的", "part_of_speech": "(adj.)" },
    { "id": 261, "date": "2026-01-26", "english": "cookie", "chinese": "曲奇、餅乾", "part_of_speech": "(n.)" },
    { "id": 262, "date": "2026-01-26", "english": "singer", "chinese": "歌手", "part_of_speech": "(n.)" },
    { "id": 263, "date": "2026-01-26", "english": "grandfather", "chinese": "祖父", "part_of_speech": "(n.)" },
    { "id": 264, "date": "2026-01-26", "english": "sound", "chinese": "聲音", "part_of_speech": "(n.)" },
    { "id": 265, "date": "2026-01-26", "english": "give birth", "chinese": "生孩子", "part_of_speech": "(ph.)" },
    { "id": 266, "date": "2026-01-26", "english": "be different from", "chinese": "不同於", "part_of_speech": "(ph.)" },
    { "id": 267, "date": "2026-01-27", "english": "talk", "chinese": "講話；談論", "part_of_speech": "(v.)" },
    { "id": 268, "date": "2026-01-27", "english": "noisy", "chinese": "喧鬧的", "part_of_speech": "(adj.)" },
    { "id": 269, "date": "2026-01-27", "english": "dangerous", "chinese": "危險的", "part_of_speech": "(adj.)" },
    { "id": 270, "date": "2026-01-27", "english": "whale", "chinese": "鯨魚", "part_of_speech": "(n.)" },
    { "id": 271, "date": "2026-01-27", "english": "dolphin", "chinese": "海豚", "part_of_speech": "(n.)" },
    { "id": 272, "date": "2026-01-28", "english": "turtle", "chinese": "海龜", "part_of_speech": "(n.)" },
    { "id": 273, "date": "2026-01-28", "english": "travel", "chinese": "旅行", "part_of_speech": "(v.)" },
    { "id": 274, "date": "2026-01-28", "english": "alone", "chinese": "獨自的(地)、單獨的(地)", "part_of_speech": "(adj.)(adv.)" },
    { "id": 275, "date": "2026-01-28", "english": "each other", "chinese": "彼此；互相", "part_of_speech": "(pron.)" },
    { "id": 276, "date": "2026-01-28", "english": "take care of", "chinese": "照顧；處理", "part_of_speech": "(ph.)" },
    { "id": 277, "date": "2026-01-28", "english": "scare away", "chinese": "把...嚇跑", "part_of_speech": "(ph.)" },
    { "id": 278, "date": "2026-01-29", "english": "adventure", "chinese": "冒險；奇遇", "part_of_speech": "(n.)" },
    { "id": 279, "date": "2026-01-29", "english": "explore", "chinese": "探索", "part_of_speech": "(v.)" },
    { "id": 280, "date": "2026-01-29", "english": "continent", "chinese": "洲、大陸", "part_of_speech": "(n.)" },
    { "id": 281, "date": "2026-01-29", "english": "teach", "chinese": "教", "part_of_speech": "(v.)" },
    { "id": 282, "date": "2026-01-29", "english": "naughty", "chinese": "淘氣的；調皮的", "part_of_speech": "(adj.)" },
    { "id": 283, "date": "2026-01-29", "english": "be interesting to", "chinese": "某事令人覺得有趣", "part_of_speech": "(ph.)" },
    { "id": 285, "date": "2026-02-02", "english": "swimming pool", "chinese": "游泳池", "part_of_speech": "(n.)" },
    { "id": 286, "date": "2026-02-02", "english": "restaurant", "chinese": "餐廳", "part_of_speech": "(n.)" },
    { "id": 287, "date": "2026-02-02", "english": "library", "chinese": "圖書館", "part_of_speech": "(n.)" },
    { "id": 288, "date": "2026-02-02", "english": "supermarket", "chinese": "超級市場", "part_of_speech": "(n.)" },
    { "id": 289, "date": "2026-02-02", "english": "cheer on", "chinese": "為...加油；打氣", "part_of_speech": "(ph.)" },
    { "id": 290, "date": "2026-02-03", "english": "shopping centre (Br) / shopping center (US)", "chinese": "購物中心", "part_of_speech": "(n.)" },
    { "id": 291, "date": "2026-02-03", "english": "car park (Br) / parking lot (US)", "chinese": "停車場", "part_of_speech": "(n.)" },
    { "id": 292, "date": "2026-02-03", "english": "post office", "chinese": "郵局", "part_of_speech": "(n.)" },
    { "id": 293, "date": "2026-02-03", "english": "station", "chinese": "車站", "part_of_speech": "(n.)" },
    { "id": 294, "date": "2026-02-03", "english": "lose (lose - lost - lost)", "chinese": "輸掉；丟失", "part_of_speech": "(v.)" },
    { "id": 295, "date": "2026-02-03", "english": "shout at", "chinese": "對...大聲喊叫", "part_of_speech": "(ph.)" },
    { "id": 296, "date": "2026-02-04", "english": "stretch", "chinese": "伸展、延伸", "part_of_speech": "(v.)" },
    { "id": 297, "date": "2026-02-04", "english": "pitcher", "chinese": "投手", "part_of_speech": "(n.)" },
    { "id": 298, "date": "2026-02-04", "english": "bat", "chinese": "打擊(v.) / 球棒、蝙蝠(n.)", "part_of_speech": "(v.) / (n.)" },
    { "id": 299, "date": "2026-02-04", "english": "catch", "chinese": "接住、抓住", "part_of_speech": "(v.)" },
    { "id": 300, "date": "2026-02-04", "english": "throw", "chinese": "丟、拋擲", "part_of_speech": "(v.)" },
    { "id": 301, "date": "2026-02-04", "english": "go to the dentist", "chinese": "看牙醫", "part_of_speech": "(ph.)" },
    { "id": 302, "date": "2026-02-05", "english": "score", "chinese": "得分", "part_of_speech": "(v.)" },
    { "id": 303, "date": "2026-02-05", "english": "tie", "chinese": "平手、繫", "part_of_speech": "(v.)" },
    { "id": 304, "date": "2026-02-05", "english": "baseball", "chinese": "棒球", "part_of_speech": "(n.)" },
    { "id": 305, "date": "2026-02-05", "english": "season", "chinese": "季節", "part_of_speech": "(n.)" },
    { "id": 306, "date": "2026-02-05", "english": "stand", "chinese": "站立", "part_of_speech": "(v.)" },
    { "id": 307, "date": "2026-02-05", "english": "stay up (late)", "chinese": "熬夜", "part_of_speech": "(ph.)" },
    { "id": 308, "date": "2026-02-09", "english": "visitor", "chinese": "訪客、遊客", "part_of_speech": "(n.)" },
    { "id": 309, "date": "2026-02-09", "english": "swing", "chinese": "擺動(v.); 鞦韆(n.)", "part_of_speech": "(v.) / (n.)" },
    { "id": 310, "date": "2026-02-09", "english": "enormous", "chinese": "巨大的", "part_of_speech": "(adj.)" },
    { "id": 311, "date": "2026-02-09", "english": "airport", "chinese": "機場", "part_of_speech": "(n.)" },
    { "id": 312, "date": "2026-02-09", "english": "slide", "chinese": "溜滑梯", "part_of_speech": "(n.)" },
    { "id": 313, "date": "2026-02-09", "english": "It's time to...", "chinese": "是...的時候了", "part_of_speech": "(ph.)" },
    { "id": 314, "date": "2026-02-10", "english": "important", "chinese": "重要的", "part_of_speech": "(adj.)" },
    { "id": 315, "date": "2026-02-10", "english": "actor", "chinese": "演員", "part_of_speech": "(n.)" },
    { "id": 316, "date": "2026-02-10", "english": "after school", "chinese": "放學後", "part_of_speech": "(ph.)" },
    { "id": 318, "date": "2026-02-10", "english": "hungry", "chinese": "飢餓的", "part_of_speech": "(adj.)" },
    { "id": 319, "date": "2026-02-10", "english": "head for + a place", "chinese": "朝...走去", "part_of_speech": "(ph.)" },
    { "id": 320, "date": "2026-02-11", "english": "breakfast", "chinese": "早餐", "part_of_speech": "(n.)" },
    { "id": 321, "date": "2026-02-11", "english": "cover", "chinese": "蓋住；遮蓋", "part_of_speech": "(v.)" },
    { "id": 322, "date": "2026-02-11", "english": "receive", "chinese": "收到", "part_of_speech": "(v.)" },
    { "id": 323, "date": "2026-02-11", "english": "shout", "chinese": "呼喊；吼叫", "part_of_speech": "(v.)" },
    { "id": 324, "date": "2026-02-11", "english": "hand", "chinese": "將...交給", "part_of_speech": "(v.)" },
    { "id": 325, "date": "2026-02-11", "english": "as busy as a bee", "chinese": "忙個不停", "part_of_speech": "(ph.)" },
    { "id": 326, "date": "2026-02-12", "english": "path", "chinese": "小道", "part_of_speech": "(n.)" },
    { "id": 327, "date": "2026-02-12", "english": "bridge", "chinese": "橋", "part_of_speech": "(n.)" },
    { "id": 328, "date": "2026-02-12", "english": "river", "chinese": "河", "part_of_speech": "(n.)" },
    { "id": 329, "date": "2026-02-12", "english": "area", "chinese": "區域；範圍", "part_of_speech": "(n.)" },
    { "id": 330, "date": "2026-02-12", "english": "wood", "chinese": "木頭；樹林", "part_of_speech": "(n.)" },
    { "id": 331, "date": "2026-02-12", "english": "as sick as a dog", "chinese": "非常虛弱；病得很嚴重", "part_of_speech": "(ph.)" },
    { "id": 332, "date": "2026-02-23", "english": "adventure", "chinese": "冒險；奇遇", "part_of_speech": "(n.)" },
    { "id": 333, "date": "2026-02-23", "english": "symbol", "chinese": "符號；標誌；象徵", "part_of_speech": "(n.)" },
    { "id": 334, "date": "2026-02-23", "english": "cross", "chinese": "越過；跨越", "part_of_speech": "(v.)" },
    { "id": 335, "date": "2026-02-23", "english": "island", "chinese": "島；島嶼", "part_of_speech": "(n.)" },
    { "id": 336, "date": "2026-02-23", "english": "return", "chinese": "返回；歸還", "part_of_speech": "(v.)" },
    { "id": 337, "date": "2026-02-23", "english": "as hungry as a bear", "chinese": "非常餓", "part_of_speech": "(ph.)" },
    { "id": 338, "date": "2026-02-25", "english": "countryside", "chinese": "農村；鄉下", "part_of_speech": "(n.)" },
    { "id": 339, "date": "2026-02-25", "english": "hard / soft", "chinese": "困難的(1)；堅硬的(2) / 柔軟的", "part_of_speech": "(adj.)" },
    { "id": 340, "date": "2026-02-25", "english": "salt", "chinese": "鹽", "part_of_speech": "(n.)" },
    { "id": 341, "date": "2026-02-25", "english": "delicious", "chinese": "美味的", "part_of_speech": "(adj.)" },
    { "id": 342, "date": "2026-02-25", "english": "pour", "chinese": "倒、注入", "part_of_speech": "(v.)" },
    { "id": 343, "date": "2026-02-25", "english": "eat out", "chinese": "外出用餐", "part_of_speech": "(ph.)" },
    { "id": 344, "date": "2026-02-26", "english": "shake", "chinese": "搖動；發抖", "part_of_speech": "(v.)" },
    { "id": 345, "date": "2026-02-26", "english": "dessert", "chinese": "甜點", "part_of_speech": "(n.)" },
    { "id": 346, "date": "2026-02-26", "english": "sweet", "chinese": "甜的；溫和的", "part_of_speech": "(adj.)" },
    { "id": 347, "date": "2026-02-26", "english": "fresh", "chinese": "新鮮的；清新的", "part_of_speech": "(adj.)" },
    { "id": 348, "date": "2026-02-26", "english": "thick", "chinese": "厚的；濃的", "part_of_speech": "(adj.)" },
    { "id": 349, "date": "2026-02-26", "english": "act like...", "chinese": "表現得像...", "part_of_speech": "(ph.)" },
    { "id": 350, "date": "2026-02-27", "english": "school", "chinese": "學校", "part_of_speech": "(n.)" },
    { "id": 351, "date": "2026-02-27", "english": "park", "chinese": "公園", "part_of_speech": "(n.)" },
    { "id": 352, "date": "2026-02-27", "english": "computer", "chinese": "電腦", "part_of_speech": "(n.)" },
    { "id": 353, "date": "2026-02-27", "english": "team", "chinese": "隊伍", "part_of_speech": "(n.)" },
    { "id": 354, "date": "2026-02-27", "english": "picnic", "chinese": "野餐", "part_of_speech": "(n.)" },
    { "id": 355, "date": "2026-02-27", "english": "beach", "chinese": "海灘；沙灘", "part_of_speech": "(n.)" },
    { "id": 356, "date": "2026-02-27", "english": "shop", "chinese": "商店", "part_of_speech": "(n.)" },
    { "id": 357, "date": "2026-02-27", "english": "present", "chinese": "禮物", "part_of_speech": "(n.)" },
    { "id": 358, "date": "2026-02-27", "english": "balloon", "chinese": "氣球", "part_of_speech": "(n.)" },
    { "id": 359, "date": "2026-02-27", "english": "surprise", "chinese": "驚喜", "part_of_speech": "(n.)" },
    { "id": 360, "date": "2026-02-27", "english": "restaurant", "chinese": "餐廳", "part_of_speech": "(n.)" },
    { "id": 361, "date": "2026-02-27", "english": "bedroom", "chinese": "臥室", "part_of_speech": "(n.)" },
    { "id": 362, "date": "2026-02-27", "english": "kitchen", "chinese": "廚房", "part_of_speech": "(n.)" },
    { "id": 363, "date": "2026-02-27", "english": "sugar", "chinese": "糖", "part_of_speech": "(n.)" },
    { "id": 364, "date": "2026-02-27", "english": "fruit", "chinese": "水果；果實", "part_of_speech": "(n.)" },
    { "id": 365, "date": "2026-02-27", "english": "different", "chinese": "不一樣的", "part_of_speech": "(adj.)" },
    { "id": 366, "date": "2026-02-27", "english": "straight", "chinese": "筆直地；坦率地；直接", "part_of_speech": "(adv.)" },
    { "id": 367, "date": "2026-02-27", "english": "show", "chinese": "顯示；說明", "part_of_speech": "(v.)" },
];

const processedData = serverData.map((word, index) => ({ ...word, id: index + 1 }));

export default processedData; 